/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheeled_brick_pitch_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {4, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};

/* wheeled_brick_pitch_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[])->(o0[4],o1[4x4],o2[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a01=6.1866666666666665e+00;
  a02=1.1754666666666667e+02;
  a03=8.;
  a04=arg[0]? arg[0][1] : 0;
  a05=cos(a04);
  a06=(a03*a05);
  a07=casadi_sq(a06);
  a02=(a02-a07);
  a01=(a01/a02);
  a07=casadi_sq(a00);
  a07=(a03*a07);
  a04=sin(a04);
  a08=(a07*a04);
  a09=arg[3]? arg[3][0] : 0;
  a10=arg[3]? arg[3][1] : 0;
  a09=(a09+a10);
  a10=2.0000000000000001e-01;
  a09=(a09/a10);
  a08=(a08+a09);
  a09=(a01*a08);
  a10=(a06/a02);
  a11=7.8480000000000004e+01;
  a12=(a11*a04);
  a13=(a10*a12);
  a09=(a09-a13);
  if (res[0]!=0) res[0][2]=a09;
  a09=19.;
  a09=(a09/a02);
  a13=(a09*a12);
  a14=(a10*a08);
  a13=(a13-a14);
  if (res[0]!=0) res[0][3]=a13;
  a13=arg[1]? arg[1][2] : 0;
  if (res[1]!=0) res[1][0]=a13;
  a13=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][1]=a13;
  a00=(a00+a00);
  a13=(a00*a13);
  a13=(a03*a13);
  a13=(a04*a13);
  a14=arg[1]? arg[1][1] : 0;
  a15=(a05*a14);
  a16=(a07*a15);
  a13=(a13+a16);
  a16=(a01*a13);
  a17=(a01/a02);
  a06=(a06+a06);
  a14=(a04*a14);
  a14=(a03*a14);
  a18=(a06*a14);
  a19=(a17*a18);
  a19=(a08*a19);
  a16=(a16-a19);
  a15=(a11*a15);
  a19=(a10*a15);
  a14=(a14/a02);
  a20=(a10/a02);
  a21=(a20*a18);
  a14=(a14+a21);
  a21=(a12*a14);
  a19=(a19-a21);
  a16=(a16-a19);
  if (res[1]!=0) res[1][2]=a16;
  a15=(a09*a15);
  a16=(a09/a02);
  a18=(a16*a18);
  a18=(a12*a18);
  a15=(a15-a18);
  a13=(a10*a13);
  a14=(a08*a14);
  a13=(a13-a14);
  a15=(a15-a13);
  if (res[1]!=0) res[1][3]=a15;
  a15=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][4]=a15;
  a15=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][5]=a15;
  a15=(a00*a15);
  a15=(a03*a15);
  a15=(a04*a15);
  a13=arg[1]? arg[1][5] : 0;
  a14=(a05*a13);
  a18=(a07*a14);
  a15=(a15+a18);
  a18=(a01*a15);
  a13=(a04*a13);
  a13=(a03*a13);
  a19=(a06*a13);
  a21=(a17*a19);
  a21=(a08*a21);
  a18=(a18-a21);
  a14=(a11*a14);
  a21=(a10*a14);
  a13=(a13/a02);
  a22=(a20*a19);
  a13=(a13+a22);
  a22=(a12*a13);
  a21=(a21-a22);
  a18=(a18-a21);
  if (res[1]!=0) res[1][6]=a18;
  a14=(a09*a14);
  a19=(a16*a19);
  a19=(a12*a19);
  a14=(a14-a19);
  a15=(a10*a15);
  a13=(a08*a13);
  a15=(a15-a13);
  a14=(a14-a15);
  if (res[1]!=0) res[1][7]=a14;
  a14=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][8]=a14;
  a14=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][9]=a14;
  a14=(a00*a14);
  a14=(a03*a14);
  a14=(a04*a14);
  a15=arg[1]? arg[1][9] : 0;
  a13=(a05*a15);
  a19=(a07*a13);
  a14=(a14+a19);
  a19=(a01*a14);
  a15=(a04*a15);
  a15=(a03*a15);
  a18=(a06*a15);
  a21=(a17*a18);
  a21=(a08*a21);
  a19=(a19-a21);
  a13=(a11*a13);
  a21=(a10*a13);
  a15=(a15/a02);
  a22=(a20*a18);
  a15=(a15+a22);
  a22=(a12*a15);
  a21=(a21-a22);
  a19=(a19-a21);
  if (res[1]!=0) res[1][10]=a19;
  a13=(a09*a13);
  a18=(a16*a18);
  a18=(a12*a18);
  a13=(a13-a18);
  a14=(a10*a14);
  a15=(a08*a15);
  a14=(a14-a15);
  a13=(a13-a14);
  if (res[1]!=0) res[1][11]=a13;
  a13=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][12]=a13;
  a13=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][13]=a13;
  a13=(a00*a13);
  a13=(a03*a13);
  a13=(a04*a13);
  a14=arg[1]? arg[1][13] : 0;
  a15=(a05*a14);
  a18=(a07*a15);
  a13=(a13+a18);
  a18=(a01*a13);
  a14=(a04*a14);
  a14=(a03*a14);
  a19=(a06*a14);
  a21=(a17*a19);
  a21=(a08*a21);
  a18=(a18-a21);
  a15=(a11*a15);
  a21=(a10*a15);
  a14=(a14/a02);
  a22=(a20*a19);
  a14=(a14+a22);
  a22=(a12*a14);
  a21=(a21-a22);
  a18=(a18-a21);
  if (res[1]!=0) res[1][14]=a18;
  a15=(a09*a15);
  a19=(a16*a19);
  a19=(a12*a19);
  a15=(a15-a19);
  a13=(a10*a13);
  a14=(a08*a14);
  a13=(a13-a14);
  a15=(a15-a13);
  if (res[1]!=0) res[1][15]=a15;
  a15=arg[2]? arg[2][2] : 0;
  if (res[2]!=0) res[2][0]=a15;
  a15=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][1]=a15;
  a13=5.;
  a14=(a13*a01);
  a15=(a00*a15);
  a15=(a03*a15);
  a15=(a04*a15);
  a19=arg[2]? arg[2][1] : 0;
  a18=(a05*a19);
  a21=(a07*a18);
  a15=(a15+a21);
  a21=(a01*a15);
  a19=(a04*a19);
  a19=(a03*a19);
  a22=(a06*a19);
  a23=(a17*a22);
  a23=(a08*a23);
  a21=(a21-a23);
  a18=(a11*a18);
  a23=(a10*a18);
  a19=(a19/a02);
  a24=(a20*a22);
  a19=(a19+a24);
  a24=(a12*a19);
  a23=(a23-a24);
  a21=(a21-a23);
  a21=(a14+a21);
  if (res[2]!=0) res[2][2]=a21;
  a18=(a09*a18);
  a22=(a16*a22);
  a22=(a12*a22);
  a18=(a18-a22);
  a15=(a10*a15);
  a19=(a08*a19);
  a15=(a15-a19);
  a18=(a18-a15);
  a13=(a13*a10);
  a18=(a18-a13);
  if (res[2]!=0) res[2][3]=a18;
  a18=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][4]=a18;
  a18=arg[2]? arg[2][7] : 0;
  if (res[2]!=0) res[2][5]=a18;
  a00=(a00*a18);
  a00=(a03*a00);
  a00=(a04*a00);
  a18=arg[2]? arg[2][5] : 0;
  a05=(a05*a18);
  a07=(a07*a05);
  a00=(a00+a07);
  a01=(a01*a00);
  a04=(a04*a18);
  a03=(a03*a04);
  a06=(a06*a03);
  a17=(a17*a06);
  a17=(a08*a17);
  a01=(a01-a17);
  a11=(a11*a05);
  a05=(a10*a11);
  a03=(a03/a02);
  a20=(a20*a06);
  a03=(a03+a20);
  a20=(a12*a03);
  a05=(a05-a20);
  a01=(a01-a05);
  a14=(a14+a01);
  if (res[2]!=0) res[2][6]=a14;
  a09=(a09*a11);
  a16=(a16*a06);
  a12=(a12*a16);
  a09=(a09-a12);
  a10=(a10*a00);
  a08=(a08*a03);
  a10=(a10-a08);
  a09=(a09-a10);
  a09=(a09-a13);
  if (res[2]!=0) res[2][7]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_pitch_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheeled_brick_pitch_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_pitch_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_pitch_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheeled_brick_pitch_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_pitch_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_pitch_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_pitch_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_pitch_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_pitch_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real wheeled_brick_pitch_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_pitch_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_pitch_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_pitch_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_pitch_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheeled_brick_pitch_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_pitch_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
