/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_simplified_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {4, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};

/* model_simplified_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[4])->(o0[4],o1[4x4],o2[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=5.0000000000000000e-01;
  a03=21.;
  a04=arg[4]? arg[4][0] : 0;
  a03=(a03+a04);
  a02=(a02*a03);
  a04=arg[0]? arg[0][1] : 0;
  a05=cos(a04);
  a06=arg[4]? arg[4][3] : 0;
  a07=(a05*a06);
  a04=sin(a04);
  a08=arg[4]? arg[4][2] : 0;
  a09=(a04*a08);
  a07=(a07-a09);
  a09=(a07+a07);
  a10=(a07*a09);
  a11=(a05*a08);
  a12=(a04*a06);
  a11=(a11+a12);
  a12=(a11+a11);
  a13=(a11*a12);
  a10=(a10+a13);
  a10=(a02*a10);
  a13=arg[4]? arg[4][1] : 0;
  a10=(a10+a13);
  a13=6.;
  a13=(a13+a03);
  a14=(a13*a10);
  a15=(a02*a09);
  a16=2.;
  a17=(a16*a07);
  a17=(a02*a17);
  a18=(a15*a17);
  a14=(a14-a18);
  a10=(a10/a14);
  a18=arg[3]? arg[3][0] : 0;
  a19=arg[3]? arg[3][1] : 0;
  a18=(a18+a19);
  a19=2.0000000000000001e-01;
  a18=(a18/a19);
  a19=(a08*a01);
  a20=(a19*a05);
  a21=(a06*a01);
  a22=(a21*a04);
  a20=(a20+a22);
  a22=(a20+a20);
  a23=(a02*a22);
  a24=(a23*a01);
  a18=(a18+a24);
  a24=(a10*a18);
  a25=(a15/a14);
  a26=(a21*a05);
  a27=(a19*a04);
  a28=(a26-a27);
  a29=(a28+a28);
  a30=(a11*a29);
  a31=(a06*a05);
  a32=(a08*a04);
  a31=(a31-a32);
  a32=(a22*a31);
  a30=(a30+a32);
  a32=(a07*a22);
  a00=(a00-a27);
  a00=(a00+a26);
  a00=(a00+a00);
  a26=(a06*a04);
  a27=(a08*a05);
  a26=(a26+a27);
  a27=(a00*a26);
  a32=(a32+a27);
  a30=(a30-a32);
  a30=(a02*a30);
  a32=(a30*a01);
  a27=(a22*a28);
  a33=(a00*a20);
  a27=(a27-a33);
  a27=(a02*a27);
  a33=9.8100000000000005e+00;
  a33=(a33*a03);
  a03=(a33*a26);
  a27=(a27+a03);
  a32=(a32-a27);
  a27=(a25*a32);
  a24=(a24+a27);
  if (res[0]!=0) res[0][2]=a24;
  a24=(a17/a14);
  a27=(a24*a18);
  a03=(a13/a14);
  a34=(a03*a32);
  a27=(a27+a34);
  a27=(-a27);
  if (res[0]!=0) res[0][3]=a27;
  a27=arg[1]? arg[1][2] : 0;
  if (res[1]!=0) res[1][0]=a27;
  a34=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][1]=a34;
  a35=arg[1]? arg[1][1] : 0;
  a36=(a05*a35);
  a37=(a06*a36);
  a35=(a04*a35);
  a38=(a08*a35);
  a37=(a37-a38);
  a38=(a12*a37);
  a39=(a37+a37);
  a39=(a11*a39);
  a38=(a38+a39);
  a39=(a06*a35);
  a40=(a08*a36);
  a39=(a39+a40);
  a40=(a09*a39);
  a41=(a39+a39);
  a42=(a07*a41);
  a40=(a40+a42);
  a38=(a38-a40);
  a38=(a02*a38);
  a40=(a38/a14);
  a42=(a10/a14);
  a38=(a13*a38);
  a41=(a02*a41);
  a43=(a17*a41);
  a44=(a16*a39);
  a44=(a02*a44);
  a45=(a15*a44);
  a43=(a43+a45);
  a38=(a38+a43);
  a43=(a42*a38);
  a40=(a40-a43);
  a40=(a18*a40);
  a43=(a08*a34);
  a45=(a05*a43);
  a46=(a19*a35);
  a45=(a45-a46);
  a46=(a06*a34);
  a47=(a04*a46);
  a48=(a21*a36);
  a47=(a47+a48);
  a45=(a45+a47);
  a47=(a45+a45);
  a48=(a02*a47);
  a48=(a01*a48);
  a49=(a23*a34);
  a48=(a48+a49);
  a49=(a10*a48);
  a40=(a40+a49);
  a49=(a29*a37);
  a46=(a05*a46);
  a35=(a21*a35);
  a46=(a46-a35);
  a43=(a04*a43);
  a36=(a19*a36);
  a43=(a43+a36);
  a36=(a46-a43);
  a35=(a36+a36);
  a35=(a11*a35);
  a49=(a49+a35);
  a35=(a31*a47);
  a39=(a22*a39);
  a35=(a35-a39);
  a49=(a49+a35);
  a35=(a07*a47);
  a35=(a35-a39);
  a27=(a27-a43);
  a27=(a27+a46);
  a27=(a27+a27);
  a46=(a26*a27);
  a43=(a00*a37);
  a46=(a46+a43);
  a35=(a35+a46);
  a49=(a49-a35);
  a49=(a02*a49);
  a49=(a01*a49);
  a34=(a30*a34);
  a49=(a49+a34);
  a47=(a28*a47);
  a36=(a22*a36);
  a47=(a47+a36);
  a27=(a20*a27);
  a45=(a00*a45);
  a27=(a27+a45);
  a47=(a47-a27);
  a47=(a02*a47);
  a37=(a33*a37);
  a47=(a47+a37);
  a49=(a49-a47);
  a47=(a25*a49);
  a41=(a41/a14);
  a37=(a25/a14);
  a27=(a37*a38);
  a41=(a41+a27);
  a41=(a32*a41);
  a47=(a47-a41);
  a40=(a40+a47);
  if (res[1]!=0) res[1][2]=a40;
  a48=(a24*a48);
  a44=(a44/a14);
  a40=(a24/a14);
  a47=(a40*a38);
  a44=(a44+a47);
  a44=(a18*a44);
  a48=(a48-a44);
  a49=(a03*a49);
  a44=(a03/a14);
  a38=(a44*a38);
  a38=(a32*a38);
  a49=(a49-a38);
  a48=(a48+a49);
  a48=(-a48);
  if (res[1]!=0) res[1][3]=a48;
  a48=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][4]=a48;
  a49=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][5]=a49;
  a38=arg[1]? arg[1][5] : 0;
  a47=(a05*a38);
  a41=(a06*a47);
  a38=(a04*a38);
  a27=(a08*a38);
  a41=(a41-a27);
  a27=(a12*a41);
  a45=(a41+a41);
  a45=(a11*a45);
  a27=(a27+a45);
  a45=(a06*a38);
  a36=(a08*a47);
  a45=(a45+a36);
  a36=(a09*a45);
  a34=(a45+a45);
  a35=(a07*a34);
  a36=(a36+a35);
  a27=(a27-a36);
  a27=(a02*a27);
  a36=(a27/a14);
  a27=(a13*a27);
  a34=(a02*a34);
  a35=(a17*a34);
  a46=(a16*a45);
  a46=(a02*a46);
  a43=(a15*a46);
  a35=(a35+a43);
  a27=(a27+a35);
  a35=(a42*a27);
  a36=(a36-a35);
  a36=(a18*a36);
  a35=(a08*a49);
  a43=(a05*a35);
  a39=(a19*a38);
  a43=(a43-a39);
  a39=(a06*a49);
  a50=(a04*a39);
  a51=(a21*a47);
  a50=(a50+a51);
  a43=(a43+a50);
  a50=(a43+a43);
  a51=(a02*a50);
  a51=(a01*a51);
  a52=(a23*a49);
  a51=(a51+a52);
  a52=(a10*a51);
  a36=(a36+a52);
  a52=(a29*a41);
  a39=(a05*a39);
  a38=(a21*a38);
  a39=(a39-a38);
  a35=(a04*a35);
  a47=(a19*a47);
  a35=(a35+a47);
  a47=(a39-a35);
  a38=(a47+a47);
  a38=(a11*a38);
  a52=(a52+a38);
  a38=(a31*a50);
  a45=(a22*a45);
  a38=(a38-a45);
  a52=(a52+a38);
  a38=(a07*a50);
  a38=(a38-a45);
  a48=(a48-a35);
  a48=(a48+a39);
  a48=(a48+a48);
  a39=(a26*a48);
  a35=(a00*a41);
  a39=(a39+a35);
  a38=(a38+a39);
  a52=(a52-a38);
  a52=(a02*a52);
  a52=(a01*a52);
  a49=(a30*a49);
  a52=(a52+a49);
  a50=(a28*a50);
  a47=(a22*a47);
  a50=(a50+a47);
  a48=(a20*a48);
  a43=(a00*a43);
  a48=(a48+a43);
  a50=(a50-a48);
  a50=(a02*a50);
  a41=(a33*a41);
  a50=(a50+a41);
  a52=(a52-a50);
  a50=(a25*a52);
  a34=(a34/a14);
  a41=(a37*a27);
  a34=(a34+a41);
  a34=(a32*a34);
  a50=(a50-a34);
  a36=(a36+a50);
  if (res[1]!=0) res[1][6]=a36;
  a51=(a24*a51);
  a46=(a46/a14);
  a36=(a40*a27);
  a46=(a46+a36);
  a46=(a18*a46);
  a51=(a51-a46);
  a52=(a03*a52);
  a27=(a44*a27);
  a27=(a32*a27);
  a52=(a52-a27);
  a51=(a51+a52);
  a51=(-a51);
  if (res[1]!=0) res[1][7]=a51;
  a51=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][8]=a51;
  a52=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][9]=a52;
  a27=arg[1]? arg[1][9] : 0;
  a46=(a05*a27);
  a36=(a06*a46);
  a27=(a04*a27);
  a50=(a08*a27);
  a36=(a36-a50);
  a50=(a12*a36);
  a34=(a36+a36);
  a34=(a11*a34);
  a50=(a50+a34);
  a34=(a06*a27);
  a41=(a08*a46);
  a34=(a34+a41);
  a41=(a09*a34);
  a48=(a34+a34);
  a43=(a07*a48);
  a41=(a41+a43);
  a50=(a50-a41);
  a50=(a02*a50);
  a41=(a50/a14);
  a50=(a13*a50);
  a48=(a02*a48);
  a43=(a17*a48);
  a47=(a16*a34);
  a47=(a02*a47);
  a49=(a15*a47);
  a43=(a43+a49);
  a50=(a50+a43);
  a43=(a42*a50);
  a41=(a41-a43);
  a41=(a18*a41);
  a43=(a08*a52);
  a49=(a05*a43);
  a38=(a19*a27);
  a49=(a49-a38);
  a38=(a06*a52);
  a39=(a04*a38);
  a35=(a21*a46);
  a39=(a39+a35);
  a49=(a49+a39);
  a39=(a49+a49);
  a35=(a02*a39);
  a35=(a01*a35);
  a45=(a23*a52);
  a35=(a35+a45);
  a45=(a10*a35);
  a41=(a41+a45);
  a45=(a29*a36);
  a38=(a05*a38);
  a27=(a21*a27);
  a38=(a38-a27);
  a43=(a04*a43);
  a46=(a19*a46);
  a43=(a43+a46);
  a46=(a38-a43);
  a27=(a46+a46);
  a27=(a11*a27);
  a45=(a45+a27);
  a27=(a31*a39);
  a34=(a22*a34);
  a27=(a27-a34);
  a45=(a45+a27);
  a27=(a07*a39);
  a27=(a27-a34);
  a51=(a51-a43);
  a51=(a51+a38);
  a51=(a51+a51);
  a38=(a26*a51);
  a43=(a00*a36);
  a38=(a38+a43);
  a27=(a27+a38);
  a45=(a45-a27);
  a45=(a02*a45);
  a45=(a01*a45);
  a52=(a30*a52);
  a45=(a45+a52);
  a39=(a28*a39);
  a46=(a22*a46);
  a39=(a39+a46);
  a51=(a20*a51);
  a49=(a00*a49);
  a51=(a51+a49);
  a39=(a39-a51);
  a39=(a02*a39);
  a36=(a33*a36);
  a39=(a39+a36);
  a45=(a45-a39);
  a39=(a25*a45);
  a48=(a48/a14);
  a36=(a37*a50);
  a48=(a48+a36);
  a48=(a32*a48);
  a39=(a39-a48);
  a41=(a41+a39);
  if (res[1]!=0) res[1][10]=a41;
  a35=(a24*a35);
  a47=(a47/a14);
  a41=(a40*a50);
  a47=(a47+a41);
  a47=(a18*a47);
  a35=(a35-a47);
  a45=(a03*a45);
  a50=(a44*a50);
  a50=(a32*a50);
  a45=(a45-a50);
  a35=(a35+a45);
  a35=(-a35);
  if (res[1]!=0) res[1][11]=a35;
  a35=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][12]=a35;
  a45=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][13]=a45;
  a50=arg[1]? arg[1][13] : 0;
  a47=(a05*a50);
  a41=(a06*a47);
  a50=(a04*a50);
  a39=(a08*a50);
  a41=(a41-a39);
  a39=(a12*a41);
  a48=(a41+a41);
  a48=(a11*a48);
  a39=(a39+a48);
  a48=(a06*a50);
  a36=(a08*a47);
  a48=(a48+a36);
  a36=(a09*a48);
  a51=(a48+a48);
  a49=(a07*a51);
  a36=(a36+a49);
  a39=(a39-a36);
  a39=(a02*a39);
  a36=(a39/a14);
  a39=(a13*a39);
  a51=(a02*a51);
  a49=(a17*a51);
  a46=(a16*a48);
  a46=(a02*a46);
  a52=(a15*a46);
  a49=(a49+a52);
  a39=(a39+a49);
  a49=(a42*a39);
  a36=(a36-a49);
  a36=(a18*a36);
  a49=(a08*a45);
  a52=(a05*a49);
  a27=(a19*a50);
  a52=(a52-a27);
  a27=(a06*a45);
  a38=(a04*a27);
  a43=(a21*a47);
  a38=(a38+a43);
  a52=(a52+a38);
  a38=(a52+a52);
  a43=(a02*a38);
  a43=(a01*a43);
  a34=(a23*a45);
  a43=(a43+a34);
  a34=(a10*a43);
  a36=(a36+a34);
  a34=(a29*a41);
  a27=(a05*a27);
  a50=(a21*a50);
  a27=(a27-a50);
  a49=(a04*a49);
  a47=(a19*a47);
  a49=(a49+a47);
  a47=(a27-a49);
  a50=(a47+a47);
  a50=(a11*a50);
  a34=(a34+a50);
  a50=(a31*a38);
  a48=(a22*a48);
  a50=(a50-a48);
  a34=(a34+a50);
  a50=(a07*a38);
  a50=(a50-a48);
  a35=(a35-a49);
  a35=(a35+a27);
  a35=(a35+a35);
  a27=(a26*a35);
  a49=(a00*a41);
  a27=(a27+a49);
  a50=(a50+a27);
  a34=(a34-a50);
  a34=(a02*a34);
  a34=(a01*a34);
  a45=(a30*a45);
  a34=(a34+a45);
  a38=(a28*a38);
  a47=(a22*a47);
  a38=(a38+a47);
  a35=(a20*a35);
  a52=(a00*a52);
  a35=(a35+a52);
  a38=(a38-a35);
  a38=(a02*a38);
  a41=(a33*a41);
  a38=(a38+a41);
  a34=(a34-a38);
  a38=(a25*a34);
  a51=(a51/a14);
  a41=(a37*a39);
  a51=(a51+a41);
  a51=(a32*a51);
  a38=(a38-a51);
  a36=(a36+a38);
  if (res[1]!=0) res[1][14]=a36;
  a43=(a24*a43);
  a46=(a46/a14);
  a36=(a40*a39);
  a46=(a46+a36);
  a46=(a18*a46);
  a43=(a43-a46);
  a34=(a03*a34);
  a39=(a44*a39);
  a39=(a32*a39);
  a34=(a34-a39);
  a43=(a43+a34);
  a43=(-a43);
  if (res[1]!=0) res[1][15]=a43;
  a43=arg[2]? arg[2][2] : 0;
  if (res[2]!=0) res[2][0]=a43;
  a34=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][1]=a34;
  a39=5.;
  a46=(a39*a10);
  a36=arg[2]? arg[2][1] : 0;
  a38=(a05*a36);
  a51=(a06*a38);
  a36=(a04*a36);
  a41=(a08*a36);
  a51=(a51-a41);
  a41=(a12*a51);
  a35=(a51+a51);
  a35=(a11*a35);
  a41=(a41+a35);
  a35=(a06*a36);
  a52=(a08*a38);
  a35=(a35+a52);
  a52=(a09*a35);
  a47=(a35+a35);
  a45=(a07*a47);
  a52=(a52+a45);
  a41=(a41-a52);
  a41=(a02*a41);
  a52=(a41/a14);
  a41=(a13*a41);
  a47=(a02*a47);
  a45=(a17*a47);
  a50=(a16*a35);
  a50=(a02*a50);
  a27=(a15*a50);
  a45=(a45+a27);
  a41=(a41+a45);
  a45=(a42*a41);
  a52=(a52-a45);
  a52=(a18*a52);
  a45=(a08*a34);
  a27=(a05*a45);
  a49=(a19*a36);
  a27=(a27-a49);
  a49=(a06*a34);
  a48=(a04*a49);
  a53=(a21*a38);
  a48=(a48+a53);
  a27=(a27+a48);
  a48=(a27+a27);
  a53=(a02*a48);
  a53=(a01*a53);
  a54=(a23*a34);
  a53=(a53+a54);
  a54=(a10*a53);
  a52=(a52+a54);
  a54=(a29*a51);
  a49=(a05*a49);
  a36=(a21*a36);
  a49=(a49-a36);
  a45=(a04*a45);
  a38=(a19*a38);
  a45=(a45+a38);
  a38=(a49-a45);
  a36=(a38+a38);
  a36=(a11*a36);
  a54=(a54+a36);
  a36=(a31*a48);
  a35=(a22*a35);
  a36=(a36-a35);
  a54=(a54+a36);
  a36=(a07*a48);
  a36=(a36-a35);
  a43=(a43-a45);
  a43=(a43+a49);
  a43=(a43+a43);
  a49=(a26*a43);
  a45=(a00*a51);
  a49=(a49+a45);
  a36=(a36+a49);
  a54=(a54-a36);
  a54=(a02*a54);
  a54=(a01*a54);
  a34=(a30*a34);
  a54=(a54+a34);
  a48=(a28*a48);
  a38=(a22*a38);
  a48=(a48+a38);
  a43=(a20*a43);
  a27=(a00*a27);
  a43=(a43+a27);
  a48=(a48-a43);
  a48=(a02*a48);
  a51=(a33*a51);
  a48=(a48+a51);
  a54=(a54-a48);
  a48=(a25*a54);
  a47=(a47/a14);
  a51=(a37*a41);
  a47=(a47+a51);
  a47=(a32*a47);
  a48=(a48-a47);
  a52=(a52+a48);
  a52=(a46+a52);
  if (res[2]!=0) res[2][2]=a52;
  a39=(a39*a24);
  a53=(a24*a53);
  a50=(a50/a14);
  a52=(a40*a41);
  a50=(a50+a52);
  a50=(a18*a50);
  a53=(a53-a50);
  a54=(a03*a54);
  a41=(a44*a41);
  a41=(a32*a41);
  a54=(a54-a41);
  a53=(a53+a54);
  a53=(a39+a53);
  a53=(-a53);
  if (res[2]!=0) res[2][3]=a53;
  a53=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][4]=a53;
  a54=arg[2]? arg[2][7] : 0;
  if (res[2]!=0) res[2][5]=a54;
  a41=arg[2]? arg[2][5] : 0;
  a50=(a05*a41);
  a52=(a06*a50);
  a41=(a04*a41);
  a48=(a08*a41);
  a52=(a52-a48);
  a12=(a12*a52);
  a48=(a52+a52);
  a48=(a11*a48);
  a12=(a12+a48);
  a48=(a06*a41);
  a47=(a08*a50);
  a48=(a48+a47);
  a09=(a09*a48);
  a47=(a48+a48);
  a51=(a07*a47);
  a09=(a09+a51);
  a12=(a12-a09);
  a12=(a02*a12);
  a09=(a12/a14);
  a13=(a13*a12);
  a47=(a02*a47);
  a17=(a17*a47);
  a16=(a16*a48);
  a16=(a02*a16);
  a15=(a15*a16);
  a17=(a17+a15);
  a13=(a13+a17);
  a42=(a42*a13);
  a09=(a09-a42);
  a09=(a18*a09);
  a08=(a08*a54);
  a42=(a05*a08);
  a17=(a19*a41);
  a42=(a42-a17);
  a06=(a06*a54);
  a17=(a04*a06);
  a15=(a21*a50);
  a17=(a17+a15);
  a42=(a42+a17);
  a17=(a42+a42);
  a15=(a02*a17);
  a15=(a01*a15);
  a23=(a23*a54);
  a15=(a15+a23);
  a10=(a10*a15);
  a09=(a09+a10);
  a29=(a29*a52);
  a05=(a05*a06);
  a21=(a21*a41);
  a05=(a05-a21);
  a04=(a04*a08);
  a19=(a19*a50);
  a04=(a04+a19);
  a19=(a05-a04);
  a50=(a19+a19);
  a11=(a11*a50);
  a29=(a29+a11);
  a31=(a31*a17);
  a48=(a22*a48);
  a31=(a31-a48);
  a29=(a29+a31);
  a07=(a07*a17);
  a07=(a07-a48);
  a53=(a53-a04);
  a53=(a53+a05);
  a53=(a53+a53);
  a26=(a26*a53);
  a05=(a00*a52);
  a26=(a26+a05);
  a07=(a07+a26);
  a29=(a29-a07);
  a29=(a02*a29);
  a01=(a01*a29);
  a30=(a30*a54);
  a01=(a01+a30);
  a28=(a28*a17);
  a22=(a22*a19);
  a28=(a28+a22);
  a20=(a20*a53);
  a00=(a00*a42);
  a20=(a20+a00);
  a28=(a28-a20);
  a02=(a02*a28);
  a33=(a33*a52);
  a02=(a02+a33);
  a01=(a01-a02);
  a25=(a25*a01);
  a47=(a47/a14);
  a37=(a37*a13);
  a47=(a47+a37);
  a47=(a32*a47);
  a25=(a25-a47);
  a09=(a09+a25);
  a46=(a46+a09);
  if (res[2]!=0) res[2][6]=a46;
  a24=(a24*a15);
  a16=(a16/a14);
  a40=(a40*a13);
  a16=(a16+a40);
  a18=(a18*a16);
  a24=(a24-a18);
  a03=(a03*a01);
  a44=(a44*a13);
  a32=(a32*a44);
  a03=(a03-a32);
  a24=(a24+a03);
  a39=(a39+a24);
  a39=(-a39);
  if (res[2]!=0) res[2][7]=a39;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_simplified_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_simplified_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real model_simplified_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
