/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) simplified_inverted_pendulum_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};

/* simplified_inverted_pendulum_expl_ode_fun:(i0[4],i1[2],i2[])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=1.0500000000000000e+01;
  a03=8.7500000000000000e-01;
  a04=arg[0]? arg[0][1] : 0;
  a05=cos(a04);
  a06=(a03*a05);
  a07=-2.3199999999999998e-02;
  a04=sin(a04);
  a08=(a07*a04);
  a08=(a06-a08);
  a09=(a08+a08);
  a10=(a08*a09);
  a11=2.3199999999999998e-02;
  a12=(a11*a05);
  a13=(a03*a04);
  a12=(a12-a13);
  a14=(a12+a12);
  a14=(a12*a14);
  a10=(a10+a14);
  a10=(a02*a10);
  a14=8.4100000000000001e+00;
  a10=(a10+a14);
  a14=27.;
  a15=(a14*a10);
  a09=(a02*a09);
  a16=2.;
  a16=(a16*a08);
  a16=(a02*a16);
  a17=(a09*a16);
  a15=(a15-a17);
  a10=(a10/a15);
  a17=arg[1]? arg[1][0] : 0;
  a18=arg[1]? arg[1][1] : 0;
  a17=(a17+a18);
  a18=2.0000000000000001e-01;
  a17=(a17/a18);
  a18=(a07*a01);
  a19=(a18*a05);
  a03=(a03*a01);
  a20=(a03*a04);
  a19=(a19+a20);
  a21=(a19+a19);
  a22=(a02*a21);
  a22=(a22*a01);
  a17=(a17+a22);
  a10=(a10*a17);
  a09=(a09/a15);
  a18=(a18*a04);
  a00=(a00-a18);
  a03=(a03*a05);
  a00=(a00+a03);
  a00=(a00+a00);
  a19=(a00*a19);
  a18=(a11*a01);
  a22=(a18*a05);
  a22=(a22-a20);
  a22=(a22+a22);
  a18=(a18*a04);
  a18=(a18+a03);
  a03=(a22*a18);
  a19=(a19+a03);
  a19=(a02*a19);
  a03=2.0601000000000002e+02;
  a03=(a03*a12);
  a19=(a19+a03);
  a08=(a08*a21);
  a07=(a07*a05);
  a13=(a13+a07);
  a00=(a00*a13);
  a08=(a08+a00);
  a18=(a18+a18);
  a12=(a12*a18);
  a11=(a11*a04);
  a11=(a11+a06);
  a22=(a22*a11);
  a12=(a12+a22);
  a08=(a08+a12);
  a02=(a02*a08);
  a02=(a02*a01);
  a19=(a19-a02);
  a09=(a09*a19);
  a10=(a10+a09);
  if (res[0]!=0) res[0][2]=a10;
  a16=(a16/a15);
  a16=(a16*a17);
  a14=(a14/a15);
  a14=(a14*a19);
  a16=(a16+a14);
  a16=(-a16);
  if (res[0]!=0) res[0][3]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int simplified_inverted_pendulum_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int simplified_inverted_pendulum_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real simplified_inverted_pendulum_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simplified_inverted_pendulum_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simplified_inverted_pendulum_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simplified_inverted_pendulum_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simplified_inverted_pendulum_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
