/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_simplified_gnsf_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};

/* model_simplified_gnsf_phi_fun:(i0[3],i1[2],i2[4])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21;
  a00=5.0000000000000000e-01;
  a01=21.;
  a02=arg[2]? arg[2][0] : 0;
  a01=(a01+a02);
  a00=(a00*a01);
  a02=arg[0]? arg[0][0] : 0;
  a03=cos(a02);
  a04=arg[2]? arg[2][3] : 0;
  a05=(a03*a04);
  a02=sin(a02);
  a06=arg[2]? arg[2][2] : 0;
  a07=(a02*a06);
  a05=(a05-a07);
  a07=(a05+a05);
  a08=(a05*a07);
  a09=(a03*a06);
  a10=(a02*a04);
  a09=(a09+a10);
  a10=(a09+a09);
  a10=(a09*a10);
  a08=(a08+a10);
  a08=(a00*a08);
  a10=arg[2]? arg[2][1] : 0;
  a08=(a08+a10);
  a10=6.;
  a10=(a10+a01);
  a11=(a10*a08);
  a07=(a00*a07);
  a12=2.;
  a12=(a12*a05);
  a12=(a00*a12);
  a13=(a07*a12);
  a11=(a11-a13);
  a08=(a08/a11);
  a13=arg[1]? arg[1][0] : 0;
  a14=arg[1]? arg[1][1] : 0;
  a13=(a13+a14);
  a14=2.0000000000000001e-01;
  a13=(a13/a14);
  a14=arg[0]? arg[0][2] : 0;
  a15=(a06*a14);
  a16=(a15*a03);
  a17=(a04*a14);
  a18=(a17*a02);
  a16=(a16+a18);
  a18=(a16+a16);
  a19=(a00*a18);
  a19=(a19*a14);
  a13=(a13+a19);
  a08=(a08*a13);
  a07=(a07/a11);
  a17=(a17*a03);
  a15=(a15*a02);
  a19=(a17-a15);
  a20=(a19+a19);
  a09=(a09*a20);
  a20=(a04*a03);
  a21=(a06*a02);
  a20=(a20-a21);
  a20=(a18*a20);
  a09=(a09+a20);
  a05=(a05*a18);
  a20=arg[0]? arg[0][1] : 0;
  a20=(a20-a15);
  a20=(a20+a17);
  a20=(a20+a20);
  a04=(a04*a02);
  a06=(a06*a03);
  a04=(a04+a06);
  a06=(a20*a04);
  a05=(a05+a06);
  a09=(a09-a05);
  a09=(a00*a09);
  a09=(a09*a14);
  a18=(a18*a19);
  a20=(a20*a16);
  a18=(a18-a20);
  a00=(a00*a18);
  a18=9.8100000000000005e+00;
  a18=(a18*a01);
  a18=(a18*a04);
  a00=(a00+a18);
  a09=(a09-a00);
  a07=(a07*a09);
  a08=(a08+a07);
  if (res[0]!=0) res[0][0]=a08;
  a12=(a12/a11);
  a12=(a12*a13);
  a10=(a10/a11);
  a10=(a10*a09);
  a12=(a12+a10);
  a12=(-a12);
  if (res[0]!=0) res[0][1]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_gnsf_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_gnsf_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real model_simplified_gnsf_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_gnsf_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_gnsf_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_gnsf_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_gnsf_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
