/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_simplified_gnsf_phi_jac_y_uhat_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {2, 3, 1};
static const casadi_int casadi_s4[3] = {2, 2, 1};

/* model_simplified_gnsf_phi_jac_y_uhat:(i0[3],i1[2],i2[4])->(o0[2x3],o1[2x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[1]? arg[1][1] : 0;
  a00=(a00+a01);
  a01=2.0000000000000001e-01;
  a00=(a00/a01);
  a01=5.0000000000000000e-01;
  a02=21.;
  a03=arg[2]? arg[2][0] : 0;
  a02=(a02+a03);
  a01=(a01*a02);
  a03=arg[2]? arg[2][2] : 0;
  a04=arg[0]? arg[0][2] : 0;
  a05=(a03*a04);
  a06=arg[0]? arg[0][0] : 0;
  a07=cos(a06);
  a08=(a05*a07);
  a09=arg[2]? arg[2][3] : 0;
  a10=(a09*a04);
  a06=sin(a06);
  a11=(a10*a06);
  a12=(a08+a11);
  a13=(a12+a12);
  a14=(a01*a13);
  a15=(a14*a04);
  a00=(a00+a15);
  a15=(a07*a03);
  a16=(a06*a09);
  a15=(a15+a16);
  a16=(a15+a15);
  a17=(a09*a07);
  a18=(a03*a06);
  a17=(a17-a18);
  a18=(a16*a17);
  a19=(a17+a17);
  a19=(a15*a19);
  a18=(a18+a19);
  a19=(a07*a09);
  a20=(a06*a03);
  a19=(a19-a20);
  a20=(a19+a19);
  a09=(a09*a06);
  a03=(a03*a07);
  a09=(a09+a03);
  a03=(a20*a09);
  a21=(a09+a09);
  a22=(a19*a21);
  a03=(a03+a22);
  a18=(a18-a03);
  a18=(a01*a18);
  a03=6.;
  a03=(a03+a02);
  a22=(a19*a20);
  a23=(a15*a16);
  a22=(a22+a23);
  a22=(a01*a22);
  a23=arg[2]? arg[2][1] : 0;
  a22=(a22+a23);
  a23=(a03*a22);
  a24=(a01*a20);
  a25=2.;
  a26=(a25*a19);
  a26=(a01*a26);
  a27=(a24*a26);
  a23=(a23-a27);
  a27=(a18/a23);
  a22=(a22/a23);
  a28=(a22/a23);
  a18=(a03*a18);
  a21=(a01*a21);
  a29=(a26*a21);
  a30=(a25*a09);
  a30=(a01*a30);
  a31=(a24*a30);
  a29=(a29+a31);
  a18=(a18+a29);
  a28=(a28*a18);
  a27=(a27-a28);
  a27=(a00*a27);
  a10=(a10*a07);
  a05=(a05*a06);
  a06=(a10-a05);
  a07=(a06+a06);
  a28=(a01*a07);
  a28=(a04*a28);
  a29=(a22*a28);
  a27=(a27+a29);
  a24=(a24/a23);
  a29=(a07*a17);
  a11=(a11+a08);
  a08=(a11+a11);
  a08=(a15*a08);
  a29=(a29-a08);
  a08=(a17*a07);
  a31=(a13*a09);
  a08=(a08-a31);
  a29=(a29+a08);
  a08=(a19*a07);
  a08=(a08-a31);
  a31=arg[0]? arg[0][1] : 0;
  a31=(a31-a05);
  a31=(a31+a10);
  a31=(a31+a31);
  a10=(a31*a17);
  a05=(a09*a13);
  a10=(a10-a05);
  a08=(a08+a10);
  a29=(a29-a08);
  a29=(a01*a29);
  a29=(a04*a29);
  a08=(a06*a07);
  a11=(a13*a11);
  a08=(a08-a11);
  a11=(a31*a06);
  a10=(a12*a13);
  a11=(a11-a10);
  a08=(a08-a11);
  a08=(a01*a08);
  a11=9.8100000000000005e+00;
  a11=(a11*a02);
  a02=(a11*a17);
  a08=(a08+a02);
  a29=(a29-a08);
  a08=(a24*a29);
  a07=(a15*a07);
  a02=(a13*a17);
  a07=(a07+a02);
  a02=(a19*a13);
  a10=(a31*a09);
  a02=(a02+a10);
  a07=(a07-a02);
  a07=(a01*a07);
  a02=(a07*a04);
  a10=(a13*a06);
  a05=(a31*a12);
  a10=(a10-a05);
  a10=(a01*a10);
  a11=(a11*a09);
  a10=(a10+a11);
  a02=(a02-a10);
  a21=(a21/a23);
  a10=(a24/a23);
  a10=(a10*a18);
  a21=(a21+a10);
  a21=(a02*a21);
  a08=(a08-a21);
  a27=(a27+a08);
  if (res[0]!=0) res[0][0]=a27;
  a26=(a26/a23);
  a28=(a26*a28);
  a27=(a30/a23);
  a08=(a26/a23);
  a08=(a08*a18);
  a27=(a27+a08);
  a00=(a00*a27);
  a28=(a28-a00);
  a03=(a03/a23);
  a29=(a03*a29);
  a23=(a03/a23);
  a23=(a23*a18);
  a02=(a02*a23);
  a29=(a29-a02);
  a28=(a28+a29);
  a28=(-a28);
  if (res[0]!=0) res[0][1]=a28;
  a25=(a25*a12);
  a25=(a01*a25);
  a30=(a04*a30);
  a25=(a25-a30);
  a30=(a24*a25);
  if (res[0]!=0) res[0][2]=a30;
  a25=(a03*a25);
  a25=(-a25);
  if (res[0]!=0) res[0][3]=a25;
  a25=(a01*a16);
  a25=(a04*a25);
  a25=(a25+a14);
  a14=(a22*a25);
  a30=(a15*a20);
  a17=(a17*a16);
  a30=(a30+a17);
  a17=(a19*a16);
  a09=(a09*a20);
  a17=(a17+a09);
  a30=(a30-a17);
  a30=(a01*a30);
  a04=(a04*a30);
  a04=(a04+a07);
  a06=(a06*a16);
  a13=(a13*a19);
  a06=(a06+a13);
  a12=(a12*a20);
  a31=(a31*a15);
  a12=(a12+a31);
  a06=(a06-a12);
  a01=(a01*a06);
  a04=(a04-a01);
  a24=(a24*a04);
  a14=(a14+a24);
  if (res[0]!=0) res[0][4]=a14;
  a25=(a26*a25);
  a03=(a03*a04);
  a25=(a25+a03);
  a25=(-a25);
  if (res[0]!=0) res[0][5]=a25;
  a25=5.;
  a22=(a25*a22);
  if (res[1]!=0) res[1][0]=a22;
  a25=(a25*a26);
  a25=(-a25);
  if (res[1]!=0) res[1][1]=a25;
  if (res[1]!=0) res[1][2]=a22;
  if (res[1]!=0) res[1][3]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_jac_y_uhat(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_jac_y_uhat_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_jac_y_uhat_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_jac_y_uhat_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_jac_y_uhat_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_jac_y_uhat_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_jac_y_uhat_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_jac_y_uhat_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_gnsf_phi_jac_y_uhat_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_gnsf_phi_jac_y_uhat_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real model_simplified_gnsf_phi_jac_y_uhat_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_gnsf_phi_jac_y_uhat_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_gnsf_phi_jac_y_uhat_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_gnsf_phi_jac_y_uhat_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_gnsf_phi_jac_y_uhat_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_jac_y_uhat_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_jac_y_uhat_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
