/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_simplified_gnsf_phi_fun_jac_y_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {2, 3, 1};

/* model_simplified_gnsf_phi_fun_jac_y:(i0[3],i1[2],i2[4])->(o0[2],o1[2x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=5.0000000000000000e-01;
  a01=21.;
  a02=arg[2]? arg[2][0] : 0;
  a01=(a01+a02);
  a00=(a00*a01);
  a02=arg[0]? arg[0][0] : 0;
  a03=cos(a02);
  a04=arg[2]? arg[2][3] : 0;
  a05=(a03*a04);
  a02=sin(a02);
  a06=arg[2]? arg[2][2] : 0;
  a07=(a02*a06);
  a05=(a05-a07);
  a07=(a05+a05);
  a08=(a05*a07);
  a09=(a03*a06);
  a10=(a02*a04);
  a09=(a09+a10);
  a10=(a09+a09);
  a11=(a09*a10);
  a08=(a08+a11);
  a08=(a00*a08);
  a11=arg[2]? arg[2][1] : 0;
  a08=(a08+a11);
  a11=6.;
  a11=(a11+a01);
  a12=(a11*a08);
  a13=(a00*a07);
  a14=2.;
  a15=(a14*a05);
  a15=(a00*a15);
  a16=(a13*a15);
  a12=(a12-a16);
  a08=(a08/a12);
  a16=arg[1]? arg[1][0] : 0;
  a17=arg[1]? arg[1][1] : 0;
  a16=(a16+a17);
  a17=2.0000000000000001e-01;
  a16=(a16/a17);
  a17=arg[0]? arg[0][2] : 0;
  a18=(a06*a17);
  a19=(a18*a03);
  a20=(a04*a17);
  a21=(a20*a02);
  a22=(a19+a21);
  a23=(a22+a22);
  a24=(a00*a23);
  a25=(a24*a17);
  a16=(a16+a25);
  a25=(a08*a16);
  a26=(a13/a12);
  a20=(a20*a03);
  a18=(a18*a02);
  a27=(a20-a18);
  a28=(a27+a27);
  a29=(a09*a28);
  a30=(a04*a03);
  a31=(a06*a02);
  a30=(a30-a31);
  a31=(a23*a30);
  a29=(a29+a31);
  a31=(a05*a23);
  a32=arg[0]? arg[0][1] : 0;
  a32=(a32-a18);
  a32=(a32+a20);
  a32=(a32+a32);
  a04=(a04*a02);
  a06=(a06*a03);
  a04=(a04+a06);
  a06=(a32*a04);
  a31=(a31+a06);
  a29=(a29-a31);
  a29=(a00*a29);
  a31=(a29*a17);
  a06=(a23*a27);
  a03=(a32*a22);
  a06=(a06-a03);
  a06=(a00*a06);
  a03=9.8100000000000005e+00;
  a03=(a03*a01);
  a01=(a03*a04);
  a06=(a06+a01);
  a31=(a31-a06);
  a06=(a26*a31);
  a25=(a25+a06);
  if (res[0]!=0) res[0][0]=a25;
  a25=(a15/a12);
  a06=(a25*a16);
  a01=(a11/a12);
  a02=(a01*a31);
  a06=(a06+a02);
  a06=(-a06);
  if (res[0]!=0) res[0][1]=a06;
  a06=(a10*a30);
  a02=(a30+a30);
  a02=(a09*a02);
  a06=(a06+a02);
  a02=(a07*a04);
  a20=(a04+a04);
  a18=(a05*a20);
  a02=(a02+a18);
  a06=(a06-a02);
  a06=(a00*a06);
  a02=(a06/a12);
  a18=(a08/a12);
  a11=(a11*a06);
  a20=(a00*a20);
  a15=(a15*a20);
  a06=(a14*a04);
  a06=(a00*a06);
  a13=(a13*a06);
  a15=(a15+a13);
  a11=(a11+a15);
  a18=(a18*a11);
  a02=(a02-a18);
  a02=(a16*a02);
  a18=(a00*a28);
  a18=(a17*a18);
  a15=(a08*a18);
  a02=(a02+a15);
  a15=(a28*a30);
  a21=(a21+a19);
  a19=(a21+a21);
  a19=(a09*a19);
  a15=(a15-a19);
  a19=(a30*a28);
  a13=(a23*a04);
  a19=(a19-a13);
  a15=(a15+a19);
  a19=(a05*a28);
  a19=(a19-a13);
  a13=(a32*a30);
  a33=(a04*a23);
  a13=(a13-a33);
  a19=(a19+a13);
  a15=(a15-a19);
  a15=(a00*a15);
  a15=(a17*a15);
  a28=(a27*a28);
  a21=(a23*a21);
  a28=(a28-a21);
  a21=(a32*a27);
  a19=(a22*a23);
  a21=(a21-a19);
  a28=(a28-a21);
  a28=(a00*a28);
  a03=(a03*a30);
  a28=(a28+a03);
  a15=(a15-a28);
  a28=(a26*a15);
  a20=(a20/a12);
  a03=(a26/a12);
  a03=(a03*a11);
  a20=(a20+a03);
  a20=(a31*a20);
  a28=(a28-a20);
  a02=(a02+a28);
  if (res[1]!=0) res[1][0]=a02;
  a18=(a25*a18);
  a02=(a06/a12);
  a28=(a25/a12);
  a28=(a28*a11);
  a02=(a02+a28);
  a16=(a16*a02);
  a18=(a18-a16);
  a15=(a01*a15);
  a12=(a01/a12);
  a12=(a12*a11);
  a31=(a31*a12);
  a15=(a15-a31);
  a18=(a18+a15);
  a18=(-a18);
  if (res[1]!=0) res[1][1]=a18;
  a14=(a14*a22);
  a14=(a00*a14);
  a06=(a17*a06);
  a14=(a14-a06);
  a06=(a26*a14);
  if (res[1]!=0) res[1][2]=a06;
  a14=(a01*a14);
  a14=(-a14);
  if (res[1]!=0) res[1][3]=a14;
  a14=(a00*a10);
  a14=(a17*a14);
  a14=(a14+a24);
  a08=(a08*a14);
  a24=(a09*a07);
  a30=(a30*a10);
  a24=(a24+a30);
  a30=(a05*a10);
  a04=(a04*a07);
  a30=(a30+a04);
  a24=(a24-a30);
  a24=(a00*a24);
  a17=(a17*a24);
  a17=(a17+a29);
  a27=(a27*a10);
  a23=(a23*a05);
  a27=(a27+a23);
  a22=(a22*a07);
  a32=(a32*a09);
  a22=(a22+a32);
  a27=(a27-a22);
  a00=(a00*a27);
  a17=(a17-a00);
  a26=(a26*a17);
  a08=(a08+a26);
  if (res[1]!=0) res[1][4]=a08;
  a25=(a25*a14);
  a01=(a01*a17);
  a25=(a25+a01);
  a25=(-a25);
  if (res[1]!=0) res[1][5]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_jac_y(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_jac_y_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_jac_y_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_fun_jac_y_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_jac_y_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_fun_jac_y_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_fun_jac_y_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_simplified_gnsf_phi_fun_jac_y_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_gnsf_phi_fun_jac_y_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_gnsf_phi_fun_jac_y_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real model_simplified_gnsf_phi_fun_jac_y_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_gnsf_phi_fun_jac_y_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_gnsf_phi_fun_jac_y_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_gnsf_phi_fun_jac_y_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_gnsf_phi_fun_jac_y_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_jac_y_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_gnsf_phi_fun_jac_y_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
