/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) diff_robot_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {4, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};

/* diff_robot_model_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[])->(o0[4],o1[4x4],o2[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=7.8480000000000004e+01;
  a02=arg[0]? arg[0][0] : 0;
  a03=sin(a02);
  a04=(a01*a03);
  a05=8.;
  a06=arg[3]? arg[3][0] : 0;
  a07=arg[3]? arg[3][1] : 0;
  a08=(a06+a07);
  a09=2.0000000000000001e-01;
  a08=(a08/a09);
  a09=casadi_sq(a00);
  a09=(a05*a09);
  a10=(a09*a03);
  a08=(a08-a10);
  a10=1.5696000000000001e+02;
  a11=(a10*a03);
  a02=cos(a02);
  a12=(a11*a02);
  a08=(a08-a12);
  a12=19.;
  a08=(a08/a12);
  a12=(a05*a08);
  a13=(a12*a02);
  a04=(a04-a13);
  a13=5.0000000000000000e-01;
  a14=arg[0]? arg[0][3] : 0;
  a15=casadi_sq(a14);
  a15=(a05*a15);
  a15=(a13*a15);
  a16=(a15*a03);
  a17=(a16*a02);
  a04=(a04-a17);
  a17=6.1866666666666665e+00;
  a04=(a04/a17);
  if (res[0]!=0) res[0][1]=a04;
  if (res[0]!=0) res[0][2]=a08;
  a08=1.4999999999999998e+00;
  a07=(a07-a06);
  a07=(a08*a07);
  a06=(a05*a00);
  a04=(a06*a14);
  a17=(a04*a03);
  a18=(a17*a02);
  a07=(a07-a18);
  a18=4.;
  a19=casadi_sq(a03);
  a19=(a18*a19);
  a20=1.0666666666666669e+00;
  a19=(a19+a20);
  a20=8.9999999999999997e-02;
  a19=(a19+a20);
  a07=(a07/a19);
  if (res[0]!=0) res[0][3]=a07;
  a20=arg[1]? arg[1][1] : 0;
  if (res[1]!=0) res[1][0]=a20;
  a21=1.6163793103448276e-01;
  a22=arg[1]? arg[1][0] : 0;
  a23=(a02*a22);
  a24=(a01*a23);
  a25=5.2631578947368418e-02;
  a00=(a00+a00);
  a26=(a00*a20);
  a26=(a05*a26);
  a26=(a03*a26);
  a27=(a09*a23);
  a26=(a26+a27);
  a27=(a10*a23);
  a27=(a02*a27);
  a22=(a03*a22);
  a28=(a11*a22);
  a27=(a27-a28);
  a26=(a26+a27);
  a26=(a25*a26);
  a27=(a05*a26);
  a27=(a02*a27);
  a28=(a12*a22);
  a27=(a27+a28);
  a24=(a24+a27);
  a27=(a14+a14);
  a28=arg[1]? arg[1][3] : 0;
  a29=(a27*a28);
  a29=(a05*a29);
  a29=(a13*a29);
  a29=(a03*a29);
  a30=(a15*a23);
  a29=(a29+a30);
  a29=(a02*a29);
  a30=(a16*a22);
  a29=(a29-a30);
  a24=(a24-a29);
  a24=(a21*a24);
  if (res[1]!=0) res[1][1]=a24;
  a26=(-a26);
  if (res[1]!=0) res[1][2]=a26;
  a20=(a05*a20);
  a20=(a14*a20);
  a28=(a06*a28);
  a20=(a20+a28);
  a20=(a03*a20);
  a28=(a04*a23);
  a20=(a20+a28);
  a20=(a02*a20);
  a22=(a17*a22);
  a20=(a20-a22);
  a20=(a20/a19);
  a07=(a07/a19);
  a22=(a03+a03);
  a23=(a22*a23);
  a23=(a18*a23);
  a23=(a07*a23);
  a20=(a20+a23);
  a20=(-a20);
  if (res[1]!=0) res[1][3]=a20;
  a20=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][4]=a20;
  a23=arg[1]? arg[1][4] : 0;
  a28=(a02*a23);
  a26=(a01*a28);
  a24=(a00*a20);
  a24=(a05*a24);
  a24=(a03*a24);
  a29=(a09*a28);
  a24=(a24+a29);
  a29=(a10*a28);
  a29=(a02*a29);
  a23=(a03*a23);
  a30=(a11*a23);
  a29=(a29-a30);
  a24=(a24+a29);
  a24=(a25*a24);
  a29=(a05*a24);
  a29=(a02*a29);
  a30=(a12*a23);
  a29=(a29+a30);
  a26=(a26+a29);
  a29=arg[1]? arg[1][7] : 0;
  a30=(a27*a29);
  a30=(a05*a30);
  a30=(a13*a30);
  a30=(a03*a30);
  a31=(a15*a28);
  a30=(a30+a31);
  a30=(a02*a30);
  a31=(a16*a23);
  a30=(a30-a31);
  a26=(a26-a30);
  a26=(a21*a26);
  if (res[1]!=0) res[1][5]=a26;
  a24=(-a24);
  if (res[1]!=0) res[1][6]=a24;
  a20=(a05*a20);
  a20=(a14*a20);
  a29=(a06*a29);
  a20=(a20+a29);
  a20=(a03*a20);
  a29=(a04*a28);
  a20=(a20+a29);
  a20=(a02*a20);
  a23=(a17*a23);
  a20=(a20-a23);
  a20=(a20/a19);
  a28=(a22*a28);
  a28=(a18*a28);
  a28=(a07*a28);
  a20=(a20+a28);
  a20=(-a20);
  if (res[1]!=0) res[1][7]=a20;
  a20=arg[1]? arg[1][9] : 0;
  if (res[1]!=0) res[1][8]=a20;
  a28=arg[1]? arg[1][8] : 0;
  a23=(a02*a28);
  a29=(a01*a23);
  a24=(a00*a20);
  a24=(a05*a24);
  a24=(a03*a24);
  a26=(a09*a23);
  a24=(a24+a26);
  a26=(a10*a23);
  a26=(a02*a26);
  a28=(a03*a28);
  a30=(a11*a28);
  a26=(a26-a30);
  a24=(a24+a26);
  a24=(a25*a24);
  a26=(a05*a24);
  a26=(a02*a26);
  a30=(a12*a28);
  a26=(a26+a30);
  a29=(a29+a26);
  a26=arg[1]? arg[1][11] : 0;
  a30=(a27*a26);
  a30=(a05*a30);
  a30=(a13*a30);
  a30=(a03*a30);
  a31=(a15*a23);
  a30=(a30+a31);
  a30=(a02*a30);
  a31=(a16*a28);
  a30=(a30-a31);
  a29=(a29-a30);
  a29=(a21*a29);
  if (res[1]!=0) res[1][9]=a29;
  a24=(-a24);
  if (res[1]!=0) res[1][10]=a24;
  a20=(a05*a20);
  a20=(a14*a20);
  a26=(a06*a26);
  a20=(a20+a26);
  a20=(a03*a20);
  a26=(a04*a23);
  a20=(a20+a26);
  a20=(a02*a20);
  a28=(a17*a28);
  a20=(a20-a28);
  a20=(a20/a19);
  a23=(a22*a23);
  a23=(a18*a23);
  a23=(a07*a23);
  a20=(a20+a23);
  a20=(-a20);
  if (res[1]!=0) res[1][11]=a20;
  a20=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][12]=a20;
  a23=arg[1]? arg[1][12] : 0;
  a28=(a02*a23);
  a26=(a01*a28);
  a24=(a00*a20);
  a24=(a05*a24);
  a24=(a03*a24);
  a29=(a09*a28);
  a24=(a24+a29);
  a29=(a10*a28);
  a29=(a02*a29);
  a23=(a03*a23);
  a30=(a11*a23);
  a29=(a29-a30);
  a24=(a24+a29);
  a24=(a25*a24);
  a29=(a05*a24);
  a29=(a02*a29);
  a30=(a12*a23);
  a29=(a29+a30);
  a26=(a26+a29);
  a29=arg[1]? arg[1][15] : 0;
  a30=(a27*a29);
  a30=(a05*a30);
  a30=(a13*a30);
  a30=(a03*a30);
  a31=(a15*a28);
  a30=(a30+a31);
  a30=(a02*a30);
  a31=(a16*a23);
  a30=(a30-a31);
  a26=(a26-a30);
  a26=(a21*a26);
  if (res[1]!=0) res[1][13]=a26;
  a24=(-a24);
  if (res[1]!=0) res[1][14]=a24;
  a20=(a05*a20);
  a20=(a14*a20);
  a29=(a06*a29);
  a20=(a20+a29);
  a20=(a03*a20);
  a29=(a04*a28);
  a20=(a20+a29);
  a20=(a02*a20);
  a23=(a17*a23);
  a20=(a20-a23);
  a20=(a20/a19);
  a28=(a22*a28);
  a28=(a18*a28);
  a28=(a07*a28);
  a20=(a20+a28);
  a20=(-a20);
  if (res[1]!=0) res[1][15]=a20;
  a20=arg[2]? arg[2][1] : 0;
  if (res[2]!=0) res[2][0]=a20;
  a28=arg[2]? arg[2][0] : 0;
  a23=(a02*a28);
  a29=(a01*a23);
  a24=(a00*a20);
  a24=(a05*a24);
  a24=(a03*a24);
  a26=(a09*a23);
  a24=(a24+a26);
  a26=(a10*a23);
  a26=(a02*a26);
  a28=(a03*a28);
  a30=(a11*a28);
  a26=(a26-a30);
  a24=(a24+a26);
  a24=(a25*a24);
  a26=(a05*a24);
  a26=(a02*a26);
  a30=(a12*a28);
  a26=(a26+a30);
  a29=(a29+a26);
  a26=arg[2]? arg[2][3] : 0;
  a30=(a27*a26);
  a30=(a05*a30);
  a30=(a13*a30);
  a30=(a03*a30);
  a31=(a15*a23);
  a30=(a30+a31);
  a30=(a02*a30);
  a31=(a16*a28);
  a30=(a30-a31);
  a29=(a29-a30);
  a29=(a21*a29);
  a30=2.1052631578947367e+00;
  a30=(a30*a02);
  a30=(a21*a30);
  a29=(a29-a30);
  if (res[2]!=0) res[2][1]=a29;
  a29=2.6315789473684209e-01;
  a24=(a29-a24);
  if (res[2]!=0) res[2][2]=a24;
  a24=-1.4999999999999998e+00;
  a24=(a24/a19);
  a20=(a05*a20);
  a20=(a14*a20);
  a26=(a06*a26);
  a20=(a20+a26);
  a20=(a03*a20);
  a26=(a04*a23);
  a20=(a20+a26);
  a20=(a02*a20);
  a28=(a17*a28);
  a20=(a20-a28);
  a20=(a20/a19);
  a23=(a22*a23);
  a23=(a18*a23);
  a23=(a07*a23);
  a20=(a20+a23);
  a24=(a24-a20);
  if (res[2]!=0) res[2][3]=a24;
  a24=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][4]=a24;
  a20=arg[2]? arg[2][4] : 0;
  a23=(a02*a20);
  a01=(a01*a23);
  a00=(a00*a24);
  a00=(a05*a00);
  a00=(a03*a00);
  a09=(a09*a23);
  a00=(a00+a09);
  a10=(a10*a23);
  a10=(a02*a10);
  a20=(a03*a20);
  a11=(a11*a20);
  a10=(a10-a11);
  a00=(a00+a10);
  a25=(a25*a00);
  a00=(a05*a25);
  a00=(a02*a00);
  a12=(a12*a20);
  a00=(a00+a12);
  a01=(a01+a00);
  a00=arg[2]? arg[2][7] : 0;
  a27=(a27*a00);
  a27=(a05*a27);
  a13=(a13*a27);
  a13=(a03*a13);
  a15=(a15*a23);
  a13=(a13+a15);
  a13=(a02*a13);
  a16=(a16*a20);
  a13=(a13-a16);
  a01=(a01-a13);
  a21=(a21*a01);
  a21=(a21-a30);
  if (res[2]!=0) res[2][5]=a21;
  a29=(a29-a25);
  if (res[2]!=0) res[2][6]=a29;
  a08=(a08/a19);
  a05=(a05*a24);
  a14=(a14*a05);
  a06=(a06*a00);
  a14=(a14+a06);
  a03=(a03*a14);
  a04=(a04*a23);
  a03=(a03+a04);
  a02=(a02*a03);
  a17=(a17*a20);
  a02=(a02-a17);
  a02=(a02/a19);
  a22=(a22*a23);
  a18=(a18*a22);
  a07=(a07*a18);
  a02=(a02+a07);
  a08=(a08-a02);
  if (res[2]!=0) res[2][7]=a08;
  return 0;
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diff_robot_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diff_robot_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void diff_robot_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void diff_robot_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int diff_robot_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int diff_robot_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real diff_robot_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diff_robot_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diff_robot_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diff_robot_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diff_robot_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
