/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) diff_robot_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {6, 1, 1};

/* diff_robot_model_expl_vde_adj:(i0[4],i1[4],i2[2],i3[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24;
  a00=arg[0]? arg[0][0] : 0;
  a01=sin(a00);
  a02=8.;
  a03=arg[0]? arg[0][1] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][3] : 0;
  a06=(a04*a05);
  a07=(a06*a01);
  a08=arg[1]? arg[1][3] : 0;
  a09=4.;
  a10=casadi_sq(a01);
  a10=(a09*a10);
  a11=1.0666666666666669e+00;
  a10=(a10+a11);
  a11=8.9999999999999997e-02;
  a10=(a10+a11);
  a11=(a08/a10);
  a12=(a07*a11);
  a13=5.0000000000000000e-01;
  a14=casadi_sq(a05);
  a14=(a02*a14);
  a14=(a13*a14);
  a15=(a14*a01);
  a16=1.6163793103448276e-01;
  a17=arg[1]? arg[1][1] : 0;
  a16=(a16*a17);
  a15=(a15*a16);
  a12=(a12+a15);
  a15=arg[2]? arg[2][0] : 0;
  a17=arg[2]? arg[2][1] : 0;
  a18=(a15+a17);
  a19=2.0000000000000001e-01;
  a18=(a18/a19);
  a19=casadi_sq(a03);
  a19=(a02*a19);
  a20=(a19*a01);
  a18=(a18-a20);
  a20=1.5696000000000001e+02;
  a21=(a20*a01);
  a00=cos(a00);
  a22=(a21*a00);
  a18=(a18-a22);
  a22=19.;
  a18=(a18/a22);
  a18=(a02*a18);
  a18=(a18*a16);
  a12=(a12+a18);
  a18=5.2631578947368418e-02;
  a22=arg[1]? arg[1][2] : 0;
  a23=(a00*a16);
  a24=(a02*a23);
  a22=(a22-a24);
  a18=(a18*a22);
  a21=(a21*a18);
  a12=(a12+a21);
  a12=(a01*a12);
  a21=(a01+a01);
  a22=1.4999999999999998e+00;
  a17=(a17-a15);
  a17=(a22*a17);
  a07=(a07*a00);
  a17=(a17-a07);
  a17=(a17/a10);
  a17=(a17/a10);
  a17=(a17*a08);
  a09=(a09*a17);
  a21=(a21*a09);
  a21=(a00*a21);
  a12=(a12-a21);
  a21=7.8480000000000004e+01;
  a21=(a21*a16);
  a16=(a00*a11);
  a06=(a06*a16);
  a14=(a14*a23);
  a06=(a06+a14);
  a14=(a00*a18);
  a20=(a20*a14);
  a06=(a06+a20);
  a19=(a19*a18);
  a06=(a06+a19);
  a21=(a21-a06);
  a00=(a00*a21);
  a12=(a12+a00);
  if (res[0]!=0) res[0][0]=a12;
  a12=arg[1]? arg[1][0] : 0;
  a16=(a01*a16);
  a00=(a05*a16);
  a00=(a02*a00);
  a03=(a03+a03);
  a21=(a01*a18);
  a21=(a02*a21);
  a03=(a03*a21);
  a00=(a00+a03);
  a12=(a12-a00);
  if (res[0]!=0) res[0][1]=a12;
  a12=0.;
  if (res[0]!=0) res[0][2]=a12;
  a04=(a04*a16);
  a05=(a05+a05);
  a01=(a01*a23);
  a13=(a13*a01);
  a02=(a02*a13);
  a05=(a05*a02);
  a04=(a04+a05);
  a04=(-a04);
  if (res[0]!=0) res[0][3]=a04;
  a04=5.;
  a04=(a04*a18);
  a22=(a22*a11);
  a11=(a04-a22);
  if (res[0]!=0) res[0][4]=a11;
  a22=(a22+a04);
  if (res[0]!=0) res[0][5]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diff_robot_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diff_robot_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void diff_robot_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void diff_robot_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int diff_robot_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int diff_robot_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real diff_robot_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diff_robot_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diff_robot_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diff_robot_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diff_robot_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int diff_robot_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
