/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cart_brick_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[13] = 
  {4, 4, 0, 0, 2, 3, 6, 2,
  3, 0, 1, 2, 3};
static const casadi_int casadi_s4[11] = 
  {4, 4, 0, 1, 2, 3, 4, 0,
  1, 2, 3};
static const casadi_int casadi_s5[6] = {4, 1, 0, 2, 2, 3};

/* cart_brick_impl_dae_fun_jac_x_xdot_u:(i0[4],i1[4],i2,i3[],i4[])->(o0[4],o1[4x4,6nz],o2[4x4,4nz],o3[4x1,2nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21;
  a00=arg[0]? arg[0][2] : 0;
  a01=arg[1]? arg[1][0] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][3] : 0;
  a01=arg[1]? arg[1][1] : 0;
  a01=(a00-a01);
  if (res[0]!=0) res[0][1]=a01;
  a01=2.0449999999999999e+00;
  a02=arg[2]? arg[2][0] : 0;
  a03=(a01*a02);
  a04=6.1349999999999998e+00;
  a05=arg[0]? arg[0][1] : 0;
  a06=sin(a05);
  a07=(a04*a06);
  a08=casadi_sq(a00);
  a09=(a07*a08);
  a03=(a03+a09);
  a09=8.8290000000000006e+01;
  a10=(a09*a06);
  a05=cos(a05);
  a11=(a10*a05);
  a03=(a03-a11);
  a11=3.2719999999999999e+01;
  a12=3.;
  a13=(a12*a05);
  a14=casadi_sq(a13);
  a11=(a11-a14);
  a03=(a03/a11);
  a14=arg[1]? arg[1][2] : 0;
  a14=(a03-a14);
  if (res[0]!=0) res[0][2]=a14;
  a14=-3.;
  a15=(a14*a05);
  a16=(a15*a02);
  a17=9.;
  a18=(a17*a06);
  a19=(a18*a05);
  a20=(a19*a08);
  a16=(a16-a20);
  a20=4.7088000000000000e+02;
  a21=(a20*a06);
  a16=(a16+a21);
  a16=(a16/a11);
  a21=arg[1]? arg[1][3] : 0;
  a21=(a16-a21);
  if (res[0]!=0) res[0][3]=a21;
  a04=(a04*a05);
  a04=(a08*a04);
  a09=(a09*a05);
  a09=(a05*a09);
  a10=(a10*a06);
  a09=(a09-a10);
  a04=(a04-a09);
  a04=(a04/a11);
  a03=(a03/a11);
  a13=(a13+a13);
  a12=(a12*a06);
  a13=(a13*a12);
  a03=(a03*a13);
  a04=(a04-a03);
  if (res[1]!=0) res[1][0]=a04;
  a20=(a20*a05);
  a14=(a14*a06);
  a02=(a02*a14);
  a17=(a17*a05);
  a05=(a05*a17);
  a18=(a18*a06);
  a05=(a05-a18);
  a08=(a08*a05);
  a02=(a02+a08);
  a20=(a20-a02);
  a20=(a20/a11);
  a16=(a16/a11);
  a16=(a16*a13);
  a20=(a20-a16);
  if (res[1]!=0) res[1][1]=a20;
  a20=1.;
  if (res[1]!=0) res[1][2]=a20;
  if (res[1]!=0) res[1][3]=a20;
  a00=(a00+a00);
  a07=(a07*a00);
  a07=(a07/a11);
  if (res[1]!=0) res[1][4]=a07;
  a19=(a19*a00);
  a19=(a19/a11);
  a19=(-a19);
  if (res[1]!=0) res[1][5]=a19;
  a19=-1.;
  if (res[2]!=0) res[2][0]=a19;
  if (res[2]!=0) res[2][1]=a19;
  if (res[2]!=0) res[2][2]=a19;
  if (res[2]!=0) res[2][3]=a19;
  a01=(a01/a11);
  if (res[3]!=0) res[3][0]=a01;
  a15=(a15/a11);
  if (res[3]!=0) res[3][1]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int cart_brick_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cart_brick_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cart_brick_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cart_brick_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cart_brick_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cart_brick_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cart_brick_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void cart_brick_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cart_brick_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cart_brick_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real cart_brick_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cart_brick_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cart_brick_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cart_brick_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cart_brick_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cart_brick_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cart_brick_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
