/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheeled_robot_fork_1D_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};

/* wheeled_robot_fork_1D_expl_ode_fun:(i0[4],i1,i2)->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a01=2.1866666666666665e+00;
  a02=16.;
  a03=arg[0]? arg[0][0] : 0;
  a04=5.0000000000000000e-01;
  a05=arg[0]? arg[0][1] : 0;
  a06=sin(a05);
  a07=(a04*a06);
  a07=(a03-a07);
  a08=(a02*a07);
  a09=5.;
  a10=-2.0000000000000001e-01;
  a05=cos(a05);
  a11=(a10*a05);
  a11=(a03+a11);
  a11=(a11-a06);
  a12=(a09*a11);
  a08=(a08+a12);
  a12=3.;
  a13=-9.9999999999999992e-02;
  a14=(a13*a05);
  a14=(a03+a14);
  a15=1.5000000000000000e+00;
  a16=arg[2]? arg[2][0] : 0;
  a15=(a15+a16);
  a16=(a15*a06);
  a14=(a14-a16);
  a17=(a12*a14);
  a08=(a08+a17);
  a17=2.5000000000000000e-01;
  a18=(a17*a05);
  a18=(a03+a18);
  a18=(a18-a16);
  a08=(a08+a18);
  a19=-2.5000000000000000e-01;
  a20=(a19*a05);
  a20=(a03+a20);
  a20=(a20-a16);
  a08=(a08+a20);
  a16=2.;
  a21=(a16*a03);
  a08=(a08+a21);
  a21=28.;
  a08=(a08/a21);
  a07=(a07-a08);
  a07=casadi_sq(a07);
  a22=2.0000000000000001e-01;
  a04=(a04*a05);
  a04=(a22+a04);
  a23=(a02*a04);
  a10=(a10*a06);
  a10=(a22+a10);
  a10=(a10+a05);
  a24=(a09*a10);
  a23=(a23+a24);
  a13=(a13*a06);
  a13=(a22+a13);
  a15=(a15*a05);
  a13=(a13+a15);
  a05=(a12*a13);
  a23=(a23+a05);
  a17=(a17*a06);
  a17=(a22+a17);
  a17=(a17+a15);
  a23=(a23+a17);
  a19=(a19*a06);
  a19=(a22+a19);
  a19=(a19+a15);
  a23=(a23+a19);
  a15=4.0000000000000002e-01;
  a23=(a23+a15);
  a23=(a23/a21);
  a04=(a04-a23);
  a04=casadi_sq(a04);
  a07=(a07+a04);
  a02=(a02*a07);
  a01=(a01+a02);
  a02=9.7499999999999987e-01;
  a01=(a01+a02);
  a11=(a11-a08);
  a11=casadi_sq(a11);
  a10=(a10-a23);
  a10=casadi_sq(a10);
  a11=(a11+a10);
  a09=(a09*a11);
  a01=(a01+a09);
  a09=1.6250000000000003e-01;
  a01=(a01+a09);
  a14=(a14-a08);
  a14=casadi_sq(a14);
  a13=(a13-a23);
  a13=casadi_sq(a13);
  a14=(a14+a13);
  a12=(a12*a14);
  a01=(a01+a12);
  a12=3.0833333333333331e-02;
  a01=(a01+a12);
  a18=(a18-a08);
  a18=casadi_sq(a18);
  a17=(a17-a23);
  a17=casadi_sq(a17);
  a18=(a18+a17);
  a01=(a01+a18);
  a01=(a01+a12);
  a20=(a20-a08);
  a20=casadi_sq(a20);
  a19=(a19-a23);
  a19=casadi_sq(a19);
  a20=(a20+a19);
  a01=(a01+a20);
  a20=26.;
  a23=(a23-a22);
  a19=casadi_sq(a23);
  a08=(a08-a03);
  a03=casadi_sq(a08);
  a19=(a19+a03);
  a19=(a20*a19);
  a01=(a01+a19);
  a19=31.;
  a03=(a19*a01);
  a20=(a20*a23);
  a23=casadi_sq(a20);
  a03=(a03-a23);
  a01=(a01/a03);
  a00=casadi_sq(a00);
  a00=(a20*a00);
  a23=arg[1]? arg[1][0] : 0;
  a16=(a16*a23);
  a16=(a16/a22);
  a00=(a00+a16);
  a01=(a01*a00);
  a20=(a20/a03);
  a16=2.5506000000000000e+02;
  a16=(a16*a08);
  a08=(a20*a16);
  a01=(a01-a08);
  if (res[0]!=0) res[0][2]=a01;
  a19=(a19/a03);
  a19=(a19*a16);
  a20=(a20*a00);
  a19=(a19-a20);
  if (res[0]!=0) res[0][3]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheeled_robot_fork_1D_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int wheeled_robot_fork_1D_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wheeled_robot_fork_1D_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_robot_fork_1D_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_robot_fork_1D_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_robot_fork_1D_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_robot_fork_1D_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
