/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheeled_robot_fork_1D_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {5, 1, 1};

/* wheeled_robot_fork_1D_expl_vde_adj:(i0[4],i1[4],i2,i3)->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43;
  a00=2.;
  a01=3.5714285714285712e-02;
  a02=2.5506000000000000e+02;
  a03=31.;
  a04=2.1866666666666665e+00;
  a05=16.;
  a06=arg[0]? arg[0][0] : 0;
  a07=5.0000000000000000e-01;
  a08=arg[0]? arg[0][1] : 0;
  a09=sin(a08);
  a10=(a07*a09);
  a10=(a06-a10);
  a11=(a05*a10);
  a12=5.;
  a13=-2.0000000000000001e-01;
  a08=cos(a08);
  a14=(a13*a08);
  a14=(a06+a14);
  a14=(a14-a09);
  a15=(a12*a14);
  a11=(a11+a15);
  a15=3.;
  a16=-9.9999999999999992e-02;
  a17=(a16*a08);
  a17=(a06+a17);
  a18=1.5000000000000000e+00;
  a19=arg[3]? arg[3][0] : 0;
  a18=(a18+a19);
  a19=(a18*a09);
  a17=(a17-a19);
  a20=(a15*a17);
  a11=(a11+a20);
  a20=2.5000000000000000e-01;
  a21=(a20*a08);
  a21=(a06+a21);
  a21=(a21-a19);
  a11=(a11+a21);
  a22=-2.5000000000000000e-01;
  a23=(a22*a08);
  a23=(a06+a23);
  a23=(a23-a19);
  a11=(a11+a23);
  a19=(a00*a06);
  a11=(a11+a19);
  a19=28.;
  a11=(a11/a19);
  a10=(a10-a11);
  a24=casadi_sq(a10);
  a25=2.0000000000000001e-01;
  a26=(a07*a08);
  a26=(a25+a26);
  a27=(a05*a26);
  a28=(a13*a09);
  a28=(a25+a28);
  a28=(a28+a08);
  a29=(a12*a28);
  a27=(a27+a29);
  a29=(a16*a09);
  a29=(a25+a29);
  a30=(a18*a08);
  a29=(a29+a30);
  a31=(a15*a29);
  a27=(a27+a31);
  a31=(a20*a09);
  a31=(a25+a31);
  a31=(a31+a30);
  a27=(a27+a31);
  a32=(a22*a09);
  a32=(a25+a32);
  a32=(a32+a30);
  a27=(a27+a32);
  a30=4.0000000000000002e-01;
  a27=(a27+a30);
  a27=(a27/a19);
  a26=(a26-a27);
  a19=casadi_sq(a26);
  a24=(a24+a19);
  a24=(a05*a24);
  a04=(a04+a24);
  a24=9.7499999999999987e-01;
  a04=(a04+a24);
  a14=(a14-a11);
  a24=casadi_sq(a14);
  a28=(a28-a27);
  a19=casadi_sq(a28);
  a24=(a24+a19);
  a24=(a12*a24);
  a04=(a04+a24);
  a24=1.6250000000000003e-01;
  a04=(a04+a24);
  a17=(a17-a11);
  a24=casadi_sq(a17);
  a29=(a29-a27);
  a19=casadi_sq(a29);
  a24=(a24+a19);
  a24=(a15*a24);
  a04=(a04+a24);
  a24=3.0833333333333331e-02;
  a04=(a04+a24);
  a21=(a21-a11);
  a19=casadi_sq(a21);
  a31=(a31-a27);
  a30=casadi_sq(a31);
  a19=(a19+a30);
  a04=(a04+a19);
  a04=(a04+a24);
  a23=(a23-a11);
  a24=casadi_sq(a23);
  a32=(a32-a27);
  a19=casadi_sq(a32);
  a24=(a24+a19);
  a04=(a04+a24);
  a24=26.;
  a27=(a27-a25);
  a19=casadi_sq(a27);
  a11=(a11-a06);
  a06=casadi_sq(a11);
  a19=(a19+a06);
  a19=(a24*a19);
  a04=(a04+a19);
  a19=(a03*a04);
  a06=(a24*a27);
  a30=casadi_sq(a06);
  a19=(a19-a30);
  a30=(a03/a19);
  a33=arg[1]? arg[1][3] : 0;
  a34=(a30*a33);
  a35=(a06/a19);
  a36=arg[1]? arg[1][2] : 0;
  a37=(a35*a36);
  a34=(a34-a37);
  a34=(a02*a34);
  a37=(a11+a11);
  a38=arg[0]? arg[0][3] : 0;
  a39=casadi_sq(a38);
  a40=(a06*a39);
  a41=arg[2]? arg[2][0] : 0;
  a41=(a00*a41);
  a41=(a41/a25);
  a40=(a40+a41);
  a41=(a40*a36);
  a25=(a41/a19);
  a42=(a35/a19);
  a40=(a40*a33);
  a43=(a42*a40);
  a30=(a30/a19);
  a02=(a02*a11);
  a11=(a02*a33);
  a30=(a30*a11);
  a43=(a43-a30);
  a02=(a02*a36);
  a42=(a42*a02);
  a43=(a43+a42);
  a04=(a04/a19);
  a42=(a04/a19);
  a42=(a42*a41);
  a43=(a43-a42);
  a03=(a03*a43);
  a25=(a25+a03);
  a03=(a24*a25);
  a37=(a37*a03);
  a34=(a34+a37);
  a23=(a23+a23);
  a23=(a23*a25);
  a37=(a34-a23);
  a21=(a21+a21);
  a21=(a21*a25);
  a37=(a37-a21);
  a17=(a17+a17);
  a42=(a15*a25);
  a17=(a17*a42);
  a37=(a37-a17);
  a14=(a14+a14);
  a41=(a12*a25);
  a14=(a14*a41);
  a37=(a37-a14);
  a10=(a10+a10);
  a30=(a05*a25);
  a10=(a10*a30);
  a37=(a37-a10);
  a37=(a01*a37);
  a11=(a00*a37);
  a11=(a11-a34);
  a23=(a23+a37);
  a11=(a11+a23);
  a21=(a21+a37);
  a11=(a11+a21);
  a34=(a15*a37);
  a17=(a17+a34);
  a11=(a11+a17);
  a34=(a12*a37);
  a14=(a14+a34);
  a11=(a11+a14);
  a37=(a05*a37);
  a10=(a10+a37);
  a11=(a11+a10);
  if (res[0]!=0) res[0][0]=a11;
  a32=(a32+a32);
  a32=(a32*a25);
  a04=(a04*a36);
  a35=(a35*a33);
  a04=(a04-a35);
  a39=(a39*a04);
  a39=(a24*a39);
  a40=(a40/a19);
  a02=(a02/a19);
  a40=(a40+a02);
  a02=(a06+a06);
  a02=(a02*a43);
  a40=(a40+a02);
  a24=(a24*a40);
  a39=(a39-a24);
  a27=(a27+a27);
  a27=(a27*a03);
  a39=(a39+a27);
  a39=(a39-a32);
  a31=(a31+a31);
  a31=(a31*a25);
  a39=(a39-a31);
  a29=(a29+a29);
  a29=(a29*a42);
  a39=(a39-a29);
  a28=(a28+a28);
  a28=(a28*a41);
  a39=(a39-a28);
  a26=(a26+a26);
  a26=(a26*a30);
  a39=(a39-a26);
  a01=(a01*a39);
  a32=(a32+a01);
  a39=(a22*a32);
  a31=(a31+a01);
  a30=(a20*a31);
  a39=(a39+a30);
  a15=(a15*a01);
  a29=(a29+a15);
  a15=(a16*a29);
  a39=(a39+a15);
  a15=(a12*a01);
  a28=(a28+a15);
  a15=(a13*a28);
  a39=(a39+a15);
  a15=(a18*a23);
  a39=(a39-a15);
  a15=(a18*a21);
  a39=(a39-a15);
  a15=(a18*a17);
  a39=(a39-a15);
  a39=(a39-a14);
  a10=(a07*a10);
  a39=(a39-a10);
  a08=(a08*a39);
  a32=(a18*a32);
  a31=(a18*a31);
  a32=(a32+a31);
  a18=(a18*a29);
  a32=(a32+a18);
  a32=(a32+a28);
  a05=(a05*a01);
  a26=(a26+a05);
  a07=(a07*a26);
  a32=(a32+a07);
  a22=(a22*a23);
  a32=(a32+a22);
  a20=(a20*a21);
  a32=(a32+a20);
  a16=(a16*a17);
  a32=(a32+a16);
  a13=(a13*a14);
  a32=(a32+a13);
  a09=(a09*a32);
  a08=(a08-a09);
  if (res[0]!=0) res[0][1]=a08;
  a08=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][2]=a08;
  a38=(a38+a38);
  a06=(a06*a04);
  a38=(a38*a06);
  a06=arg[1]? arg[1][1] : 0;
  a38=(a38+a06);
  if (res[0]!=0) res[0][3]=a38;
  a12=(a12*a04);
  a00=(a00*a12);
  if (res[0]!=0) res[0][4]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheeled_robot_fork_1D_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int wheeled_robot_fork_1D_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wheeled_robot_fork_1D_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_robot_fork_1D_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_robot_fork_1D_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_robot_fork_1D_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_robot_fork_1D_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
