/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheeled_robot_fork_1D_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* wheeled_robot_fork_1D_expl_vde_forw:(i0[4],i1[4x4],i2[4],i3,i4)->(o0[4],o1[4x4],o2[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a01=2.1866666666666665e+00;
  a02=16.;
  a03=arg[0]? arg[0][0] : 0;
  a04=5.0000000000000000e-01;
  a05=arg[0]? arg[0][1] : 0;
  a06=sin(a05);
  a07=(a04*a06);
  a07=(a03-a07);
  a08=(a02*a07);
  a09=5.;
  a10=-2.0000000000000001e-01;
  a05=cos(a05);
  a11=(a10*a05);
  a11=(a03+a11);
  a11=(a11-a06);
  a12=(a09*a11);
  a08=(a08+a12);
  a12=3.;
  a13=-9.9999999999999992e-02;
  a14=(a13*a05);
  a14=(a03+a14);
  a15=1.5000000000000000e+00;
  a16=arg[4]? arg[4][0] : 0;
  a15=(a15+a16);
  a16=(a15*a06);
  a14=(a14-a16);
  a17=(a12*a14);
  a08=(a08+a17);
  a17=2.5000000000000000e-01;
  a18=(a17*a05);
  a18=(a03+a18);
  a18=(a18-a16);
  a08=(a08+a18);
  a19=-2.5000000000000000e-01;
  a20=(a19*a05);
  a20=(a03+a20);
  a20=(a20-a16);
  a08=(a08+a20);
  a16=2.;
  a21=(a16*a03);
  a08=(a08+a21);
  a21=28.;
  a08=(a08/a21);
  a07=(a07-a08);
  a22=casadi_sq(a07);
  a23=2.0000000000000001e-01;
  a24=(a04*a05);
  a24=(a23+a24);
  a25=(a02*a24);
  a26=(a10*a06);
  a26=(a23+a26);
  a26=(a26+a05);
  a27=(a09*a26);
  a25=(a25+a27);
  a27=(a13*a06);
  a27=(a23+a27);
  a28=(a15*a05);
  a27=(a27+a28);
  a29=(a12*a27);
  a25=(a25+a29);
  a29=(a17*a06);
  a29=(a23+a29);
  a29=(a29+a28);
  a25=(a25+a29);
  a30=(a19*a06);
  a30=(a23+a30);
  a30=(a30+a28);
  a25=(a25+a30);
  a28=4.0000000000000002e-01;
  a25=(a25+a28);
  a25=(a25/a21);
  a24=(a24-a25);
  a21=casadi_sq(a24);
  a22=(a22+a21);
  a22=(a02*a22);
  a01=(a01+a22);
  a22=9.7499999999999987e-01;
  a01=(a01+a22);
  a11=(a11-a08);
  a22=casadi_sq(a11);
  a26=(a26-a25);
  a21=casadi_sq(a26);
  a22=(a22+a21);
  a22=(a09*a22);
  a01=(a01+a22);
  a22=1.6250000000000003e-01;
  a01=(a01+a22);
  a14=(a14-a08);
  a22=casadi_sq(a14);
  a27=(a27-a25);
  a21=casadi_sq(a27);
  a22=(a22+a21);
  a22=(a12*a22);
  a01=(a01+a22);
  a22=3.0833333333333331e-02;
  a01=(a01+a22);
  a18=(a18-a08);
  a21=casadi_sq(a18);
  a29=(a29-a25);
  a28=casadi_sq(a29);
  a21=(a21+a28);
  a01=(a01+a21);
  a01=(a01+a22);
  a20=(a20-a08);
  a22=casadi_sq(a20);
  a30=(a30-a25);
  a21=casadi_sq(a30);
  a22=(a22+a21);
  a01=(a01+a22);
  a22=26.;
  a25=(a25-a23);
  a21=casadi_sq(a25);
  a08=(a08-a03);
  a03=casadi_sq(a08);
  a21=(a21+a03);
  a21=(a22*a21);
  a01=(a01+a21);
  a21=31.;
  a03=(a21*a01);
  a28=(a22*a25);
  a31=casadi_sq(a28);
  a03=(a03-a31);
  a01=(a01/a03);
  a31=casadi_sq(a00);
  a32=(a28*a31);
  a33=arg[3]? arg[3][0] : 0;
  a33=(a16*a33);
  a33=(a33/a23);
  a32=(a32+a33);
  a33=(a01*a32);
  a23=(a28/a03);
  a34=2.5506000000000000e+02;
  a35=(a34*a08);
  a36=(a23*a35);
  a33=(a33-a36);
  if (res[0]!=0) res[0][2]=a33;
  a33=(a21/a03);
  a36=(a33*a35);
  a37=(a23*a32);
  a36=(a36-a37);
  if (res[0]!=0) res[0][3]=a36;
  a36=arg[1]? arg[1][2] : 0;
  if (res[1]!=0) res[1][0]=a36;
  a36=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][1]=a36;
  a07=(a07+a07);
  a37=arg[1]? arg[1][0] : 0;
  a38=arg[1]? arg[1][1] : 0;
  a39=(a05*a38);
  a40=(a04*a39);
  a40=(a37-a40);
  a41=3.5714285714285712e-02;
  a42=(a02*a40);
  a38=(a06*a38);
  a43=(a10*a38);
  a43=(a37-a43);
  a43=(a43-a39);
  a44=(a09*a43);
  a42=(a42+a44);
  a44=(a13*a38);
  a44=(a37-a44);
  a45=(a15*a39);
  a44=(a44-a45);
  a46=(a12*a44);
  a42=(a42+a46);
  a46=(a17*a38);
  a46=(a37-a46);
  a46=(a46-a45);
  a42=(a42+a46);
  a47=(a19*a38);
  a47=(a37-a47);
  a47=(a47-a45);
  a42=(a42+a47);
  a45=(a16*a37);
  a42=(a42+a45);
  a42=(a41*a42);
  a40=(a40-a42);
  a40=(a07*a40);
  a24=(a24+a24);
  a45=(a04*a38);
  a48=(a10*a39);
  a48=(a48-a38);
  a49=(a09*a48);
  a50=(a02*a45);
  a49=(a49-a50);
  a50=(a13*a39);
  a38=(a15*a38);
  a50=(a50-a38);
  a51=(a12*a50);
  a49=(a49+a51);
  a51=(a17*a39);
  a51=(a51-a38);
  a49=(a49+a51);
  a39=(a19*a39);
  a39=(a39-a38);
  a49=(a49+a39);
  a49=(a41*a49);
  a45=(a45+a49);
  a45=(a24*a45);
  a40=(a40-a45);
  a40=(a02*a40);
  a11=(a11+a11);
  a43=(a43-a42);
  a43=(a11*a43);
  a26=(a26+a26);
  a48=(a48-a49);
  a48=(a26*a48);
  a43=(a43+a48);
  a43=(a09*a43);
  a40=(a40+a43);
  a14=(a14+a14);
  a44=(a44-a42);
  a44=(a14*a44);
  a27=(a27+a27);
  a50=(a50-a49);
  a50=(a27*a50);
  a44=(a44+a50);
  a44=(a12*a44);
  a40=(a40+a44);
  a18=(a18+a18);
  a46=(a46-a42);
  a46=(a18*a46);
  a29=(a29+a29);
  a51=(a51-a49);
  a51=(a29*a51);
  a46=(a46+a51);
  a40=(a40+a46);
  a20=(a20+a20);
  a47=(a47-a42);
  a47=(a20*a47);
  a30=(a30+a30);
  a39=(a39-a49);
  a39=(a30*a39);
  a47=(a47+a39);
  a40=(a40+a47);
  a25=(a25+a25);
  a47=(a25*a49);
  a08=(a08+a08);
  a42=(a42-a37);
  a37=(a08*a42);
  a47=(a47+a37);
  a47=(a22*a47);
  a40=(a40+a47);
  a47=(a40/a03);
  a37=(a01/a03);
  a40=(a21*a40);
  a39=(a28+a28);
  a49=(a22*a49);
  a46=(a39*a49);
  a40=(a40-a46);
  a46=(a37*a40);
  a47=(a47-a46);
  a47=(a32*a47);
  a46=(a31*a49);
  a00=(a00+a00);
  a36=(a00*a36);
  a36=(a28*a36);
  a46=(a46+a36);
  a36=(a01*a46);
  a47=(a47+a36);
  a49=(a49/a03);
  a36=(a23/a03);
  a51=(a36*a40);
  a49=(a49-a51);
  a51=(a35*a49);
  a42=(a34*a42);
  a44=(a23*a42);
  a51=(a51+a44);
  a47=(a47-a51);
  if (res[1]!=0) res[1][2]=a47;
  a42=(a33*a42);
  a47=(a33/a03);
  a40=(a47*a40);
  a40=(a35*a40);
  a42=(a42-a40);
  a49=(a32*a49);
  a46=(a23*a46);
  a49=(a49+a46);
  a42=(a42-a49);
  if (res[1]!=0) res[1][3]=a42;
  a42=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][4]=a42;
  a42=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][5]=a42;
  a49=arg[1]? arg[1][4] : 0;
  a46=arg[1]? arg[1][5] : 0;
  a40=(a05*a46);
  a51=(a04*a40);
  a51=(a49-a51);
  a44=(a02*a51);
  a46=(a06*a46);
  a50=(a10*a46);
  a50=(a49-a50);
  a50=(a50-a40);
  a43=(a09*a50);
  a44=(a44+a43);
  a43=(a13*a46);
  a43=(a49-a43);
  a48=(a15*a40);
  a43=(a43-a48);
  a45=(a12*a43);
  a44=(a44+a45);
  a45=(a17*a46);
  a45=(a49-a45);
  a45=(a45-a48);
  a44=(a44+a45);
  a38=(a19*a46);
  a38=(a49-a38);
  a38=(a38-a48);
  a44=(a44+a38);
  a48=(a16*a49);
  a44=(a44+a48);
  a44=(a41*a44);
  a51=(a51-a44);
  a51=(a07*a51);
  a48=(a04*a46);
  a52=(a10*a40);
  a52=(a52-a46);
  a53=(a09*a52);
  a54=(a02*a48);
  a53=(a53-a54);
  a54=(a13*a40);
  a46=(a15*a46);
  a54=(a54-a46);
  a55=(a12*a54);
  a53=(a53+a55);
  a55=(a17*a40);
  a55=(a55-a46);
  a53=(a53+a55);
  a40=(a19*a40);
  a40=(a40-a46);
  a53=(a53+a40);
  a53=(a41*a53);
  a48=(a48+a53);
  a48=(a24*a48);
  a51=(a51-a48);
  a51=(a02*a51);
  a50=(a50-a44);
  a50=(a11*a50);
  a52=(a52-a53);
  a52=(a26*a52);
  a50=(a50+a52);
  a50=(a09*a50);
  a51=(a51+a50);
  a43=(a43-a44);
  a43=(a14*a43);
  a54=(a54-a53);
  a54=(a27*a54);
  a43=(a43+a54);
  a43=(a12*a43);
  a51=(a51+a43);
  a45=(a45-a44);
  a45=(a18*a45);
  a55=(a55-a53);
  a55=(a29*a55);
  a45=(a45+a55);
  a51=(a51+a45);
  a38=(a38-a44);
  a38=(a20*a38);
  a40=(a40-a53);
  a40=(a30*a40);
  a38=(a38+a40);
  a51=(a51+a38);
  a38=(a25*a53);
  a44=(a44-a49);
  a49=(a08*a44);
  a38=(a38+a49);
  a38=(a22*a38);
  a51=(a51+a38);
  a38=(a51/a03);
  a51=(a21*a51);
  a53=(a22*a53);
  a49=(a39*a53);
  a51=(a51-a49);
  a49=(a37*a51);
  a38=(a38-a49);
  a38=(a32*a38);
  a49=(a31*a53);
  a42=(a00*a42);
  a42=(a28*a42);
  a49=(a49+a42);
  a42=(a01*a49);
  a38=(a38+a42);
  a53=(a53/a03);
  a42=(a36*a51);
  a53=(a53-a42);
  a42=(a35*a53);
  a44=(a34*a44);
  a40=(a23*a44);
  a42=(a42+a40);
  a38=(a38-a42);
  if (res[1]!=0) res[1][6]=a38;
  a44=(a33*a44);
  a51=(a47*a51);
  a51=(a35*a51);
  a44=(a44-a51);
  a53=(a32*a53);
  a49=(a23*a49);
  a53=(a53+a49);
  a44=(a44-a53);
  if (res[1]!=0) res[1][7]=a44;
  a44=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][8]=a44;
  a44=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][9]=a44;
  a53=arg[1]? arg[1][8] : 0;
  a49=arg[1]? arg[1][9] : 0;
  a51=(a05*a49);
  a38=(a04*a51);
  a38=(a53-a38);
  a42=(a02*a38);
  a49=(a06*a49);
  a40=(a10*a49);
  a40=(a53-a40);
  a40=(a40-a51);
  a45=(a09*a40);
  a42=(a42+a45);
  a45=(a13*a49);
  a45=(a53-a45);
  a55=(a15*a51);
  a45=(a45-a55);
  a43=(a12*a45);
  a42=(a42+a43);
  a43=(a17*a49);
  a43=(a53-a43);
  a43=(a43-a55);
  a42=(a42+a43);
  a54=(a19*a49);
  a54=(a53-a54);
  a54=(a54-a55);
  a42=(a42+a54);
  a55=(a16*a53);
  a42=(a42+a55);
  a42=(a41*a42);
  a38=(a38-a42);
  a38=(a07*a38);
  a55=(a04*a49);
  a50=(a10*a51);
  a50=(a50-a49);
  a52=(a09*a50);
  a48=(a02*a55);
  a52=(a52-a48);
  a48=(a13*a51);
  a49=(a15*a49);
  a48=(a48-a49);
  a46=(a12*a48);
  a52=(a52+a46);
  a46=(a17*a51);
  a46=(a46-a49);
  a52=(a52+a46);
  a51=(a19*a51);
  a51=(a51-a49);
  a52=(a52+a51);
  a52=(a41*a52);
  a55=(a55+a52);
  a55=(a24*a55);
  a38=(a38-a55);
  a38=(a02*a38);
  a40=(a40-a42);
  a40=(a11*a40);
  a50=(a50-a52);
  a50=(a26*a50);
  a40=(a40+a50);
  a40=(a09*a40);
  a38=(a38+a40);
  a45=(a45-a42);
  a45=(a14*a45);
  a48=(a48-a52);
  a48=(a27*a48);
  a45=(a45+a48);
  a45=(a12*a45);
  a38=(a38+a45);
  a43=(a43-a42);
  a43=(a18*a43);
  a46=(a46-a52);
  a46=(a29*a46);
  a43=(a43+a46);
  a38=(a38+a43);
  a54=(a54-a42);
  a54=(a20*a54);
  a51=(a51-a52);
  a51=(a30*a51);
  a54=(a54+a51);
  a38=(a38+a54);
  a54=(a25*a52);
  a42=(a42-a53);
  a53=(a08*a42);
  a54=(a54+a53);
  a54=(a22*a54);
  a38=(a38+a54);
  a54=(a38/a03);
  a38=(a21*a38);
  a52=(a22*a52);
  a53=(a39*a52);
  a38=(a38-a53);
  a53=(a37*a38);
  a54=(a54-a53);
  a54=(a32*a54);
  a53=(a31*a52);
  a44=(a00*a44);
  a44=(a28*a44);
  a53=(a53+a44);
  a44=(a01*a53);
  a54=(a54+a44);
  a52=(a52/a03);
  a44=(a36*a38);
  a52=(a52-a44);
  a44=(a35*a52);
  a42=(a34*a42);
  a51=(a23*a42);
  a44=(a44+a51);
  a54=(a54-a44);
  if (res[1]!=0) res[1][10]=a54;
  a42=(a33*a42);
  a38=(a47*a38);
  a38=(a35*a38);
  a42=(a42-a38);
  a52=(a32*a52);
  a53=(a23*a53);
  a52=(a52+a53);
  a42=(a42-a52);
  if (res[1]!=0) res[1][11]=a42;
  a42=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][12]=a42;
  a42=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][13]=a42;
  a52=arg[1]? arg[1][12] : 0;
  a53=arg[1]? arg[1][13] : 0;
  a38=(a05*a53);
  a54=(a04*a38);
  a54=(a52-a54);
  a44=(a02*a54);
  a53=(a06*a53);
  a51=(a10*a53);
  a51=(a52-a51);
  a51=(a51-a38);
  a43=(a09*a51);
  a44=(a44+a43);
  a43=(a13*a53);
  a43=(a52-a43);
  a46=(a15*a38);
  a43=(a43-a46);
  a45=(a12*a43);
  a44=(a44+a45);
  a45=(a17*a53);
  a45=(a52-a45);
  a45=(a45-a46);
  a44=(a44+a45);
  a48=(a19*a53);
  a48=(a52-a48);
  a48=(a48-a46);
  a44=(a44+a48);
  a46=(a16*a52);
  a44=(a44+a46);
  a44=(a41*a44);
  a54=(a54-a44);
  a54=(a07*a54);
  a46=(a04*a53);
  a40=(a10*a38);
  a40=(a40-a53);
  a50=(a09*a40);
  a55=(a02*a46);
  a50=(a50-a55);
  a55=(a13*a38);
  a53=(a15*a53);
  a55=(a55-a53);
  a49=(a12*a55);
  a50=(a50+a49);
  a49=(a17*a38);
  a49=(a49-a53);
  a50=(a50+a49);
  a38=(a19*a38);
  a38=(a38-a53);
  a50=(a50+a38);
  a50=(a41*a50);
  a46=(a46+a50);
  a46=(a24*a46);
  a54=(a54-a46);
  a54=(a02*a54);
  a51=(a51-a44);
  a51=(a11*a51);
  a40=(a40-a50);
  a40=(a26*a40);
  a51=(a51+a40);
  a51=(a09*a51);
  a54=(a54+a51);
  a43=(a43-a44);
  a43=(a14*a43);
  a55=(a55-a50);
  a55=(a27*a55);
  a43=(a43+a55);
  a43=(a12*a43);
  a54=(a54+a43);
  a45=(a45-a44);
  a45=(a18*a45);
  a49=(a49-a50);
  a49=(a29*a49);
  a45=(a45+a49);
  a54=(a54+a45);
  a48=(a48-a44);
  a48=(a20*a48);
  a38=(a38-a50);
  a38=(a30*a38);
  a48=(a48+a38);
  a54=(a54+a48);
  a48=(a25*a50);
  a44=(a44-a52);
  a52=(a08*a44);
  a48=(a48+a52);
  a48=(a22*a48);
  a54=(a54+a48);
  a48=(a54/a03);
  a54=(a21*a54);
  a50=(a22*a50);
  a52=(a39*a50);
  a54=(a54-a52);
  a52=(a37*a54);
  a48=(a48-a52);
  a48=(a32*a48);
  a52=(a31*a50);
  a42=(a00*a42);
  a42=(a28*a42);
  a52=(a52+a42);
  a42=(a01*a52);
  a48=(a48+a42);
  a50=(a50/a03);
  a42=(a36*a54);
  a50=(a50-a42);
  a42=(a35*a50);
  a44=(a34*a44);
  a38=(a23*a44);
  a42=(a42+a38);
  a48=(a48-a42);
  if (res[1]!=0) res[1][14]=a48;
  a44=(a33*a44);
  a54=(a47*a54);
  a54=(a35*a54);
  a44=(a44-a54);
  a50=(a32*a50);
  a52=(a23*a52);
  a50=(a50+a52);
  a44=(a44-a50);
  if (res[1]!=0) res[1][15]=a44;
  a44=arg[2]? arg[2][2] : 0;
  if (res[2]!=0) res[2][0]=a44;
  a44=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][1]=a44;
  a50=10.;
  a52=(a50*a01);
  a54=arg[2]? arg[2][0] : 0;
  a48=arg[2]? arg[2][1] : 0;
  a05=(a05*a48);
  a42=(a04*a05);
  a42=(a54-a42);
  a38=(a02*a42);
  a06=(a06*a48);
  a48=(a10*a06);
  a48=(a54-a48);
  a48=(a48-a05);
  a45=(a09*a48);
  a38=(a38+a45);
  a45=(a13*a06);
  a45=(a54-a45);
  a49=(a15*a05);
  a45=(a45-a49);
  a43=(a12*a45);
  a38=(a38+a43);
  a43=(a17*a06);
  a43=(a54-a43);
  a43=(a43-a49);
  a38=(a38+a43);
  a55=(a19*a06);
  a55=(a54-a55);
  a55=(a55-a49);
  a38=(a38+a55);
  a16=(a16*a54);
  a38=(a38+a16);
  a38=(a41*a38);
  a42=(a42-a38);
  a07=(a07*a42);
  a04=(a04*a06);
  a10=(a10*a05);
  a10=(a10-a06);
  a42=(a09*a10);
  a16=(a02*a04);
  a42=(a42-a16);
  a13=(a13*a05);
  a15=(a15*a06);
  a13=(a13-a15);
  a06=(a12*a13);
  a42=(a42+a06);
  a17=(a17*a05);
  a17=(a17-a15);
  a42=(a42+a17);
  a19=(a19*a05);
  a19=(a19-a15);
  a42=(a42+a19);
  a41=(a41*a42);
  a04=(a04+a41);
  a24=(a24*a04);
  a07=(a07-a24);
  a02=(a02*a07);
  a48=(a48-a38);
  a11=(a11*a48);
  a10=(a10-a41);
  a26=(a26*a10);
  a11=(a11+a26);
  a09=(a09*a11);
  a02=(a02+a09);
  a45=(a45-a38);
  a14=(a14*a45);
  a13=(a13-a41);
  a27=(a27*a13);
  a14=(a14+a27);
  a12=(a12*a14);
  a02=(a02+a12);
  a43=(a43-a38);
  a18=(a18*a43);
  a17=(a17-a41);
  a29=(a29*a17);
  a18=(a18+a29);
  a02=(a02+a18);
  a55=(a55-a38);
  a20=(a20*a55);
  a19=(a19-a41);
  a30=(a30*a19);
  a20=(a20+a30);
  a02=(a02+a20);
  a25=(a25*a41);
  a38=(a38-a54);
  a08=(a08*a38);
  a25=(a25+a08);
  a25=(a22*a25);
  a02=(a02+a25);
  a25=(a02/a03);
  a21=(a21*a02);
  a22=(a22*a41);
  a39=(a39*a22);
  a21=(a21-a39);
  a37=(a37*a21);
  a25=(a25-a37);
  a25=(a32*a25);
  a31=(a31*a22);
  a00=(a00*a44);
  a28=(a28*a00);
  a31=(a31+a28);
  a01=(a01*a31);
  a25=(a25+a01);
  a22=(a22/a03);
  a36=(a36*a21);
  a22=(a22-a36);
  a36=(a35*a22);
  a34=(a34*a38);
  a38=(a23*a34);
  a36=(a36+a38);
  a25=(a25-a36);
  a52=(a52+a25);
  if (res[2]!=0) res[2][2]=a52;
  a33=(a33*a34);
  a47=(a47*a21);
  a35=(a35*a47);
  a33=(a33-a35);
  a32=(a32*a22);
  a31=(a23*a31);
  a32=(a32+a31);
  a33=(a33-a32);
  a50=(a50*a23);
  a33=(a33-a50);
  if (res[2]!=0) res[2][3]=a33;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheeled_robot_fork_1D_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheeled_robot_fork_1D_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int wheeled_robot_fork_1D_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real wheeled_robot_fork_1D_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_robot_fork_1D_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_robot_fork_1D_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_robot_fork_1D_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_robot_fork_1D_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_fork_1D_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
