/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) simplified_inverted_pendulum_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {4, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};

/* simplified_inverted_pendulum_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[])->(o0[4],o1[4x4],o2[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=1.0500000000000000e+01;
  a03=8.7500000000000000e-01;
  a04=arg[0]? arg[0][1] : 0;
  a05=cos(a04);
  a06=(a03*a05);
  a07=-2.3199999999999998e-02;
  a04=sin(a04);
  a08=(a07*a04);
  a08=(a06-a08);
  a09=(a08+a08);
  a10=(a08*a09);
  a11=2.3199999999999998e-02;
  a12=(a11*a05);
  a13=(a03*a04);
  a12=(a12-a13);
  a14=(a12+a12);
  a15=(a12*a14);
  a10=(a10+a15);
  a10=(a02*a10);
  a15=8.4100000000000001e+00;
  a10=(a10+a15);
  a15=27.;
  a16=(a15*a10);
  a17=(a02*a09);
  a18=2.;
  a19=(a18*a08);
  a19=(a02*a19);
  a20=(a17*a19);
  a16=(a16-a20);
  a10=(a10/a16);
  a20=arg[3]? arg[3][0] : 0;
  a21=arg[3]? arg[3][1] : 0;
  a20=(a20+a21);
  a21=2.0000000000000001e-01;
  a20=(a20/a21);
  a21=(a07*a01);
  a22=(a21*a05);
  a23=(a03*a01);
  a24=(a23*a04);
  a22=(a22+a24);
  a25=(a22+a22);
  a26=(a02*a25);
  a27=(a26*a01);
  a20=(a20+a27);
  a27=(a10*a20);
  a28=(a17/a16);
  a29=(a21*a04);
  a00=(a00-a29);
  a29=(a23*a05);
  a00=(a00+a29);
  a00=(a00+a00);
  a30=(a00*a22);
  a31=(a11*a01);
  a32=(a31*a05);
  a32=(a32-a24);
  a32=(a32+a32);
  a24=(a31*a04);
  a24=(a24+a29);
  a29=(a32*a24);
  a30=(a30+a29);
  a30=(a02*a30);
  a29=2.0601000000000002e+02;
  a33=(a29*a12);
  a30=(a30+a33);
  a33=(a08*a25);
  a34=(a07*a05);
  a13=(a13+a34);
  a34=(a00*a13);
  a33=(a33+a34);
  a34=(a24+a24);
  a35=(a12*a34);
  a36=(a11*a04);
  a36=(a36+a06);
  a06=(a32*a36);
  a35=(a35+a06);
  a33=(a33+a35);
  a33=(a02*a33);
  a35=(a33*a01);
  a30=(a30-a35);
  a35=(a28*a30);
  a27=(a27+a35);
  if (res[0]!=0) res[0][2]=a27;
  a27=(a19/a16);
  a35=(a27*a20);
  a06=(a15/a16);
  a37=(a06*a30);
  a35=(a35+a37);
  a35=(-a35);
  if (res[0]!=0) res[0][3]=a35;
  a35=arg[1]? arg[1][2] : 0;
  if (res[1]!=0) res[1][0]=a35;
  a37=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][1]=a37;
  a38=(a07*a37);
  a39=(a05*a38);
  a40=arg[1]? arg[1][1] : 0;
  a41=(a04*a40);
  a42=(a21*a41);
  a39=(a39-a42);
  a42=(a03*a37);
  a43=(a04*a42);
  a40=(a05*a40);
  a44=(a23*a40);
  a43=(a43+a44);
  a39=(a39+a43);
  a44=(a39+a39);
  a45=(a02*a44);
  a45=(a01*a45);
  a46=(a26*a37);
  a45=(a45+a46);
  a46=(a10*a45);
  a47=(a03*a41);
  a48=(a07*a40);
  a48=(a47+a48);
  a49=(a09*a48);
  a50=(a48+a48);
  a51=(a08*a50);
  a49=(a49+a51);
  a51=(a11*a41);
  a52=(a03*a40);
  a51=(a51+a52);
  a53=(a14*a51);
  a54=(a51+a51);
  a54=(a12*a54);
  a53=(a53+a54);
  a49=(a49+a53);
  a49=(a02*a49);
  a53=(a49/a16);
  a54=(a10/a16);
  a50=(a02*a50);
  a55=(a19*a50);
  a56=(a18*a48);
  a56=(a02*a56);
  a57=(a17*a56);
  a55=(a55+a57);
  a49=(a15*a49);
  a55=(a55-a49);
  a49=(a54*a55);
  a53=(a53+a49);
  a53=(a20*a53);
  a46=(a46-a53);
  a38=(a04*a38);
  a53=(a21*a40);
  a38=(a38+a53);
  a35=(a35-a38);
  a42=(a05*a42);
  a38=(a23*a41);
  a42=(a42-a38);
  a35=(a35+a42);
  a35=(a35+a35);
  a38=(a22*a35);
  a39=(a00*a39);
  a38=(a38+a39);
  a39=(a11*a37);
  a53=(a05*a39);
  a49=(a31*a41);
  a53=(a53-a49);
  a53=(a53-a43);
  a53=(a53+a53);
  a43=(a24*a53);
  a39=(a04*a39);
  a49=(a31*a40);
  a39=(a39+a49);
  a39=(a39+a42);
  a42=(a32*a39);
  a43=(a43+a42);
  a38=(a38+a43);
  a38=(a02*a38);
  a43=(a29*a51);
  a38=(a38-a43);
  a44=(a08*a44);
  a48=(a25*a48);
  a44=(a44-a48);
  a35=(a13*a35);
  a41=(a07*a41);
  a52=(a52-a41);
  a52=(a00*a52);
  a35=(a35+a52);
  a44=(a44+a35);
  a39=(a39+a39);
  a39=(a12*a39);
  a51=(a34*a51);
  a39=(a39-a51);
  a53=(a36*a53);
  a40=(a11*a40);
  a40=(a40-a47);
  a40=(a32*a40);
  a53=(a53+a40);
  a39=(a39+a53);
  a44=(a44+a39);
  a44=(a02*a44);
  a44=(a01*a44);
  a37=(a33*a37);
  a44=(a44+a37);
  a38=(a38-a44);
  a44=(a28*a38);
  a50=(a50/a16);
  a37=(a28/a16);
  a39=(a37*a55);
  a50=(a50+a39);
  a50=(a30*a50);
  a44=(a44-a50);
  a46=(a46+a44);
  if (res[1]!=0) res[1][2]=a46;
  a45=(a27*a45);
  a56=(a56/a16);
  a46=(a27/a16);
  a44=(a46*a55);
  a56=(a56+a44);
  a56=(a20*a56);
  a45=(a45-a56);
  a38=(a06*a38);
  a56=(a06/a16);
  a55=(a56*a55);
  a55=(a30*a55);
  a38=(a38-a55);
  a45=(a45+a38);
  a45=(-a45);
  if (res[1]!=0) res[1][3]=a45;
  a45=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][4]=a45;
  a38=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][5]=a38;
  a55=(a07*a38);
  a44=(a05*a55);
  a50=arg[1]? arg[1][5] : 0;
  a39=(a04*a50);
  a53=(a21*a39);
  a44=(a44-a53);
  a53=(a03*a38);
  a40=(a04*a53);
  a50=(a05*a50);
  a47=(a23*a50);
  a40=(a40+a47);
  a44=(a44+a40);
  a47=(a44+a44);
  a51=(a02*a47);
  a51=(a01*a51);
  a35=(a26*a38);
  a51=(a51+a35);
  a35=(a10*a51);
  a52=(a03*a39);
  a41=(a07*a50);
  a41=(a52+a41);
  a48=(a09*a41);
  a43=(a41+a41);
  a42=(a08*a43);
  a48=(a48+a42);
  a42=(a11*a39);
  a49=(a03*a50);
  a42=(a42+a49);
  a57=(a14*a42);
  a58=(a42+a42);
  a58=(a12*a58);
  a57=(a57+a58);
  a48=(a48+a57);
  a48=(a02*a48);
  a57=(a48/a16);
  a43=(a02*a43);
  a58=(a19*a43);
  a59=(a18*a41);
  a59=(a02*a59);
  a60=(a17*a59);
  a58=(a58+a60);
  a48=(a15*a48);
  a58=(a58-a48);
  a48=(a54*a58);
  a57=(a57+a48);
  a57=(a20*a57);
  a35=(a35-a57);
  a55=(a04*a55);
  a57=(a21*a50);
  a55=(a55+a57);
  a45=(a45-a55);
  a53=(a05*a53);
  a55=(a23*a39);
  a53=(a53-a55);
  a45=(a45+a53);
  a45=(a45+a45);
  a55=(a22*a45);
  a44=(a00*a44);
  a55=(a55+a44);
  a44=(a11*a38);
  a57=(a05*a44);
  a48=(a31*a39);
  a57=(a57-a48);
  a57=(a57-a40);
  a57=(a57+a57);
  a40=(a24*a57);
  a44=(a04*a44);
  a48=(a31*a50);
  a44=(a44+a48);
  a44=(a44+a53);
  a53=(a32*a44);
  a40=(a40+a53);
  a55=(a55+a40);
  a55=(a02*a55);
  a40=(a29*a42);
  a55=(a55-a40);
  a47=(a08*a47);
  a41=(a25*a41);
  a47=(a47-a41);
  a45=(a13*a45);
  a39=(a07*a39);
  a49=(a49-a39);
  a49=(a00*a49);
  a45=(a45+a49);
  a47=(a47+a45);
  a44=(a44+a44);
  a44=(a12*a44);
  a42=(a34*a42);
  a44=(a44-a42);
  a57=(a36*a57);
  a50=(a11*a50);
  a50=(a50-a52);
  a50=(a32*a50);
  a57=(a57+a50);
  a44=(a44+a57);
  a47=(a47+a44);
  a47=(a02*a47);
  a47=(a01*a47);
  a38=(a33*a38);
  a47=(a47+a38);
  a55=(a55-a47);
  a47=(a28*a55);
  a43=(a43/a16);
  a38=(a37*a58);
  a43=(a43+a38);
  a43=(a30*a43);
  a47=(a47-a43);
  a35=(a35+a47);
  if (res[1]!=0) res[1][6]=a35;
  a51=(a27*a51);
  a59=(a59/a16);
  a35=(a46*a58);
  a59=(a59+a35);
  a59=(a20*a59);
  a51=(a51-a59);
  a55=(a06*a55);
  a58=(a56*a58);
  a58=(a30*a58);
  a55=(a55-a58);
  a51=(a51+a55);
  a51=(-a51);
  if (res[1]!=0) res[1][7]=a51;
  a51=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][8]=a51;
  a55=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][9]=a55;
  a58=(a07*a55);
  a59=(a05*a58);
  a35=arg[1]? arg[1][9] : 0;
  a47=(a04*a35);
  a43=(a21*a47);
  a59=(a59-a43);
  a43=(a03*a55);
  a38=(a04*a43);
  a35=(a05*a35);
  a44=(a23*a35);
  a38=(a38+a44);
  a59=(a59+a38);
  a44=(a59+a59);
  a57=(a02*a44);
  a57=(a01*a57);
  a50=(a26*a55);
  a57=(a57+a50);
  a50=(a10*a57);
  a52=(a03*a47);
  a42=(a07*a35);
  a42=(a52+a42);
  a45=(a09*a42);
  a49=(a42+a42);
  a39=(a08*a49);
  a45=(a45+a39);
  a39=(a11*a47);
  a41=(a03*a35);
  a39=(a39+a41);
  a40=(a14*a39);
  a53=(a39+a39);
  a53=(a12*a53);
  a40=(a40+a53);
  a45=(a45+a40);
  a45=(a02*a45);
  a40=(a45/a16);
  a49=(a02*a49);
  a53=(a19*a49);
  a48=(a18*a42);
  a48=(a02*a48);
  a60=(a17*a48);
  a53=(a53+a60);
  a45=(a15*a45);
  a53=(a53-a45);
  a45=(a54*a53);
  a40=(a40+a45);
  a40=(a20*a40);
  a50=(a50-a40);
  a58=(a04*a58);
  a40=(a21*a35);
  a58=(a58+a40);
  a51=(a51-a58);
  a43=(a05*a43);
  a58=(a23*a47);
  a43=(a43-a58);
  a51=(a51+a43);
  a51=(a51+a51);
  a58=(a22*a51);
  a59=(a00*a59);
  a58=(a58+a59);
  a59=(a11*a55);
  a40=(a05*a59);
  a45=(a31*a47);
  a40=(a40-a45);
  a40=(a40-a38);
  a40=(a40+a40);
  a38=(a24*a40);
  a59=(a04*a59);
  a45=(a31*a35);
  a59=(a59+a45);
  a59=(a59+a43);
  a43=(a32*a59);
  a38=(a38+a43);
  a58=(a58+a38);
  a58=(a02*a58);
  a38=(a29*a39);
  a58=(a58-a38);
  a44=(a08*a44);
  a42=(a25*a42);
  a44=(a44-a42);
  a51=(a13*a51);
  a47=(a07*a47);
  a41=(a41-a47);
  a41=(a00*a41);
  a51=(a51+a41);
  a44=(a44+a51);
  a59=(a59+a59);
  a59=(a12*a59);
  a39=(a34*a39);
  a59=(a59-a39);
  a40=(a36*a40);
  a35=(a11*a35);
  a35=(a35-a52);
  a35=(a32*a35);
  a40=(a40+a35);
  a59=(a59+a40);
  a44=(a44+a59);
  a44=(a02*a44);
  a44=(a01*a44);
  a55=(a33*a55);
  a44=(a44+a55);
  a58=(a58-a44);
  a44=(a28*a58);
  a49=(a49/a16);
  a55=(a37*a53);
  a49=(a49+a55);
  a49=(a30*a49);
  a44=(a44-a49);
  a50=(a50+a44);
  if (res[1]!=0) res[1][10]=a50;
  a57=(a27*a57);
  a48=(a48/a16);
  a50=(a46*a53);
  a48=(a48+a50);
  a48=(a20*a48);
  a57=(a57-a48);
  a58=(a06*a58);
  a53=(a56*a53);
  a53=(a30*a53);
  a58=(a58-a53);
  a57=(a57+a58);
  a57=(-a57);
  if (res[1]!=0) res[1][11]=a57;
  a57=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][12]=a57;
  a58=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][13]=a58;
  a53=(a07*a58);
  a48=(a05*a53);
  a50=arg[1]? arg[1][13] : 0;
  a44=(a04*a50);
  a49=(a21*a44);
  a48=(a48-a49);
  a49=(a03*a58);
  a55=(a04*a49);
  a50=(a05*a50);
  a59=(a23*a50);
  a55=(a55+a59);
  a48=(a48+a55);
  a59=(a48+a48);
  a40=(a02*a59);
  a40=(a01*a40);
  a35=(a26*a58);
  a40=(a40+a35);
  a35=(a10*a40);
  a52=(a03*a44);
  a39=(a07*a50);
  a39=(a52+a39);
  a51=(a09*a39);
  a41=(a39+a39);
  a47=(a08*a41);
  a51=(a51+a47);
  a47=(a11*a44);
  a42=(a03*a50);
  a47=(a47+a42);
  a38=(a14*a47);
  a43=(a47+a47);
  a43=(a12*a43);
  a38=(a38+a43);
  a51=(a51+a38);
  a51=(a02*a51);
  a38=(a51/a16);
  a41=(a02*a41);
  a43=(a19*a41);
  a45=(a18*a39);
  a45=(a02*a45);
  a60=(a17*a45);
  a43=(a43+a60);
  a51=(a15*a51);
  a43=(a43-a51);
  a51=(a54*a43);
  a38=(a38+a51);
  a38=(a20*a38);
  a35=(a35-a38);
  a53=(a04*a53);
  a38=(a21*a50);
  a53=(a53+a38);
  a57=(a57-a53);
  a49=(a05*a49);
  a53=(a23*a44);
  a49=(a49-a53);
  a57=(a57+a49);
  a57=(a57+a57);
  a53=(a22*a57);
  a48=(a00*a48);
  a53=(a53+a48);
  a48=(a11*a58);
  a38=(a05*a48);
  a51=(a31*a44);
  a38=(a38-a51);
  a38=(a38-a55);
  a38=(a38+a38);
  a55=(a24*a38);
  a48=(a04*a48);
  a51=(a31*a50);
  a48=(a48+a51);
  a48=(a48+a49);
  a49=(a32*a48);
  a55=(a55+a49);
  a53=(a53+a55);
  a53=(a02*a53);
  a55=(a29*a47);
  a53=(a53-a55);
  a59=(a08*a59);
  a39=(a25*a39);
  a59=(a59-a39);
  a57=(a13*a57);
  a44=(a07*a44);
  a42=(a42-a44);
  a42=(a00*a42);
  a57=(a57+a42);
  a59=(a59+a57);
  a48=(a48+a48);
  a48=(a12*a48);
  a47=(a34*a47);
  a48=(a48-a47);
  a38=(a36*a38);
  a50=(a11*a50);
  a50=(a50-a52);
  a50=(a32*a50);
  a38=(a38+a50);
  a48=(a48+a38);
  a59=(a59+a48);
  a59=(a02*a59);
  a59=(a01*a59);
  a58=(a33*a58);
  a59=(a59+a58);
  a53=(a53-a59);
  a59=(a28*a53);
  a41=(a41/a16);
  a58=(a37*a43);
  a41=(a41+a58);
  a41=(a30*a41);
  a59=(a59-a41);
  a35=(a35+a59);
  if (res[1]!=0) res[1][14]=a35;
  a40=(a27*a40);
  a45=(a45/a16);
  a35=(a46*a43);
  a45=(a45+a35);
  a45=(a20*a45);
  a40=(a40-a45);
  a53=(a06*a53);
  a43=(a56*a43);
  a43=(a30*a43);
  a53=(a53-a43);
  a40=(a40+a53);
  a40=(-a40);
  if (res[1]!=0) res[1][15]=a40;
  a40=arg[2]? arg[2][2] : 0;
  if (res[2]!=0) res[2][0]=a40;
  a53=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][1]=a53;
  a43=5.;
  a45=(a43*a10);
  a35=(a07*a53);
  a59=(a05*a35);
  a41=arg[2]? arg[2][1] : 0;
  a58=(a04*a41);
  a48=(a21*a58);
  a59=(a59-a48);
  a48=(a03*a53);
  a38=(a04*a48);
  a41=(a05*a41);
  a50=(a23*a41);
  a38=(a38+a50);
  a59=(a59+a38);
  a50=(a59+a59);
  a52=(a02*a50);
  a52=(a01*a52);
  a47=(a26*a53);
  a52=(a52+a47);
  a47=(a10*a52);
  a57=(a03*a58);
  a42=(a07*a41);
  a42=(a57+a42);
  a44=(a09*a42);
  a39=(a42+a42);
  a55=(a08*a39);
  a44=(a44+a55);
  a55=(a11*a58);
  a49=(a03*a41);
  a55=(a55+a49);
  a51=(a14*a55);
  a60=(a55+a55);
  a60=(a12*a60);
  a51=(a51+a60);
  a44=(a44+a51);
  a44=(a02*a44);
  a51=(a44/a16);
  a39=(a02*a39);
  a60=(a19*a39);
  a61=(a18*a42);
  a61=(a02*a61);
  a62=(a17*a61);
  a60=(a60+a62);
  a44=(a15*a44);
  a60=(a60-a44);
  a44=(a54*a60);
  a51=(a51+a44);
  a51=(a20*a51);
  a47=(a47-a51);
  a35=(a04*a35);
  a51=(a21*a41);
  a35=(a35+a51);
  a40=(a40-a35);
  a48=(a05*a48);
  a35=(a23*a58);
  a48=(a48-a35);
  a40=(a40+a48);
  a40=(a40+a40);
  a35=(a22*a40);
  a59=(a00*a59);
  a35=(a35+a59);
  a59=(a11*a53);
  a51=(a05*a59);
  a44=(a31*a58);
  a51=(a51-a44);
  a51=(a51-a38);
  a51=(a51+a51);
  a38=(a24*a51);
  a59=(a04*a59);
  a44=(a31*a41);
  a59=(a59+a44);
  a59=(a59+a48);
  a48=(a32*a59);
  a38=(a38+a48);
  a35=(a35+a38);
  a35=(a02*a35);
  a38=(a29*a55);
  a35=(a35-a38);
  a50=(a08*a50);
  a42=(a25*a42);
  a50=(a50-a42);
  a40=(a13*a40);
  a58=(a07*a58);
  a49=(a49-a58);
  a49=(a00*a49);
  a40=(a40+a49);
  a50=(a50+a40);
  a59=(a59+a59);
  a59=(a12*a59);
  a55=(a34*a55);
  a59=(a59-a55);
  a51=(a36*a51);
  a41=(a11*a41);
  a41=(a41-a57);
  a41=(a32*a41);
  a51=(a51+a41);
  a59=(a59+a51);
  a50=(a50+a59);
  a50=(a02*a50);
  a50=(a01*a50);
  a53=(a33*a53);
  a50=(a50+a53);
  a35=(a35-a50);
  a50=(a28*a35);
  a39=(a39/a16);
  a53=(a37*a60);
  a39=(a39+a53);
  a39=(a30*a39);
  a50=(a50-a39);
  a47=(a47+a50);
  a47=(a45+a47);
  if (res[2]!=0) res[2][2]=a47;
  a43=(a43*a27);
  a52=(a27*a52);
  a61=(a61/a16);
  a47=(a46*a60);
  a61=(a61+a47);
  a61=(a20*a61);
  a52=(a52-a61);
  a35=(a06*a35);
  a60=(a56*a60);
  a60=(a30*a60);
  a35=(a35-a60);
  a52=(a52+a35);
  a52=(a43+a52);
  a52=(-a52);
  if (res[2]!=0) res[2][3]=a52;
  a52=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][4]=a52;
  a35=arg[2]? arg[2][7] : 0;
  if (res[2]!=0) res[2][5]=a35;
  a60=(a07*a35);
  a61=(a05*a60);
  a47=arg[2]? arg[2][5] : 0;
  a50=(a04*a47);
  a39=(a21*a50);
  a61=(a61-a39);
  a39=(a03*a35);
  a53=(a04*a39);
  a47=(a05*a47);
  a59=(a23*a47);
  a53=(a53+a59);
  a61=(a61+a53);
  a59=(a61+a61);
  a51=(a02*a59);
  a51=(a01*a51);
  a26=(a26*a35);
  a51=(a51+a26);
  a10=(a10*a51);
  a26=(a03*a50);
  a41=(a07*a47);
  a41=(a26+a41);
  a09=(a09*a41);
  a57=(a41+a41);
  a55=(a08*a57);
  a09=(a09+a55);
  a55=(a11*a50);
  a03=(a03*a47);
  a55=(a55+a03);
  a14=(a14*a55);
  a40=(a55+a55);
  a40=(a12*a40);
  a14=(a14+a40);
  a09=(a09+a14);
  a09=(a02*a09);
  a14=(a09/a16);
  a57=(a02*a57);
  a19=(a19*a57);
  a18=(a18*a41);
  a18=(a02*a18);
  a17=(a17*a18);
  a19=(a19+a17);
  a15=(a15*a09);
  a19=(a19-a15);
  a54=(a54*a19);
  a14=(a14+a54);
  a14=(a20*a14);
  a10=(a10-a14);
  a60=(a04*a60);
  a21=(a21*a47);
  a60=(a60+a21);
  a52=(a52-a60);
  a39=(a05*a39);
  a23=(a23*a50);
  a39=(a39-a23);
  a52=(a52+a39);
  a52=(a52+a52);
  a22=(a22*a52);
  a61=(a00*a61);
  a22=(a22+a61);
  a61=(a11*a35);
  a05=(a05*a61);
  a23=(a31*a50);
  a05=(a05-a23);
  a05=(a05-a53);
  a05=(a05+a05);
  a24=(a24*a05);
  a04=(a04*a61);
  a31=(a31*a47);
  a04=(a04+a31);
  a04=(a04+a39);
  a39=(a32*a04);
  a24=(a24+a39);
  a22=(a22+a24);
  a22=(a02*a22);
  a29=(a29*a55);
  a22=(a22-a29);
  a08=(a08*a59);
  a25=(a25*a41);
  a08=(a08-a25);
  a13=(a13*a52);
  a07=(a07*a50);
  a03=(a03-a07);
  a00=(a00*a03);
  a13=(a13+a00);
  a08=(a08+a13);
  a04=(a04+a04);
  a12=(a12*a04);
  a34=(a34*a55);
  a12=(a12-a34);
  a36=(a36*a05);
  a11=(a11*a47);
  a11=(a11-a26);
  a32=(a32*a11);
  a36=(a36+a32);
  a12=(a12+a36);
  a08=(a08+a12);
  a02=(a02*a08);
  a01=(a01*a02);
  a33=(a33*a35);
  a01=(a01+a33);
  a22=(a22-a01);
  a28=(a28*a22);
  a57=(a57/a16);
  a37=(a37*a19);
  a57=(a57+a37);
  a57=(a30*a57);
  a28=(a28-a57);
  a10=(a10+a28);
  a45=(a45+a10);
  if (res[2]!=0) res[2][6]=a45;
  a27=(a27*a51);
  a18=(a18/a16);
  a46=(a46*a19);
  a18=(a18+a46);
  a20=(a20*a18);
  a27=(a27-a20);
  a06=(a06*a22);
  a56=(a56*a19);
  a30=(a30*a56);
  a06=(a06-a30);
  a27=(a27+a06);
  a43=(a43+a27);
  a43=(-a43);
  if (res[2]!=0) res[2][7]=a43;
  return 0;
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int simplified_inverted_pendulum_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int simplified_inverted_pendulum_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real simplified_inverted_pendulum_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simplified_inverted_pendulum_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simplified_inverted_pendulum_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simplified_inverted_pendulum_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simplified_inverted_pendulum_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
