/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_simplified_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {6, 1, 1};

/* model_simplified_expl_vde_adj:(i0[4],i1[4],i2[2],i3[4])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a01=sin(a00);
  a02=arg[3]? arg[3][2] : 0;
  a03=9.8100000000000005e+00;
  a04=21.;
  a05=arg[3]? arg[3][0] : 0;
  a04=(a04+a05);
  a03=(a03*a04);
  a05=5.0000000000000000e-01;
  a05=(a05*a04);
  a00=cos(a00);
  a06=arg[3]? arg[3][3] : 0;
  a07=(a00*a06);
  a08=(a01*a02);
  a07=(a07-a08);
  a08=(a07+a07);
  a09=(a05*a08);
  a10=6.;
  a10=(a10+a04);
  a04=(a07*a08);
  a11=(a00*a02);
  a12=(a01*a06);
  a11=(a11+a12);
  a12=(a11+a11);
  a13=(a11*a12);
  a04=(a04+a13);
  a04=(a05*a04);
  a13=arg[3]? arg[3][1] : 0;
  a04=(a04+a13);
  a13=(a10*a04);
  a14=2.;
  a15=(a14*a07);
  a15=(a05*a15);
  a16=(a09*a15);
  a13=(a13-a16);
  a16=(a09/a13);
  a17=arg[1]? arg[1][2] : 0;
  a18=(a16*a17);
  a19=(a10/a13);
  a20=arg[1]? arg[1][3] : 0;
  a21=(a19*a20);
  a18=(a18-a21);
  a21=(a03*a18);
  a22=(a02*a21);
  a22=(a01*a22);
  a21=(a06*a21);
  a21=(a00*a21);
  a22=(a22-a21);
  a21=arg[0]? arg[0][3] : 0;
  a23=(a06*a21);
  a24=arg[0]? arg[0][2] : 0;
  a25=(a02*a21);
  a26=(a25*a01);
  a24=(a24-a26);
  a27=(a23*a00);
  a24=(a24+a27);
  a24=(a24+a24);
  a28=(a05*a18);
  a29=(a24*a28);
  a30=(a23*a29);
  a30=(a00*a30);
  a22=(a22+a30);
  a30=(a25*a29);
  a30=(a01*a30);
  a22=(a22-a30);
  a30=(a25*a00);
  a31=(a23*a01);
  a30=(a30+a31);
  a31=(a30+a30);
  a32=(a31*a28);
  a33=(a25*a32);
  a33=(a00*a33);
  a22=(a22+a33);
  a33=(a23*a32);
  a33=(a01*a33);
  a22=(a22+a33);
  a33=(a21*a18);
  a33=(a05*a33);
  a34=(a31*a33);
  a35=(a02*a34);
  a36=(a11*a33);
  a36=(a36+a36);
  a37=(a25*a36);
  a35=(a35+a37);
  a35=(a00*a35);
  a22=(a22-a35);
  a35=(a06*a34);
  a37=(a23*a36);
  a35=(a35+a37);
  a35=(a01*a35);
  a22=(a22-a35);
  a04=(a04/a13);
  a35=(a04*a17);
  a37=(a15/a13);
  a38=(a37*a20);
  a35=(a35-a38);
  a38=(a21*a35);
  a38=(a05*a38);
  a39=(a07*a33);
  a38=(a38-a39);
  a38=(a38+a38);
  a39=(a23*a38);
  a40=(a24*a33);
  a41=(a06*a40);
  a39=(a39-a41);
  a39=(a00*a39);
  a22=(a22+a39);
  a39=(a25*a38);
  a40=(a02*a40);
  a39=(a39-a40);
  a39=(a01*a39);
  a22=(a22-a39);
  a39=(a06*a00);
  a40=(a02*a01);
  a39=(a39-a40);
  a40=(a39*a33);
  a27=(a27-a26);
  a26=(a27*a28);
  a26=(a26+a26);
  a26=(a40-a26);
  a26=(a26+a40);
  a40=(a23*a26);
  a41=arg[2]? arg[2][0] : 0;
  a42=arg[2]? arg[2][1] : 0;
  a41=(a41+a42);
  a42=2.0000000000000001e-01;
  a41=(a41/a42);
  a42=(a05*a31);
  a43=(a42*a21);
  a41=(a41+a43);
  a43=(a41*a17);
  a44=(a43/a13);
  a19=(a19/a13);
  a45=(a27+a27);
  a46=(a11*a45);
  a39=(a31*a39);
  a46=(a46+a39);
  a39=(a07*a31);
  a47=(a06*a01);
  a48=(a02*a00);
  a47=(a47+a48);
  a48=(a24*a47);
  a39=(a39+a48);
  a46=(a46-a39);
  a46=(a05*a46);
  a21=(a46*a21);
  a31=(a31*a27);
  a24=(a24*a30);
  a31=(a31-a24);
  a31=(a05*a31);
  a03=(a03*a47);
  a31=(a31+a03);
  a21=(a21-a31);
  a31=(a21*a20);
  a19=(a19*a31);
  a37=(a37/a13);
  a41=(a41*a20);
  a37=(a37*a41);
  a19=(a19+a37);
  a16=(a16/a13);
  a21=(a21*a17);
  a16=(a16*a21);
  a19=(a19-a16);
  a04=(a04/a13);
  a04=(a04*a43);
  a19=(a19-a04);
  a10=(a10*a19);
  a44=(a44+a10);
  a44=(a05*a44);
  a11=(a11*a44);
  a11=(a11+a11);
  a10=(a06*a11);
  a40=(a40+a10);
  a45=(a45*a33);
  a12=(a12*a44);
  a45=(a45+a12);
  a12=(a06*a45);
  a40=(a40+a12);
  a40=(a00*a40);
  a22=(a22+a40);
  a40=(a25*a26);
  a11=(a02*a11);
  a40=(a40+a11);
  a45=(a02*a45);
  a40=(a40+a45);
  a40=(a01*a40);
  a22=(a22-a40);
  a30=(a30*a28);
  a30=(a30+a30);
  a47=(a47*a33);
  a30=(a30-a47);
  a30=(a30-a47);
  a25=(a25*a30);
  a21=(a21/a13);
  a15=(a15*a19);
  a21=(a21-a15);
  a21=(a05*a21);
  a07=(a07*a44);
  a21=(a21+a07);
  a21=(a21+a21);
  a07=(a02*a21);
  a25=(a25+a07);
  a08=(a08*a44);
  a41=(a41/a13);
  a09=(a09*a19);
  a41=(a41+a09);
  a05=(a05*a41);
  a14=(a14*a05);
  a34=(a34+a14);
  a08=(a08-a34);
  a34=(a02*a08);
  a25=(a25+a34);
  a25=(a00*a25);
  a22=(a22-a25);
  a23=(a23*a30);
  a21=(a06*a21);
  a23=(a23+a21);
  a08=(a06*a08);
  a23=(a23+a08);
  a23=(a01*a23);
  a22=(a22-a23);
  if (res[0]!=0) res[0][1]=a22;
  a22=arg[1]? arg[1][0] : 0;
  a22=(a30+a22);
  if (res[0]!=0) res[0][2]=a22;
  a46=(a46*a18);
  a18=(a01*a32);
  a22=(a00*a26);
  a18=(a18+a22);
  a22=(a01*a36);
  a18=(a18-a22);
  a18=(a02*a18);
  a46=(a46+a18);
  a26=(a01*a26);
  a32=(a00*a32);
  a26=(a26-a32);
  a36=(a00*a36);
  a26=(a26+a36);
  a26=(a06*a26);
  a46=(a46+a26);
  a42=(a42*a35);
  a46=(a46+a42);
  a42=(a01*a29);
  a26=(a00*a30);
  a42=(a42+a26);
  a26=(a01*a38);
  a42=(a42+a26);
  a06=(a06*a42);
  a46=(a46+a06);
  a29=(a00*a29);
  a01=(a01*a30);
  a29=(a29-a01);
  a00=(a00*a38);
  a29=(a29+a00);
  a02=(a02*a29);
  a46=(a46+a02);
  a02=arg[1]? arg[1][1] : 0;
  a46=(a46+a02);
  if (res[0]!=0) res[0][3]=a46;
  a46=5.;
  a46=(a46*a35);
  if (res[0]!=0) res[0][4]=a46;
  if (res[0]!=0) res[0][5]=a46;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_simplified_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_simplified_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_simplified_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int model_simplified_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real model_simplified_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_simplified_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_simplified_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_simplified_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
