/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheeled_brick_2d_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {7, 7, 1};
static const casadi_int casadi_s2[3] = {7, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};

/* wheeled_brick_2d_expl_vde_forw:(i0[7],i1[7x7],i2[7x2],i3[2],i4[])->(o0[7],o1[7x7],o2[7x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27;
  a00=arg[0]? arg[0][4] : 0;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  if (res[0]!=0) res[0][0]=a03;
  a01=sin(a01);
  a03=(a00*a01);
  if (res[0]!=0) res[0][1]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a03;
  a03=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a04=6.1866666666666665e+00;
  a05=1.1754666666666667e+02;
  a06=8.;
  a07=arg[0]? arg[0][3] : 0;
  a08=cos(a07);
  a09=(a06*a08);
  a10=casadi_sq(a09);
  a05=(a05-a10);
  a04=(a04/a05);
  a10=casadi_sq(a03);
  a10=(a06*a10);
  a07=sin(a07);
  a11=(a10*a07);
  a12=arg[3]? arg[3][0] : 0;
  a13=arg[3]? arg[3][1] : 0;
  a14=(a12+a13);
  a15=2.0000000000000001e-01;
  a14=(a14/a15);
  a11=(a11+a14);
  a14=(a04*a11);
  a15=(a09/a05);
  a16=7.8480000000000004e+01;
  a17=(a16*a07);
  a18=(a15*a17);
  a14=(a14-a18);
  if (res[0]!=0) res[0][4]=a14;
  a14=1.4999999999999998e+00;
  a13=(a13-a12);
  a14=(a14*a13);
  a13=1.4066666666666670e+00;
  a14=(a14/a13);
  if (res[0]!=0) res[0][5]=a14;
  a14=19.;
  a14=(a14/a05);
  a13=(a14*a17);
  a12=(a15*a11);
  a13=(a13-a12);
  if (res[0]!=0) res[0][6]=a13;
  a13=arg[1]? arg[1][4] : 0;
  a12=(a02*a13);
  a18=arg[1]? arg[1][2] : 0;
  a19=(a01*a18);
  a19=(a00*a19);
  a12=(a12-a19);
  if (res[1]!=0) res[1][0]=a12;
  a13=(a01*a13);
  a18=(a02*a18);
  a18=(a00*a18);
  a13=(a13+a18);
  if (res[1]!=0) res[1][1]=a13;
  a13=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a13;
  a13=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][3]=a13;
  a03=(a03+a03);
  a13=(a03*a13);
  a13=(a06*a13);
  a13=(a07*a13);
  a18=arg[1]? arg[1][3] : 0;
  a12=(a08*a18);
  a19=(a10*a12);
  a13=(a13+a19);
  a19=(a04*a13);
  a20=(a04/a05);
  a09=(a09+a09);
  a18=(a07*a18);
  a18=(a06*a18);
  a21=(a09*a18);
  a22=(a20*a21);
  a22=(a11*a22);
  a19=(a19-a22);
  a12=(a16*a12);
  a22=(a15*a12);
  a18=(a18/a05);
  a23=(a15/a05);
  a24=(a23*a21);
  a18=(a18+a24);
  a24=(a17*a18);
  a22=(a22-a24);
  a19=(a19-a22);
  if (res[1]!=0) res[1][4]=a19;
  a19=0.;
  if (res[1]!=0) res[1][5]=a19;
  a12=(a14*a12);
  a22=(a14/a05);
  a21=(a22*a21);
  a21=(a17*a21);
  a12=(a12-a21);
  a13=(a15*a13);
  a18=(a11*a18);
  a13=(a13-a18);
  a12=(a12-a13);
  if (res[1]!=0) res[1][6]=a12;
  a12=arg[1]? arg[1][11] : 0;
  a13=(a02*a12);
  a18=arg[1]? arg[1][9] : 0;
  a21=(a01*a18);
  a21=(a00*a21);
  a13=(a13-a21);
  if (res[1]!=0) res[1][7]=a13;
  a12=(a01*a12);
  a18=(a02*a18);
  a18=(a00*a18);
  a12=(a12+a18);
  if (res[1]!=0) res[1][8]=a12;
  a12=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][9]=a12;
  a12=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][10]=a12;
  a12=(a03*a12);
  a12=(a06*a12);
  a12=(a07*a12);
  a18=arg[1]? arg[1][10] : 0;
  a13=(a08*a18);
  a21=(a10*a13);
  a12=(a12+a21);
  a21=(a04*a12);
  a18=(a07*a18);
  a18=(a06*a18);
  a24=(a09*a18);
  a25=(a20*a24);
  a25=(a11*a25);
  a21=(a21-a25);
  a13=(a16*a13);
  a25=(a15*a13);
  a18=(a18/a05);
  a26=(a23*a24);
  a18=(a18+a26);
  a26=(a17*a18);
  a25=(a25-a26);
  a21=(a21-a25);
  if (res[1]!=0) res[1][11]=a21;
  if (res[1]!=0) res[1][12]=a19;
  a13=(a14*a13);
  a24=(a22*a24);
  a24=(a17*a24);
  a13=(a13-a24);
  a12=(a15*a12);
  a18=(a11*a18);
  a12=(a12-a18);
  a13=(a13-a12);
  if (res[1]!=0) res[1][13]=a13;
  a13=arg[1]? arg[1][18] : 0;
  a12=(a02*a13);
  a18=arg[1]? arg[1][16] : 0;
  a24=(a01*a18);
  a24=(a00*a24);
  a12=(a12-a24);
  if (res[1]!=0) res[1][14]=a12;
  a13=(a01*a13);
  a18=(a02*a18);
  a18=(a00*a18);
  a13=(a13+a18);
  if (res[1]!=0) res[1][15]=a13;
  a13=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][16]=a13;
  a13=arg[1]? arg[1][20] : 0;
  if (res[1]!=0) res[1][17]=a13;
  a13=(a03*a13);
  a13=(a06*a13);
  a13=(a07*a13);
  a18=arg[1]? arg[1][17] : 0;
  a12=(a08*a18);
  a24=(a10*a12);
  a13=(a13+a24);
  a24=(a04*a13);
  a18=(a07*a18);
  a18=(a06*a18);
  a21=(a09*a18);
  a25=(a20*a21);
  a25=(a11*a25);
  a24=(a24-a25);
  a12=(a16*a12);
  a25=(a15*a12);
  a18=(a18/a05);
  a26=(a23*a21);
  a18=(a18+a26);
  a26=(a17*a18);
  a25=(a25-a26);
  a24=(a24-a25);
  if (res[1]!=0) res[1][18]=a24;
  if (res[1]!=0) res[1][19]=a19;
  a12=(a14*a12);
  a21=(a22*a21);
  a21=(a17*a21);
  a12=(a12-a21);
  a13=(a15*a13);
  a18=(a11*a18);
  a13=(a13-a18);
  a12=(a12-a13);
  if (res[1]!=0) res[1][20]=a12;
  a12=arg[1]? arg[1][25] : 0;
  a13=(a02*a12);
  a18=arg[1]? arg[1][23] : 0;
  a21=(a01*a18);
  a21=(a00*a21);
  a13=(a13-a21);
  if (res[1]!=0) res[1][21]=a13;
  a12=(a01*a12);
  a18=(a02*a18);
  a18=(a00*a18);
  a12=(a12+a18);
  if (res[1]!=0) res[1][22]=a12;
  a12=arg[1]? arg[1][26] : 0;
  if (res[1]!=0) res[1][23]=a12;
  a12=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][24]=a12;
  a12=(a03*a12);
  a12=(a06*a12);
  a12=(a07*a12);
  a18=arg[1]? arg[1][24] : 0;
  a13=(a08*a18);
  a21=(a10*a13);
  a12=(a12+a21);
  a21=(a04*a12);
  a18=(a07*a18);
  a18=(a06*a18);
  a24=(a09*a18);
  a25=(a20*a24);
  a25=(a11*a25);
  a21=(a21-a25);
  a13=(a16*a13);
  a25=(a15*a13);
  a18=(a18/a05);
  a26=(a23*a24);
  a18=(a18+a26);
  a26=(a17*a18);
  a25=(a25-a26);
  a21=(a21-a25);
  if (res[1]!=0) res[1][25]=a21;
  if (res[1]!=0) res[1][26]=a19;
  a13=(a14*a13);
  a24=(a22*a24);
  a24=(a17*a24);
  a13=(a13-a24);
  a12=(a15*a12);
  a18=(a11*a18);
  a12=(a12-a18);
  a13=(a13-a12);
  if (res[1]!=0) res[1][27]=a13;
  a13=arg[1]? arg[1][32] : 0;
  a12=(a02*a13);
  a18=arg[1]? arg[1][30] : 0;
  a24=(a01*a18);
  a24=(a00*a24);
  a12=(a12-a24);
  if (res[1]!=0) res[1][28]=a12;
  a13=(a01*a13);
  a18=(a02*a18);
  a18=(a00*a18);
  a13=(a13+a18);
  if (res[1]!=0) res[1][29]=a13;
  a13=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][30]=a13;
  a13=arg[1]? arg[1][34] : 0;
  if (res[1]!=0) res[1][31]=a13;
  a13=(a03*a13);
  a13=(a06*a13);
  a13=(a07*a13);
  a18=arg[1]? arg[1][31] : 0;
  a12=(a08*a18);
  a24=(a10*a12);
  a13=(a13+a24);
  a24=(a04*a13);
  a18=(a07*a18);
  a18=(a06*a18);
  a21=(a09*a18);
  a25=(a20*a21);
  a25=(a11*a25);
  a24=(a24-a25);
  a12=(a16*a12);
  a25=(a15*a12);
  a18=(a18/a05);
  a26=(a23*a21);
  a18=(a18+a26);
  a26=(a17*a18);
  a25=(a25-a26);
  a24=(a24-a25);
  if (res[1]!=0) res[1][32]=a24;
  if (res[1]!=0) res[1][33]=a19;
  a12=(a14*a12);
  a21=(a22*a21);
  a21=(a17*a21);
  a12=(a12-a21);
  a13=(a15*a13);
  a18=(a11*a18);
  a13=(a13-a18);
  a12=(a12-a13);
  if (res[1]!=0) res[1][34]=a12;
  a12=arg[1]? arg[1][39] : 0;
  a13=(a02*a12);
  a18=arg[1]? arg[1][37] : 0;
  a21=(a01*a18);
  a21=(a00*a21);
  a13=(a13-a21);
  if (res[1]!=0) res[1][35]=a13;
  a12=(a01*a12);
  a18=(a02*a18);
  a18=(a00*a18);
  a12=(a12+a18);
  if (res[1]!=0) res[1][36]=a12;
  a12=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][37]=a12;
  a12=arg[1]? arg[1][41] : 0;
  if (res[1]!=0) res[1][38]=a12;
  a12=(a03*a12);
  a12=(a06*a12);
  a12=(a07*a12);
  a18=arg[1]? arg[1][38] : 0;
  a13=(a08*a18);
  a21=(a10*a13);
  a12=(a12+a21);
  a21=(a04*a12);
  a18=(a07*a18);
  a18=(a06*a18);
  a24=(a09*a18);
  a25=(a20*a24);
  a25=(a11*a25);
  a21=(a21-a25);
  a13=(a16*a13);
  a25=(a15*a13);
  a18=(a18/a05);
  a26=(a23*a24);
  a18=(a18+a26);
  a26=(a17*a18);
  a25=(a25-a26);
  a21=(a21-a25);
  if (res[1]!=0) res[1][39]=a21;
  if (res[1]!=0) res[1][40]=a19;
  a13=(a14*a13);
  a24=(a22*a24);
  a24=(a17*a24);
  a13=(a13-a24);
  a12=(a15*a12);
  a18=(a11*a18);
  a12=(a12-a18);
  a13=(a13-a12);
  if (res[1]!=0) res[1][41]=a13;
  a13=arg[1]? arg[1][46] : 0;
  a12=(a02*a13);
  a18=arg[1]? arg[1][44] : 0;
  a24=(a01*a18);
  a24=(a00*a24);
  a12=(a12-a24);
  if (res[1]!=0) res[1][42]=a12;
  a13=(a01*a13);
  a18=(a02*a18);
  a18=(a00*a18);
  a13=(a13+a18);
  if (res[1]!=0) res[1][43]=a13;
  a13=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][44]=a13;
  a13=arg[1]? arg[1][48] : 0;
  if (res[1]!=0) res[1][45]=a13;
  a13=(a03*a13);
  a13=(a06*a13);
  a13=(a07*a13);
  a18=arg[1]? arg[1][45] : 0;
  a12=(a08*a18);
  a24=(a10*a12);
  a13=(a13+a24);
  a24=(a04*a13);
  a18=(a07*a18);
  a18=(a06*a18);
  a21=(a09*a18);
  a25=(a20*a21);
  a25=(a11*a25);
  a24=(a24-a25);
  a12=(a16*a12);
  a25=(a15*a12);
  a18=(a18/a05);
  a26=(a23*a21);
  a18=(a18+a26);
  a26=(a17*a18);
  a25=(a25-a26);
  a24=(a24-a25);
  if (res[1]!=0) res[1][46]=a24;
  if (res[1]!=0) res[1][47]=a19;
  a12=(a14*a12);
  a21=(a22*a21);
  a21=(a17*a21);
  a12=(a12-a21);
  a13=(a15*a13);
  a18=(a11*a18);
  a13=(a13-a18);
  a12=(a12-a13);
  if (res[1]!=0) res[1][48]=a12;
  a12=arg[2]? arg[2][4] : 0;
  a13=(a02*a12);
  a18=arg[2]? arg[2][2] : 0;
  a21=(a01*a18);
  a21=(a00*a21);
  a13=(a13-a21);
  if (res[2]!=0) res[2][0]=a13;
  a12=(a01*a12);
  a18=(a02*a18);
  a18=(a00*a18);
  a12=(a12+a18);
  if (res[2]!=0) res[2][1]=a12;
  a12=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a12;
  a12=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][3]=a12;
  a18=5.;
  a13=(a18*a04);
  a12=(a03*a12);
  a12=(a06*a12);
  a12=(a07*a12);
  a21=arg[2]? arg[2][3] : 0;
  a19=(a08*a21);
  a24=(a10*a19);
  a12=(a12+a24);
  a24=(a04*a12);
  a21=(a07*a21);
  a21=(a06*a21);
  a25=(a09*a21);
  a26=(a20*a25);
  a26=(a11*a26);
  a24=(a24-a26);
  a19=(a16*a19);
  a26=(a15*a19);
  a21=(a21/a05);
  a27=(a23*a25);
  a21=(a21+a27);
  a27=(a17*a21);
  a26=(a26-a27);
  a24=(a24-a26);
  a24=(a13+a24);
  if (res[2]!=0) res[2][4]=a24;
  a24=-1.0663507109004737e+00;
  if (res[2]!=0) res[2][5]=a24;
  a19=(a14*a19);
  a25=(a22*a25);
  a25=(a17*a25);
  a19=(a19-a25);
  a12=(a15*a12);
  a21=(a11*a21);
  a12=(a12-a21);
  a19=(a19-a12);
  a18=(a18*a15);
  a19=(a19-a18);
  if (res[2]!=0) res[2][6]=a19;
  a19=arg[2]? arg[2][11] : 0;
  a12=(a02*a19);
  a21=arg[2]? arg[2][9] : 0;
  a25=(a01*a21);
  a25=(a00*a25);
  a12=(a12-a25);
  if (res[2]!=0) res[2][7]=a12;
  a01=(a01*a19);
  a02=(a02*a21);
  a00=(a00*a02);
  a01=(a01+a00);
  if (res[2]!=0) res[2][8]=a01;
  a01=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][9]=a01;
  a01=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][10]=a01;
  a03=(a03*a01);
  a03=(a06*a03);
  a03=(a07*a03);
  a01=arg[2]? arg[2][10] : 0;
  a08=(a08*a01);
  a10=(a10*a08);
  a03=(a03+a10);
  a04=(a04*a03);
  a07=(a07*a01);
  a06=(a06*a07);
  a09=(a09*a06);
  a20=(a20*a09);
  a20=(a11*a20);
  a04=(a04-a20);
  a16=(a16*a08);
  a08=(a15*a16);
  a06=(a06/a05);
  a23=(a23*a09);
  a06=(a06+a23);
  a23=(a17*a06);
  a08=(a08-a23);
  a04=(a04-a08);
  a13=(a13+a04);
  if (res[2]!=0) res[2][11]=a13;
  a13=1.0663507109004737e+00;
  if (res[2]!=0) res[2][12]=a13;
  a14=(a14*a16);
  a22=(a22*a09);
  a17=(a17*a22);
  a14=(a14-a17);
  a15=(a15*a03);
  a11=(a11*a06);
  a15=(a15-a11);
  a14=(a14-a15);
  a14=(a14-a18);
  if (res[2]!=0) res[2][13]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2d_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2d_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2d_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2d_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2d_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2d_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2d_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2d_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_2d_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_2d_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real wheeled_brick_2d_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_2d_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_2d_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_2d_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_2d_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2d_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2d_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
