/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mass_matrix_casadi_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {19, 1, 1};
static const casadi_int casadi_s2[3] = {4, 4, 1};
static const casadi_int casadi_s3[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[23] = 
  {19, 1, 0, 19, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s5[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};

/* mass_matrix:(q[4],params[19])->(M[4x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30;
  a00=2.;
  a01=arg[1]? arg[1][2] : 0;
  a01=(a00*a01);
  a02=5.0000000000000000e-01;
  a03=arg[1]? arg[1][7] : 0;
  a03=(a02*a03);
  a04=arg[1]? arg[1][0] : 0;
  a05=(1./a04);
  a05=(a05+a05);
  a05=(a05/a04);
  a03=(a03*a05);
  a03=(a00*a03);
  a01=(a01+a03);
  a03=arg[1]? arg[1][3] : 0;
  a01=(a01+a03);
  a05=arg[1]? arg[1][4] : 0;
  a01=(a01+a05);
  a04=arg[1]? arg[1][5] : 0;
  a01=(a01+a04);
  a06=arg[1]? arg[1][6] : 0;
  a01=(a01+a06);
  if (res[0]!=0) res[0][0]=a01;
  a03=(a02*a03);
  a01=arg[0]? arg[0][1] : 0;
  a07=cos(a01);
  a08=arg[1]? arg[1][13] : 0;
  a09=(a07*a08);
  a10=sin(a01);
  a11=arg[1]? arg[1][12] : 0;
  a12=(a10*a11);
  a09=(a09-a12);
  a09=(a09+a09);
  a09=(a03*a09);
  a05=(a02*a05);
  a12=cos(a01);
  a13=arg[1]? arg[1][15] : 0;
  a14=(a12*a13);
  a15=sin(a01);
  a16=arg[1]? arg[1][14] : 0;
  a17=(a15*a16);
  a14=(a14-a17);
  a14=(a14+a14);
  a14=(a05*a14);
  a09=(a09+a14);
  a04=(a02*a04);
  a14=cos(a01);
  a17=arg[1]? arg[1][17] : 0;
  a18=arg[0]? arg[0][2] : 0;
  a19=(a17+a18);
  a20=(a14*a19);
  a21=sin(a01);
  a22=arg[1]? arg[1][16] : 0;
  a23=(a21*a22);
  a20=(a20-a23);
  a20=(a20+a20);
  a20=(a04*a20);
  a09=(a09+a20);
  a02=(a02*a06);
  a06=cos(a01);
  a20=(a17+a18);
  a23=(a06*a20);
  a24=sin(a01);
  a25=(a24*a22);
  a23=(a23-a25);
  a25=arg[1]? arg[1][18] : 0;
  a26=arg[0]? arg[0][3] : 0;
  a27=(a01+a26);
  a27=sin(a27);
  a27=(a25*a27);
  a23=(a23-a27);
  a23=(a23+a23);
  a23=(a02*a23);
  a09=(a09+a23);
  if (res[0]!=0) res[0][1]=a09;
  a09=sin(a01);
  a23=(a09+a09);
  a23=(a04*a23);
  a28=sin(a01);
  a29=(a28+a28);
  a29=(a02*a29);
  a23=(a23+a29);
  if (res[0]!=0) res[0][2]=a23;
  a23=(a27+a27);
  a23=(a02*a23);
  a23=(-a23);
  if (res[0]!=0) res[0][3]=a23;
  a23=(a07*a08);
  a29=(a10*a11);
  a23=(a23-a29);
  a23=(a00*a23);
  a23=(a03*a23);
  a29=(a12*a13);
  a30=(a15*a16);
  a29=(a29-a30);
  a29=(a00*a29);
  a29=(a05*a29);
  a23=(a23+a29);
  a29=(a14*a19);
  a30=(a21*a22);
  a29=(a29-a30);
  a29=(a00*a29);
  a29=(a04*a29);
  a23=(a23+a29);
  a29=(a06*a20);
  a30=(a24*a22);
  a29=(a29-a30);
  a29=(a29-a27);
  a29=(a00*a29);
  a29=(a02*a29);
  a23=(a23+a29);
  if (res[0]!=0) res[0][4]=a23;
  a23=(a07*a08);
  a29=(a10*a11);
  a23=(a23-a29);
  a07=(a07*a08);
  a10=(a10*a11);
  a07=(a07-a10);
  a07=(a07+a07);
  a23=(a23*a07);
  a07=cos(a01);
  a10=(a07*a11);
  a29=sin(a01);
  a30=(a29*a08);
  a10=(a10+a30);
  a07=(a07*a11);
  a29=(a29*a08);
  a07=(a07+a29);
  a07=(a07+a07);
  a10=(a10*a07);
  a23=(a23+a10);
  a03=(a03*a23);
  a23=arg[1]? arg[1][8] : 0;
  a03=(a03+a23);
  a23=(a12*a13);
  a10=(a15*a16);
  a23=(a23-a10);
  a12=(a12*a13);
  a15=(a15*a16);
  a12=(a12-a15);
  a12=(a12+a12);
  a23=(a23*a12);
  a12=cos(a01);
  a15=(a12*a16);
  a10=sin(a01);
  a07=(a10*a13);
  a15=(a15+a07);
  a12=(a12*a16);
  a10=(a10*a13);
  a12=(a12+a10);
  a12=(a12+a12);
  a15=(a15*a12);
  a23=(a23+a15);
  a05=(a05*a23);
  a03=(a03+a05);
  a05=arg[1]? arg[1][9] : 0;
  a03=(a03+a05);
  a05=(a14*a19);
  a23=(a21*a22);
  a05=(a05-a23);
  a23=(a14*a19);
  a15=(a21*a22);
  a23=(a23-a15);
  a23=(a23+a23);
  a05=(a05*a23);
  a23=cos(a01);
  a15=(a23*a22);
  a12=sin(a01);
  a10=(a17+a18);
  a13=(a12*a10);
  a15=(a15+a13);
  a13=(a23*a22);
  a16=(a12*a10);
  a13=(a13+a16);
  a13=(a13+a13);
  a15=(a15*a13);
  a05=(a05+a15);
  a05=(a04*a05);
  a03=(a03+a05);
  a05=arg[1]? arg[1][10] : 0;
  a03=(a03+a05);
  a05=(a06*a20);
  a15=(a24*a22);
  a05=(a05-a15);
  a05=(a05-a27);
  a15=(a06*a20);
  a13=(a24*a22);
  a15=(a15-a13);
  a15=(a15-a27);
  a15=(a15+a15);
  a05=(a05*a15);
  a15=cos(a01);
  a13=(a15*a22);
  a16=sin(a01);
  a17=(a17+a18);
  a18=(a16*a17);
  a13=(a13+a18);
  a26=(a01+a26);
  a26=cos(a26);
  a25=(a25*a26);
  a13=(a13+a25);
  a26=(a15*a22);
  a18=(a16*a17);
  a26=(a26+a18);
  a26=(a26+a25);
  a26=(a26+a26);
  a13=(a13*a26);
  a05=(a05+a13);
  a05=(a02*a05);
  a03=(a03+a05);
  a05=arg[1]? arg[1][11] : 0;
  a03=(a03+a05);
  if (res[0]!=0) res[0][5]=a03;
  a03=(a14*a19);
  a13=(a21*a22);
  a03=(a03-a13);
  a13=(a09+a09);
  a03=(a03*a13);
  a13=(a23*a22);
  a26=(a12*a10);
  a13=(a13+a26);
  a26=cos(a01);
  a18=(a26+a26);
  a13=(a13*a18);
  a03=(a03-a13);
  a03=(a04*a03);
  a13=(a06*a20);
  a18=(a24*a22);
  a13=(a13-a18);
  a13=(a13-a27);
  a18=(a28+a28);
  a13=(a13*a18);
  a18=(a15*a22);
  a07=(a16*a17);
  a18=(a18+a07);
  a18=(a18+a25);
  a01=cos(a01);
  a07=(a01+a01);
  a18=(a18*a07);
  a13=(a13-a18);
  a13=(a02*a13);
  a03=(a03+a13);
  if (res[0]!=0) res[0][6]=a03;
  a03=(a15*a22);
  a13=(a16*a17);
  a03=(a03+a13);
  a03=(a03+a25);
  a13=(a25+a25);
  a03=(a03*a13);
  a13=(a06*a20);
  a18=(a24*a22);
  a13=(a13-a18);
  a13=(a13-a27);
  a18=(a27+a27);
  a13=(a13*a18);
  a03=(a03-a13);
  a03=(a02*a03);
  a03=(a03+a05);
  if (res[0]!=0) res[0][7]=a03;
  a03=(a00*a09);
  a03=(a04*a03);
  a13=(a00*a28);
  a13=(a02*a13);
  a03=(a03+a13);
  if (res[0]!=0) res[0][8]=a03;
  a14=(a14*a19);
  a21=(a21*a22);
  a14=(a14-a21);
  a14=(a14+a14);
  a14=(a09*a14);
  a23=(a23*a22);
  a12=(a12*a10);
  a23=(a23+a12);
  a23=(a23+a23);
  a23=(a26*a23);
  a14=(a14-a23);
  a14=(a04*a14);
  a23=(a06*a20);
  a12=(a24*a22);
  a23=(a23-a12);
  a23=(a23-a27);
  a23=(a23+a23);
  a23=(a28*a23);
  a12=(a15*a22);
  a10=(a16*a17);
  a12=(a12+a10);
  a12=(a12+a25);
  a12=(a12+a12);
  a12=(a01*a12);
  a23=(a23-a12);
  a23=(a02*a23);
  a14=(a14+a23);
  if (res[0]!=0) res[0][9]=a14;
  a14=(a09+a09);
  a09=(a09*a14);
  a14=(a26+a26);
  a26=(a26*a14);
  a09=(a09+a26);
  a04=(a04*a09);
  a09=(a28+a28);
  a09=(a28*a09);
  a26=(a01+a01);
  a26=(a01*a26);
  a09=(a09+a26);
  a09=(a02*a09);
  a04=(a04+a09);
  if (res[0]!=0) res[0][10]=a04;
  a04=(a27+a27);
  a04=(a28*a04);
  a09=(a25+a25);
  a09=(a01*a09);
  a04=(a04+a09);
  a04=(a02*a04);
  a04=(-a04);
  if (res[0]!=0) res[0][11]=a04;
  a00=(a00*a27);
  a00=(a02*a00);
  a00=(-a00);
  if (res[0]!=0) res[0][12]=a00;
  a06=(a06*a20);
  a24=(a24*a22);
  a06=(a06-a24);
  a06=(a06-a27);
  a06=(a06+a06);
  a06=(a27*a06);
  a15=(a15*a22);
  a16=(a16*a17);
  a15=(a15+a16);
  a15=(a15+a25);
  a15=(a15+a15);
  a15=(a25*a15);
  a06=(a06-a15);
  a06=(a02*a06);
  a06=(a05-a06);
  if (res[0]!=0) res[0][13]=a06;
  a28=(a28+a28);
  a28=(a27*a28);
  a01=(a01+a01);
  a01=(a25*a01);
  a28=(a28+a01);
  a28=(a02*a28);
  a28=(-a28);
  if (res[0]!=0) res[0][14]=a28;
  a28=(a27+a27);
  a27=(a27*a28);
  a28=(a25+a25);
  a25=(a25*a28);
  a27=(a27+a25);
  a02=(a02*a27);
  a05=(a05+a02);
  if (res[0]!=0) res[0][15]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int mass_matrix(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mass_matrix_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mass_matrix_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mass_matrix_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mass_matrix_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mass_matrix_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mass_matrix_incref(void) {
}

CASADI_SYMBOL_EXPORT void mass_matrix_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mass_matrix_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int mass_matrix_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mass_matrix_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mass_matrix_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    case 1: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mass_matrix_name_out(casadi_int i) {
  switch (i) {
    case 0: return "M";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mass_matrix_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mass_matrix_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mass_matrix_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mass_matrix_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_mass_matrix(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[70];
  casadi_int *iw = 0;
  const casadi_real* arg[2] = {0};
  casadi_real* res[1] = {0};
  if (argc>2) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"mass_matrix\" failed. Too many input arguments (%d, max 2)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"mass_matrix\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s3, w+39);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+4, casadi_s4, w+39);
  --resc;
  res[0] = w+23;
  mass_matrix_incref();
  mem = mass_matrix_checkout();
  i = mass_matrix(arg, res, iw, w+39, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"mass_matrix\" failed.");
  mass_matrix_release(mem);
  mass_matrix_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s5, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[12];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_mass_matrix(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "mass_matrix")==0) {
    mex_mass_matrix(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'mass_matrix'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
