/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) simplified_inverted_pendulum_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {6, 1, 1};

/* simplified_inverted_pendulum_expl_vde_adj:(i0[4],i1[4],i2[2],i3[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a01=sin(a00);
  a02=8.7500000000000000e-01;
  a03=2.3199999999999998e-02;
  a04=arg[0]? arg[0][3] : 0;
  a05=(a03*a04);
  a00=cos(a00);
  a06=(a05*a00);
  a07=(a02*a04);
  a08=(a07*a01);
  a06=(a06-a08);
  a06=(a06+a06);
  a09=1.0500000000000000e+01;
  a10=(a02*a00);
  a11=-2.3199999999999998e-02;
  a12=(a11*a01);
  a12=(a10-a12);
  a13=(a12+a12);
  a14=(a09*a13);
  a15=27.;
  a16=(a12*a13);
  a17=(a03*a00);
  a18=(a02*a01);
  a17=(a17-a18);
  a19=(a17+a17);
  a20=(a17*a19);
  a16=(a16+a20);
  a16=(a09*a16);
  a20=8.4100000000000001e+00;
  a16=(a16+a20);
  a20=(a15*a16);
  a21=2.;
  a22=(a21*a12);
  a22=(a09*a22);
  a23=(a14*a22);
  a20=(a20-a23);
  a23=(a14/a20);
  a24=arg[1]? arg[1][2] : 0;
  a25=(a23*a24);
  a26=(a15/a20);
  a27=arg[1]? arg[1][3] : 0;
  a28=(a26*a27);
  a25=(a25-a28);
  a28=(a04*a25);
  a28=(a09*a28);
  a29=(a06*a28);
  a30=(a02*a29);
  a31=(a17*a28);
  a31=(a31+a31);
  a32=(a07*a31);
  a30=(a30+a32);
  a30=(a01*a30);
  a29=(a03*a29);
  a32=(a05*a31);
  a29=(a29+a32);
  a29=(a00*a29);
  a30=(a30-a29);
  a29=2.0601000000000002e+02;
  a32=(a29*a25);
  a33=(a02*a32);
  a33=(a00*a33);
  a30=(a30-a33);
  a32=(a03*a32);
  a32=(a01*a32);
  a30=(a30-a32);
  a32=(a09*a25);
  a33=(a06*a32);
  a34=(a07*a33);
  a34=(a01*a34);
  a30=(a30-a34);
  a34=(a05*a33);
  a34=(a00*a34);
  a30=(a30+a34);
  a34=arg[0]? arg[0][2] : 0;
  a35=(a11*a04);
  a36=(a35*a01);
  a34=(a34-a36);
  a36=(a07*a00);
  a34=(a34+a36);
  a34=(a34+a34);
  a37=(a34*a32);
  a38=(a07*a37);
  a38=(a00*a38);
  a30=(a30+a38);
  a38=(a35*a37);
  a38=(a01*a38);
  a30=(a30-a38);
  a16=(a16/a20);
  a38=(a16*a24);
  a39=(a22/a20);
  a40=(a39*a27);
  a38=(a38-a40);
  a40=(a04*a38);
  a40=(a09*a40);
  a41=(a12*a28);
  a40=(a40-a41);
  a40=(a40+a40);
  a41=(a07*a40);
  a42=(a34*a28);
  a43=(a02*a42);
  a41=(a41-a43);
  a41=(a00*a41);
  a30=(a30+a41);
  a41=(a35*a40);
  a42=(a11*a42);
  a41=(a41-a42);
  a41=(a01*a41);
  a30=(a30-a41);
  a41=(a05*a01);
  a41=(a41+a36);
  a36=(a41*a32);
  a42=(a03*a01);
  a42=(a42+a10);
  a10=(a42*a28);
  a10=(a10+a10);
  a10=(a36-a10);
  a10=(a10+a36);
  a36=(a07*a10);
  a43=arg[2]? arg[2][0] : 0;
  a44=arg[2]? arg[2][1] : 0;
  a43=(a43+a44);
  a44=2.0000000000000001e-01;
  a43=(a43/a44);
  a44=(a35*a00);
  a44=(a44+a08);
  a08=(a44+a44);
  a45=(a09*a08);
  a46=(a45*a04);
  a43=(a43+a46);
  a46=(a43*a24);
  a47=(a46/a20);
  a26=(a26/a20);
  a48=(a34*a44);
  a49=(a06*a41);
  a48=(a48+a49);
  a48=(a09*a48);
  a29=(a29*a17);
  a48=(a48+a29);
  a29=(a12*a08);
  a49=(a11*a00);
  a18=(a18+a49);
  a34=(a34*a18);
  a29=(a29+a34);
  a41=(a41+a41);
  a34=(a17*a41);
  a06=(a06*a42);
  a34=(a34+a06);
  a29=(a29+a34);
  a29=(a09*a29);
  a04=(a29*a04);
  a48=(a48-a04);
  a04=(a48*a27);
  a26=(a26*a04);
  a39=(a39/a20);
  a43=(a43*a27);
  a39=(a39*a43);
  a26=(a26+a39);
  a23=(a23/a20);
  a48=(a48*a24);
  a23=(a23*a48);
  a26=(a26-a23);
  a16=(a16/a20);
  a16=(a16*a46);
  a26=(a26-a16);
  a15=(a15*a26);
  a47=(a47+a15);
  a47=(a09*a47);
  a17=(a17*a47);
  a17=(a17+a17);
  a15=(a02*a17);
  a36=(a36+a15);
  a19=(a19*a47);
  a41=(a41*a28);
  a19=(a19-a41);
  a41=(a02*a19);
  a36=(a36+a41);
  a36=(a00*a36);
  a30=(a30-a36);
  a05=(a05*a10);
  a17=(a03*a17);
  a05=(a05+a17);
  a19=(a03*a19);
  a05=(a05+a19);
  a05=(a01*a05);
  a30=(a30-a05);
  a44=(a44*a32);
  a18=(a18*a28);
  a18=(a18+a18);
  a18=(a44-a18);
  a18=(a18+a44);
  a35=(a35*a18);
  a48=(a48/a20);
  a22=(a22*a26);
  a48=(a48-a22);
  a48=(a09*a48);
  a12=(a12*a47);
  a48=(a48+a12);
  a48=(a48+a48);
  a12=(a11*a48);
  a35=(a35+a12);
  a13=(a13*a47);
  a08=(a08*a28);
  a43=(a43/a20);
  a14=(a14*a26);
  a43=(a43+a14);
  a09=(a09*a43);
  a21=(a21*a09);
  a08=(a08+a21);
  a13=(a13-a08);
  a08=(a11*a13);
  a35=(a35+a08);
  a35=(a00*a35);
  a30=(a30-a35);
  a07=(a07*a18);
  a48=(a02*a48);
  a07=(a07+a48);
  a13=(a02*a13);
  a07=(a07+a13);
  a07=(a01*a07);
  a30=(a30-a07);
  if (res[0]!=0) res[0][1]=a30;
  a30=arg[1]? arg[1][0] : 0;
  a30=(a18+a30);
  if (res[0]!=0) res[0][2]=a30;
  a30=(a00*a33);
  a07=(a00*a31);
  a30=(a30-a07);
  a07=(a01*a10);
  a30=(a30-a07);
  a30=(a02*a30);
  a29=(a29*a25);
  a30=(a30-a29);
  a33=(a01*a33);
  a31=(a01*a31);
  a33=(a33-a31);
  a10=(a00*a10);
  a33=(a33+a10);
  a03=(a03*a33);
  a30=(a30+a03);
  a45=(a45*a38);
  a30=(a30+a45);
  a45=(a01*a37);
  a03=(a00*a18);
  a45=(a45+a03);
  a03=(a01*a40);
  a45=(a45+a03);
  a02=(a02*a45);
  a30=(a30+a02);
  a37=(a00*a37);
  a01=(a01*a18);
  a37=(a37-a01);
  a00=(a00*a40);
  a37=(a37+a00);
  a11=(a11*a37);
  a30=(a30+a11);
  a11=arg[1]? arg[1][1] : 0;
  a30=(a30+a11);
  if (res[0]!=0) res[0][3]=a30;
  a30=5.;
  a30=(a30*a38);
  if (res[0]!=0) res[0][4]=a30;
  if (res[0]!=0) res[0][5]=a30;
  return 0;
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void simplified_inverted_pendulum_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int simplified_inverted_pendulum_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int simplified_inverted_pendulum_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real simplified_inverted_pendulum_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simplified_inverted_pendulum_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simplified_inverted_pendulum_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simplified_inverted_pendulum_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simplified_inverted_pendulum_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int simplified_inverted_pendulum_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
