/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cart_pole_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {5, 1, 1};

/* cart_pole_expl_vde_adj:(i0[4],i1[4],i2,i3[0])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a01=cos(a00);
  a02=-4.1202000000000000e-01;
  a03=8.3699999999999992e+00;
  a04=arg[1]? arg[1][3] : 0;
  a05=5.4363149999999992e-02;
  a06=4.1999999999999996e-02;
  a07=(a06*a01);
  a08=casadi_sq(a07);
  a05=(a05-a08);
  a08=(a04/a05);
  a09=(a03*a08);
  a10=arg[1]? arg[1][2] : 0;
  a11=(a10/a05);
  a12=(a07*a11);
  a09=(a09-a12);
  a09=(a02*a09);
  a12=arg[0]? arg[0][3] : 0;
  a13=casadi_sq(a12);
  a14=6.4949999999999999e-03;
  a15=(a14*a11);
  a16=(a07*a08);
  a15=(a15-a16);
  a16=(a13*a15);
  a16=(a06*a16);
  a09=(a09+a16);
  a01=(a01*a09);
  a00=sin(a00);
  a09=(a07+a07);
  a02=(a02*a00);
  a03=(a03*a02);
  a16=arg[2]? arg[2][0] : 0;
  a17=(a06*a00);
  a13=(a17*a13);
  a16=(a16+a13);
  a13=(a16*a07);
  a03=(a03-a13);
  a03=(a03/a05);
  a03=(a03/a05);
  a03=(a03*a04);
  a14=(a14*a16);
  a07=(a02*a07);
  a14=(a14-a07);
  a14=(a14/a05);
  a14=(a14/a05);
  a14=(a14*a10);
  a03=(a03+a14);
  a09=(a09*a03);
  a16=(a16*a08);
  a09=(a09-a16);
  a02=(a02*a11);
  a09=(a09-a02);
  a06=(a06*a09);
  a00=(a00*a06);
  a01=(a01-a00);
  if (res[0]!=0) res[0][1]=a01;
  a01=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][2]=a01;
  a12=(a12+a12);
  a17=(a17*a15);
  a12=(a12*a17);
  a17=arg[1]? arg[1][1] : 0;
  a12=(a12+a17);
  if (res[0]!=0) res[0][3]=a12;
  if (res[0]!=0) res[0][4]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int cart_pole_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cart_pole_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cart_pole_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cart_pole_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cart_pole_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cart_pole_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cart_pole_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void cart_pole_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cart_pole_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int cart_pole_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cart_pole_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cart_pole_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cart_pole_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cart_pole_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cart_pole_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cart_pole_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cart_pole_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
