function G = gravity_vector(x,theta_p,d_m,theta_a,m_w,m_b,m_m,m_a,m_f,g,r_w,l_bx,l_bz,l_mx,l_mz,l_ax,l_az,l_fx)
%GRAVITY_VECTOR
%    G = GRAVITY_VECTOR(X,THETA_P,D_M,THETA_A,M_W,M_B,M_M,M_A,M_F,g,R_W,L_BX,L_BZ,L_MX,L_MZ,L_AX,L_AZ,L_FX)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    29-Dec-2025 18:33:28

G = [0.0;-g.*m_f.*(sin(theta_p).*(d_m+l_az)-l_fx.*cos(theta_a+theta_p)+l_ax.*cos(theta_p))-g.*m_a.*(sin(theta_p).*(d_m+l_az)+l_ax.*cos(theta_p))-g.*m_b.*(l_bx.*cos(theta_p)+l_bz.*sin(theta_p))-g.*m_m.*(l_mx.*cos(theta_p)+l_mz.*sin(theta_p));g.*cos(theta_p).*(m_a+m_f);g.*l_fx.*m_f.*cos(theta_a+theta_p)];
end
