/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheeled_brick_2D_full_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};

/* wheeled_brick_2D_full_expl_ode_fun:(i0[7],i1[2],i2[])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16;
  a00=arg[0]? arg[0][4] : 0;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a02=(a00*a02);
  if (res[0]!=0) res[0][0]=a02;
  a01=sin(a01);
  a01=(a00*a01);
  if (res[0]!=0) res[0][1]=a01;
  a01=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a01;
  a02=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][3]=a02;
  a03=5.8133333333333326e+00;
  a04=1.1045333333333332e+02;
  a05=8.;
  a06=arg[0]? arg[0][3] : 0;
  a07=cos(a06);
  a08=(a05*a07);
  a09=casadi_sq(a08);
  a04=(a04-a09);
  a03=(a03/a04);
  a06=sin(a06);
  a09=(a05*a06);
  a10=casadi_sq(a02);
  a10=(a09*a10);
  a11=arg[1]? arg[1][0] : 0;
  a12=arg[1]? arg[1][1] : 0;
  a13=(a11+a12);
  a14=2.0000000000000001e-01;
  a13=(a13/a14);
  a10=(a10+a13);
  a03=(a03*a10);
  a08=(a08/a04);
  a13=7.8480000000000004e+01;
  a13=(a13*a06);
  a15=-8.;
  a15=(a15*a06);
  a15=(a15*a00);
  a15=(a15*a02);
  a13=(a13+a15);
  a15=-4.;
  a16=casadi_sq(a01);
  a15=(a15*a16);
  a15=(a15*a06);
  a15=(a15*a07);
  a13=(a13+a15);
  a15=(a05*a00);
  a15=(a15*a01);
  a15=(a15*a07);
  a13=(a13+a15);
  a15=(a08*a13);
  a03=(a03-a15);
  if (res[0]!=0) res[0][4]=a03;
  a03=2.;
  a12=(a12-a11);
  a03=(a03*a12);
  a09=(a09*a07);
  a09=(a09*a02);
  a09=(a09*a01);
  a03=(a03-a09);
  a09=4.0000000000000008e-02;
  a09=(a09*a01);
  a09=(a09*a00);
  a09=(a09*a06);
  a09=(a09/a14);
  a03=(a03-a09);
  a09=1.6733333333333333e+00;
  a14=4.;
  a06=casadi_sq(a06);
  a14=(a14*a06);
  a09=(a09+a14);
  a03=(a03/a09);
  a05=(a05*a01);
  a03=(a03-a05);
  if (res[0]!=0) res[0][5]=a03;
  a03=19.;
  a03=(a03/a04);
  a03=(a03*a13);
  a08=(a08*a10);
  a03=(a03-a08);
  if (res[0]!=0) res[0][6]=a03;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_2D_full_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_2D_full_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wheeled_brick_2D_full_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_2D_full_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_2D_full_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_2D_full_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_2D_full_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
