/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheeled_brick_2D_full_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {7, 7, 1};
static const casadi_int casadi_s2[3] = {7, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};

/* wheeled_brick_2D_full_expl_vde_forw:(i0[7],i1[7x7],i2[7x2],i3[2],i4[])->(o0[7],o1[7x7],o2[7x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55;
  a00=arg[0]? arg[0][4] : 0;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  if (res[0]!=0) res[0][0]=a03;
  a01=sin(a01);
  a03=(a00*a01);
  if (res[0]!=0) res[0][1]=a03;
  a03=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a03;
  a04=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][3]=a04;
  a05=5.8133333333333326e+00;
  a06=1.1045333333333332e+02;
  a07=8.;
  a08=arg[0]? arg[0][3] : 0;
  a09=cos(a08);
  a10=(a07*a09);
  a11=casadi_sq(a10);
  a06=(a06-a11);
  a05=(a05/a06);
  a08=sin(a08);
  a11=(a07*a08);
  a12=casadi_sq(a04);
  a13=(a11*a12);
  a14=arg[3]? arg[3][0] : 0;
  a15=arg[3]? arg[3][1] : 0;
  a16=(a14+a15);
  a17=2.0000000000000001e-01;
  a16=(a16/a17);
  a13=(a13+a16);
  a16=(a05*a13);
  a18=(a10/a06);
  a19=7.8480000000000004e+01;
  a20=(a19*a08);
  a21=-8.;
  a22=(a21*a08);
  a23=(a22*a00);
  a24=(a23*a04);
  a20=(a20+a24);
  a24=-4.;
  a25=casadi_sq(a03);
  a25=(a24*a25);
  a26=(a25*a08);
  a27=(a26*a09);
  a20=(a20+a27);
  a27=(a07*a00);
  a28=(a27*a03);
  a29=(a28*a09);
  a20=(a20+a29);
  a29=(a18*a20);
  a16=(a16-a29);
  if (res[0]!=0) res[0][4]=a16;
  a16=2.;
  a15=(a15-a14);
  a15=(a16*a15);
  a14=(a11*a09);
  a29=(a14*a04);
  a30=(a29*a03);
  a15=(a15-a30);
  a30=4.0000000000000008e-02;
  a31=(a30*a03);
  a32=(a31*a00);
  a33=(a32*a08);
  a33=(a33/a17);
  a15=(a15-a33);
  a33=1.6733333333333333e+00;
  a17=4.;
  a34=casadi_sq(a08);
  a34=(a17*a34);
  a33=(a33+a34);
  a15=(a15/a33);
  a34=(a07*a03);
  a34=(a15-a34);
  if (res[0]!=0) res[0][5]=a34;
  a34=19.;
  a34=(a34/a06);
  a35=(a34*a20);
  a36=(a18*a13);
  a35=(a35-a36);
  if (res[0]!=0) res[0][6]=a35;
  a35=arg[1]? arg[1][4] : 0;
  a36=(a02*a35);
  a37=arg[1]? arg[1][2] : 0;
  a38=(a01*a37);
  a38=(a00*a38);
  a36=(a36-a38);
  if (res[1]!=0) res[1][0]=a36;
  a36=(a01*a35);
  a37=(a02*a37);
  a37=(a00*a37);
  a36=(a36+a37);
  if (res[1]!=0) res[1][1]=a36;
  a36=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a36;
  a37=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][3]=a37;
  a38=arg[1]? arg[1][3] : 0;
  a39=(a09*a38);
  a40=(a07*a39);
  a41=(a12*a40);
  a42=(a04+a04);
  a43=(a42*a37);
  a43=(a11*a43);
  a41=(a41+a43);
  a43=(a05*a41);
  a44=(a05/a06);
  a10=(a10+a10);
  a38=(a08*a38);
  a45=(a07*a38);
  a46=(a10*a45);
  a47=(a44*a46);
  a47=(a13*a47);
  a43=(a43-a47);
  a47=(a19*a39);
  a48=(a21*a39);
  a48=(a00*a48);
  a49=(a22*a35);
  a48=(a48+a49);
  a48=(a04*a48);
  a49=(a23*a37);
  a48=(a48+a49);
  a47=(a47+a48);
  a48=(a03+a03);
  a49=(a48*a36);
  a49=(a24*a49);
  a49=(a08*a49);
  a50=(a25*a39);
  a49=(a49+a50);
  a49=(a09*a49);
  a50=(a26*a38);
  a49=(a49-a50);
  a47=(a47+a49);
  a49=(a07*a35);
  a49=(a03*a49);
  a50=(a27*a36);
  a49=(a49+a50);
  a49=(a09*a49);
  a50=(a28*a38);
  a49=(a49-a50);
  a47=(a47+a49);
  a49=(a18*a47);
  a45=(a45/a06);
  a50=(a18/a06);
  a51=(a50*a46);
  a45=(a45+a51);
  a51=(a20*a45);
  a49=(a49-a51);
  a43=(a43-a49);
  if (res[1]!=0) res[1][4]=a43;
  a40=(a09*a40);
  a38=(a11*a38);
  a40=(a40-a38);
  a40=(a04*a40);
  a37=(a14*a37);
  a40=(a40+a37);
  a40=(a03*a40);
  a37=(a29*a36);
  a40=(a40+a37);
  a37=5.;
  a38=(a30*a36);
  a38=(a00*a38);
  a35=(a31*a35);
  a38=(a38+a35);
  a38=(a08*a38);
  a35=(a32*a39);
  a38=(a38+a35);
  a38=(a37*a38);
  a40=(a40+a38);
  a40=(a40/a33);
  a15=(a15/a33);
  a38=(a08+a08);
  a39=(a38*a39);
  a39=(a17*a39);
  a39=(a15*a39);
  a40=(a40+a39);
  a36=(a07*a36);
  a40=(a40+a36);
  a40=(-a40);
  if (res[1]!=0) res[1][5]=a40;
  a47=(a34*a47);
  a40=(a34/a06);
  a46=(a40*a46);
  a46=(a20*a46);
  a47=(a47-a46);
  a41=(a18*a41);
  a45=(a13*a45);
  a41=(a41-a45);
  a47=(a47-a41);
  if (res[1]!=0) res[1][6]=a47;
  a47=arg[1]? arg[1][11] : 0;
  a41=(a02*a47);
  a45=arg[1]? arg[1][9] : 0;
  a46=(a01*a45);
  a46=(a00*a46);
  a41=(a41-a46);
  if (res[1]!=0) res[1][7]=a41;
  a41=(a01*a47);
  a45=(a02*a45);
  a45=(a00*a45);
  a41=(a41+a45);
  if (res[1]!=0) res[1][8]=a41;
  a41=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][9]=a41;
  a45=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][10]=a45;
  a46=arg[1]? arg[1][10] : 0;
  a36=(a09*a46);
  a39=(a07*a36);
  a35=(a12*a39);
  a43=(a42*a45);
  a43=(a11*a43);
  a35=(a35+a43);
  a43=(a05*a35);
  a46=(a08*a46);
  a49=(a07*a46);
  a51=(a10*a49);
  a52=(a44*a51);
  a52=(a13*a52);
  a43=(a43-a52);
  a52=(a19*a36);
  a53=(a21*a36);
  a53=(a00*a53);
  a54=(a22*a47);
  a53=(a53+a54);
  a53=(a04*a53);
  a54=(a23*a45);
  a53=(a53+a54);
  a52=(a52+a53);
  a53=(a48*a41);
  a53=(a24*a53);
  a53=(a08*a53);
  a54=(a25*a36);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a26*a46);
  a53=(a53-a54);
  a52=(a52+a53);
  a53=(a07*a47);
  a53=(a03*a53);
  a54=(a27*a41);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a28*a46);
  a53=(a53-a54);
  a52=(a52+a53);
  a53=(a18*a52);
  a49=(a49/a06);
  a54=(a50*a51);
  a49=(a49+a54);
  a54=(a20*a49);
  a53=(a53-a54);
  a43=(a43-a53);
  if (res[1]!=0) res[1][11]=a43;
  a39=(a09*a39);
  a46=(a11*a46);
  a39=(a39-a46);
  a39=(a04*a39);
  a45=(a14*a45);
  a39=(a39+a45);
  a39=(a03*a39);
  a45=(a29*a41);
  a39=(a39+a45);
  a45=(a30*a41);
  a45=(a00*a45);
  a47=(a31*a47);
  a45=(a45+a47);
  a45=(a08*a45);
  a47=(a32*a36);
  a45=(a45+a47);
  a45=(a37*a45);
  a39=(a39+a45);
  a39=(a39/a33);
  a36=(a38*a36);
  a36=(a17*a36);
  a36=(a15*a36);
  a39=(a39+a36);
  a41=(a07*a41);
  a39=(a39+a41);
  a39=(-a39);
  if (res[1]!=0) res[1][12]=a39;
  a52=(a34*a52);
  a51=(a40*a51);
  a51=(a20*a51);
  a52=(a52-a51);
  a35=(a18*a35);
  a49=(a13*a49);
  a35=(a35-a49);
  a52=(a52-a35);
  if (res[1]!=0) res[1][13]=a52;
  a52=arg[1]? arg[1][18] : 0;
  a35=(a02*a52);
  a49=arg[1]? arg[1][16] : 0;
  a51=(a01*a49);
  a51=(a00*a51);
  a35=(a35-a51);
  if (res[1]!=0) res[1][14]=a35;
  a35=(a01*a52);
  a49=(a02*a49);
  a49=(a00*a49);
  a35=(a35+a49);
  if (res[1]!=0) res[1][15]=a35;
  a35=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][16]=a35;
  a49=arg[1]? arg[1][20] : 0;
  if (res[1]!=0) res[1][17]=a49;
  a51=arg[1]? arg[1][17] : 0;
  a39=(a09*a51);
  a41=(a07*a39);
  a36=(a12*a41);
  a45=(a42*a49);
  a45=(a11*a45);
  a36=(a36+a45);
  a45=(a05*a36);
  a51=(a08*a51);
  a47=(a07*a51);
  a46=(a10*a47);
  a43=(a44*a46);
  a43=(a13*a43);
  a45=(a45-a43);
  a43=(a19*a39);
  a53=(a21*a39);
  a53=(a00*a53);
  a54=(a22*a52);
  a53=(a53+a54);
  a53=(a04*a53);
  a54=(a23*a49);
  a53=(a53+a54);
  a43=(a43+a53);
  a53=(a48*a35);
  a53=(a24*a53);
  a53=(a08*a53);
  a54=(a25*a39);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a26*a51);
  a53=(a53-a54);
  a43=(a43+a53);
  a53=(a07*a52);
  a53=(a03*a53);
  a54=(a27*a35);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a28*a51);
  a53=(a53-a54);
  a43=(a43+a53);
  a53=(a18*a43);
  a47=(a47/a06);
  a54=(a50*a46);
  a47=(a47+a54);
  a54=(a20*a47);
  a53=(a53-a54);
  a45=(a45-a53);
  if (res[1]!=0) res[1][18]=a45;
  a41=(a09*a41);
  a51=(a11*a51);
  a41=(a41-a51);
  a41=(a04*a41);
  a49=(a14*a49);
  a41=(a41+a49);
  a41=(a03*a41);
  a49=(a29*a35);
  a41=(a41+a49);
  a49=(a30*a35);
  a49=(a00*a49);
  a52=(a31*a52);
  a49=(a49+a52);
  a49=(a08*a49);
  a52=(a32*a39);
  a49=(a49+a52);
  a49=(a37*a49);
  a41=(a41+a49);
  a41=(a41/a33);
  a39=(a38*a39);
  a39=(a17*a39);
  a39=(a15*a39);
  a41=(a41+a39);
  a35=(a07*a35);
  a41=(a41+a35);
  a41=(-a41);
  if (res[1]!=0) res[1][19]=a41;
  a43=(a34*a43);
  a46=(a40*a46);
  a46=(a20*a46);
  a43=(a43-a46);
  a36=(a18*a36);
  a47=(a13*a47);
  a36=(a36-a47);
  a43=(a43-a36);
  if (res[1]!=0) res[1][20]=a43;
  a43=arg[1]? arg[1][25] : 0;
  a36=(a02*a43);
  a47=arg[1]? arg[1][23] : 0;
  a46=(a01*a47);
  a46=(a00*a46);
  a36=(a36-a46);
  if (res[1]!=0) res[1][21]=a36;
  a36=(a01*a43);
  a47=(a02*a47);
  a47=(a00*a47);
  a36=(a36+a47);
  if (res[1]!=0) res[1][22]=a36;
  a36=arg[1]? arg[1][26] : 0;
  if (res[1]!=0) res[1][23]=a36;
  a47=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][24]=a47;
  a46=arg[1]? arg[1][24] : 0;
  a41=(a09*a46);
  a35=(a07*a41);
  a39=(a12*a35);
  a49=(a42*a47);
  a49=(a11*a49);
  a39=(a39+a49);
  a49=(a05*a39);
  a46=(a08*a46);
  a52=(a07*a46);
  a51=(a10*a52);
  a45=(a44*a51);
  a45=(a13*a45);
  a49=(a49-a45);
  a45=(a19*a41);
  a53=(a21*a41);
  a53=(a00*a53);
  a54=(a22*a43);
  a53=(a53+a54);
  a53=(a04*a53);
  a54=(a23*a47);
  a53=(a53+a54);
  a45=(a45+a53);
  a53=(a48*a36);
  a53=(a24*a53);
  a53=(a08*a53);
  a54=(a25*a41);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a26*a46);
  a53=(a53-a54);
  a45=(a45+a53);
  a53=(a07*a43);
  a53=(a03*a53);
  a54=(a27*a36);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a28*a46);
  a53=(a53-a54);
  a45=(a45+a53);
  a53=(a18*a45);
  a52=(a52/a06);
  a54=(a50*a51);
  a52=(a52+a54);
  a54=(a20*a52);
  a53=(a53-a54);
  a49=(a49-a53);
  if (res[1]!=0) res[1][25]=a49;
  a35=(a09*a35);
  a46=(a11*a46);
  a35=(a35-a46);
  a35=(a04*a35);
  a47=(a14*a47);
  a35=(a35+a47);
  a35=(a03*a35);
  a47=(a29*a36);
  a35=(a35+a47);
  a47=(a30*a36);
  a47=(a00*a47);
  a43=(a31*a43);
  a47=(a47+a43);
  a47=(a08*a47);
  a43=(a32*a41);
  a47=(a47+a43);
  a47=(a37*a47);
  a35=(a35+a47);
  a35=(a35/a33);
  a41=(a38*a41);
  a41=(a17*a41);
  a41=(a15*a41);
  a35=(a35+a41);
  a36=(a07*a36);
  a35=(a35+a36);
  a35=(-a35);
  if (res[1]!=0) res[1][26]=a35;
  a45=(a34*a45);
  a51=(a40*a51);
  a51=(a20*a51);
  a45=(a45-a51);
  a39=(a18*a39);
  a52=(a13*a52);
  a39=(a39-a52);
  a45=(a45-a39);
  if (res[1]!=0) res[1][27]=a45;
  a45=arg[1]? arg[1][32] : 0;
  a39=(a02*a45);
  a52=arg[1]? arg[1][30] : 0;
  a51=(a01*a52);
  a51=(a00*a51);
  a39=(a39-a51);
  if (res[1]!=0) res[1][28]=a39;
  a39=(a01*a45);
  a52=(a02*a52);
  a52=(a00*a52);
  a39=(a39+a52);
  if (res[1]!=0) res[1][29]=a39;
  a39=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][30]=a39;
  a52=arg[1]? arg[1][34] : 0;
  if (res[1]!=0) res[1][31]=a52;
  a51=arg[1]? arg[1][31] : 0;
  a35=(a09*a51);
  a36=(a07*a35);
  a41=(a12*a36);
  a47=(a42*a52);
  a47=(a11*a47);
  a41=(a41+a47);
  a47=(a05*a41);
  a51=(a08*a51);
  a43=(a07*a51);
  a46=(a10*a43);
  a49=(a44*a46);
  a49=(a13*a49);
  a47=(a47-a49);
  a49=(a19*a35);
  a53=(a21*a35);
  a53=(a00*a53);
  a54=(a22*a45);
  a53=(a53+a54);
  a53=(a04*a53);
  a54=(a23*a52);
  a53=(a53+a54);
  a49=(a49+a53);
  a53=(a48*a39);
  a53=(a24*a53);
  a53=(a08*a53);
  a54=(a25*a35);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a26*a51);
  a53=(a53-a54);
  a49=(a49+a53);
  a53=(a07*a45);
  a53=(a03*a53);
  a54=(a27*a39);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a28*a51);
  a53=(a53-a54);
  a49=(a49+a53);
  a53=(a18*a49);
  a43=(a43/a06);
  a54=(a50*a46);
  a43=(a43+a54);
  a54=(a20*a43);
  a53=(a53-a54);
  a47=(a47-a53);
  if (res[1]!=0) res[1][32]=a47;
  a36=(a09*a36);
  a51=(a11*a51);
  a36=(a36-a51);
  a36=(a04*a36);
  a52=(a14*a52);
  a36=(a36+a52);
  a36=(a03*a36);
  a52=(a29*a39);
  a36=(a36+a52);
  a52=(a30*a39);
  a52=(a00*a52);
  a45=(a31*a45);
  a52=(a52+a45);
  a52=(a08*a52);
  a45=(a32*a35);
  a52=(a52+a45);
  a52=(a37*a52);
  a36=(a36+a52);
  a36=(a36/a33);
  a35=(a38*a35);
  a35=(a17*a35);
  a35=(a15*a35);
  a36=(a36+a35);
  a39=(a07*a39);
  a36=(a36+a39);
  a36=(-a36);
  if (res[1]!=0) res[1][33]=a36;
  a49=(a34*a49);
  a46=(a40*a46);
  a46=(a20*a46);
  a49=(a49-a46);
  a41=(a18*a41);
  a43=(a13*a43);
  a41=(a41-a43);
  a49=(a49-a41);
  if (res[1]!=0) res[1][34]=a49;
  a49=arg[1]? arg[1][39] : 0;
  a41=(a02*a49);
  a43=arg[1]? arg[1][37] : 0;
  a46=(a01*a43);
  a46=(a00*a46);
  a41=(a41-a46);
  if (res[1]!=0) res[1][35]=a41;
  a41=(a01*a49);
  a43=(a02*a43);
  a43=(a00*a43);
  a41=(a41+a43);
  if (res[1]!=0) res[1][36]=a41;
  a41=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][37]=a41;
  a43=arg[1]? arg[1][41] : 0;
  if (res[1]!=0) res[1][38]=a43;
  a46=arg[1]? arg[1][38] : 0;
  a36=(a09*a46);
  a39=(a07*a36);
  a35=(a12*a39);
  a52=(a42*a43);
  a52=(a11*a52);
  a35=(a35+a52);
  a52=(a05*a35);
  a46=(a08*a46);
  a45=(a07*a46);
  a51=(a10*a45);
  a47=(a44*a51);
  a47=(a13*a47);
  a52=(a52-a47);
  a47=(a19*a36);
  a53=(a21*a36);
  a53=(a00*a53);
  a54=(a22*a49);
  a53=(a53+a54);
  a53=(a04*a53);
  a54=(a23*a43);
  a53=(a53+a54);
  a47=(a47+a53);
  a53=(a48*a41);
  a53=(a24*a53);
  a53=(a08*a53);
  a54=(a25*a36);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a26*a46);
  a53=(a53-a54);
  a47=(a47+a53);
  a53=(a07*a49);
  a53=(a03*a53);
  a54=(a27*a41);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a28*a46);
  a53=(a53-a54);
  a47=(a47+a53);
  a53=(a18*a47);
  a45=(a45/a06);
  a54=(a50*a51);
  a45=(a45+a54);
  a54=(a20*a45);
  a53=(a53-a54);
  a52=(a52-a53);
  if (res[1]!=0) res[1][39]=a52;
  a39=(a09*a39);
  a46=(a11*a46);
  a39=(a39-a46);
  a39=(a04*a39);
  a43=(a14*a43);
  a39=(a39+a43);
  a39=(a03*a39);
  a43=(a29*a41);
  a39=(a39+a43);
  a43=(a30*a41);
  a43=(a00*a43);
  a49=(a31*a49);
  a43=(a43+a49);
  a43=(a08*a43);
  a49=(a32*a36);
  a43=(a43+a49);
  a43=(a37*a43);
  a39=(a39+a43);
  a39=(a39/a33);
  a36=(a38*a36);
  a36=(a17*a36);
  a36=(a15*a36);
  a39=(a39+a36);
  a41=(a07*a41);
  a39=(a39+a41);
  a39=(-a39);
  if (res[1]!=0) res[1][40]=a39;
  a47=(a34*a47);
  a51=(a40*a51);
  a51=(a20*a51);
  a47=(a47-a51);
  a35=(a18*a35);
  a45=(a13*a45);
  a35=(a35-a45);
  a47=(a47-a35);
  if (res[1]!=0) res[1][41]=a47;
  a47=arg[1]? arg[1][46] : 0;
  a35=(a02*a47);
  a45=arg[1]? arg[1][44] : 0;
  a51=(a01*a45);
  a51=(a00*a51);
  a35=(a35-a51);
  if (res[1]!=0) res[1][42]=a35;
  a35=(a01*a47);
  a45=(a02*a45);
  a45=(a00*a45);
  a35=(a35+a45);
  if (res[1]!=0) res[1][43]=a35;
  a35=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][44]=a35;
  a45=arg[1]? arg[1][48] : 0;
  if (res[1]!=0) res[1][45]=a45;
  a51=arg[1]? arg[1][45] : 0;
  a39=(a09*a51);
  a41=(a07*a39);
  a36=(a12*a41);
  a43=(a42*a45);
  a43=(a11*a43);
  a36=(a36+a43);
  a43=(a05*a36);
  a51=(a08*a51);
  a49=(a07*a51);
  a46=(a10*a49);
  a52=(a44*a46);
  a52=(a13*a52);
  a43=(a43-a52);
  a52=(a19*a39);
  a53=(a21*a39);
  a53=(a00*a53);
  a54=(a22*a47);
  a53=(a53+a54);
  a53=(a04*a53);
  a54=(a23*a45);
  a53=(a53+a54);
  a52=(a52+a53);
  a53=(a48*a35);
  a53=(a24*a53);
  a53=(a08*a53);
  a54=(a25*a39);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a26*a51);
  a53=(a53-a54);
  a52=(a52+a53);
  a53=(a07*a47);
  a53=(a03*a53);
  a54=(a27*a35);
  a53=(a53+a54);
  a53=(a09*a53);
  a54=(a28*a51);
  a53=(a53-a54);
  a52=(a52+a53);
  a53=(a18*a52);
  a49=(a49/a06);
  a54=(a50*a46);
  a49=(a49+a54);
  a54=(a20*a49);
  a53=(a53-a54);
  a43=(a43-a53);
  if (res[1]!=0) res[1][46]=a43;
  a41=(a09*a41);
  a51=(a11*a51);
  a41=(a41-a51);
  a41=(a04*a41);
  a45=(a14*a45);
  a41=(a41+a45);
  a41=(a03*a41);
  a45=(a29*a35);
  a41=(a41+a45);
  a45=(a30*a35);
  a45=(a00*a45);
  a47=(a31*a47);
  a45=(a45+a47);
  a45=(a08*a45);
  a47=(a32*a39);
  a45=(a45+a47);
  a45=(a37*a45);
  a41=(a41+a45);
  a41=(a41/a33);
  a39=(a38*a39);
  a39=(a17*a39);
  a39=(a15*a39);
  a41=(a41+a39);
  a35=(a07*a35);
  a41=(a41+a35);
  a41=(-a41);
  if (res[1]!=0) res[1][47]=a41;
  a52=(a34*a52);
  a46=(a40*a46);
  a46=(a20*a46);
  a52=(a52-a46);
  a36=(a18*a36);
  a49=(a13*a49);
  a36=(a36-a49);
  a52=(a52-a36);
  if (res[1]!=0) res[1][48]=a52;
  a52=arg[2]? arg[2][4] : 0;
  a36=(a02*a52);
  a49=arg[2]? arg[2][2] : 0;
  a46=(a01*a49);
  a46=(a00*a46);
  a36=(a36-a46);
  if (res[2]!=0) res[2][0]=a36;
  a36=(a01*a52);
  a49=(a02*a49);
  a49=(a00*a49);
  a36=(a36+a49);
  if (res[2]!=0) res[2][1]=a36;
  a36=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a36;
  a49=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][3]=a49;
  a46=(a37*a05);
  a41=arg[2]? arg[2][3] : 0;
  a35=(a09*a41);
  a39=(a07*a35);
  a45=(a12*a39);
  a47=(a42*a49);
  a47=(a11*a47);
  a45=(a45+a47);
  a47=(a05*a45);
  a41=(a08*a41);
  a51=(a07*a41);
  a43=(a10*a51);
  a53=(a44*a43);
  a53=(a13*a53);
  a47=(a47-a53);
  a53=(a19*a35);
  a54=(a21*a35);
  a54=(a00*a54);
  a55=(a22*a52);
  a54=(a54+a55);
  a54=(a04*a54);
  a55=(a23*a49);
  a54=(a54+a55);
  a53=(a53+a54);
  a54=(a48*a36);
  a54=(a24*a54);
  a54=(a08*a54);
  a55=(a25*a35);
  a54=(a54+a55);
  a54=(a09*a54);
  a55=(a26*a41);
  a54=(a54-a55);
  a53=(a53+a54);
  a54=(a07*a52);
  a54=(a03*a54);
  a55=(a27*a36);
  a54=(a54+a55);
  a54=(a09*a54);
  a55=(a28*a41);
  a54=(a54-a55);
  a53=(a53+a54);
  a54=(a18*a53);
  a51=(a51/a06);
  a55=(a50*a43);
  a51=(a51+a55);
  a55=(a20*a51);
  a54=(a54-a55);
  a47=(a47-a54);
  a47=(a46+a47);
  if (res[2]!=0) res[2][4]=a47;
  a47=-2.;
  a47=(a47/a33);
  a39=(a09*a39);
  a41=(a11*a41);
  a39=(a39-a41);
  a39=(a04*a39);
  a49=(a14*a49);
  a39=(a39+a49);
  a39=(a03*a39);
  a49=(a29*a36);
  a39=(a39+a49);
  a49=(a30*a36);
  a49=(a00*a49);
  a52=(a31*a52);
  a49=(a49+a52);
  a49=(a08*a49);
  a52=(a32*a35);
  a49=(a49+a52);
  a49=(a37*a49);
  a39=(a39+a49);
  a39=(a39/a33);
  a35=(a38*a35);
  a35=(a17*a35);
  a35=(a15*a35);
  a39=(a39+a35);
  a36=(a07*a36);
  a39=(a39+a36);
  a47=(a47-a39);
  if (res[2]!=0) res[2][5]=a47;
  a53=(a34*a53);
  a43=(a40*a43);
  a43=(a20*a43);
  a53=(a53-a43);
  a45=(a18*a45);
  a51=(a13*a51);
  a45=(a45-a51);
  a53=(a53-a45);
  a45=(a37*a18);
  a53=(a53-a45);
  if (res[2]!=0) res[2][6]=a53;
  a53=arg[2]? arg[2][11] : 0;
  a51=(a02*a53);
  a43=arg[2]? arg[2][9] : 0;
  a47=(a01*a43);
  a47=(a00*a47);
  a51=(a51-a47);
  if (res[2]!=0) res[2][7]=a51;
  a01=(a01*a53);
  a02=(a02*a43);
  a02=(a00*a02);
  a01=(a01+a02);
  if (res[2]!=0) res[2][8]=a01;
  a01=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][9]=a01;
  a02=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][10]=a02;
  a43=arg[2]? arg[2][10] : 0;
  a51=(a09*a43);
  a47=(a07*a51);
  a12=(a12*a47);
  a42=(a42*a02);
  a42=(a11*a42);
  a12=(a12+a42);
  a05=(a05*a12);
  a43=(a08*a43);
  a42=(a07*a43);
  a10=(a10*a42);
  a44=(a44*a10);
  a44=(a13*a44);
  a05=(a05-a44);
  a19=(a19*a51);
  a21=(a21*a51);
  a21=(a00*a21);
  a22=(a22*a53);
  a21=(a21+a22);
  a21=(a04*a21);
  a23=(a23*a02);
  a21=(a21+a23);
  a19=(a19+a21);
  a48=(a48*a01);
  a24=(a24*a48);
  a24=(a08*a24);
  a25=(a25*a51);
  a24=(a24+a25);
  a24=(a09*a24);
  a26=(a26*a43);
  a24=(a24-a26);
  a19=(a19+a24);
  a24=(a07*a53);
  a24=(a03*a24);
  a27=(a27*a01);
  a24=(a24+a27);
  a24=(a09*a24);
  a28=(a28*a43);
  a24=(a24-a28);
  a19=(a19+a24);
  a24=(a18*a19);
  a42=(a42/a06);
  a50=(a50*a10);
  a42=(a42+a50);
  a50=(a20*a42);
  a24=(a24-a50);
  a05=(a05-a24);
  a46=(a46+a05);
  if (res[2]!=0) res[2][11]=a46;
  a16=(a16/a33);
  a09=(a09*a47);
  a11=(a11*a43);
  a09=(a09-a11);
  a04=(a04*a09);
  a14=(a14*a02);
  a04=(a04+a14);
  a03=(a03*a04);
  a29=(a29*a01);
  a03=(a03+a29);
  a30=(a30*a01);
  a00=(a00*a30);
  a31=(a31*a53);
  a00=(a00+a31);
  a08=(a08*a00);
  a32=(a32*a51);
  a08=(a08+a32);
  a37=(a37*a08);
  a03=(a03+a37);
  a03=(a03/a33);
  a38=(a38*a51);
  a17=(a17*a38);
  a15=(a15*a17);
  a03=(a03+a15);
  a07=(a07*a01);
  a03=(a03+a07);
  a16=(a16-a03);
  if (res[2]!=0) res[2][12]=a16;
  a34=(a34*a19);
  a40=(a40*a10);
  a20=(a20*a40);
  a34=(a34-a20);
  a18=(a18*a12);
  a13=(a13*a42);
  a18=(a18-a13);
  a34=(a34-a18);
  a34=(a34-a45);
  if (res[2]!=0) res[2][13]=a34;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_2D_full_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_2D_full_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real wheeled_brick_2D_full_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_2D_full_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_2D_full_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_2D_full_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_2D_full_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
