/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheeled_brick_2D_full_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};

/* wheeled_brick_2D_full_expl_vde_adj:(i0[7],i1[7],i2[2],i3[])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][4] : 0;
  a03=arg[1]? arg[1][1] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a00=sin(a00);
  a05=arg[1]? arg[1][0] : 0;
  a06=(a02*a05);
  a06=(a00*a06);
  a04=(a04-a06);
  if (res[0]!=0) res[0][2]=a04;
  a04=arg[0]? arg[0][3] : 0;
  a06=cos(a04);
  a07=-4.;
  a08=arg[0]? arg[0][5] : 0;
  a09=casadi_sq(a08);
  a09=(a07*a09);
  a10=19.;
  a11=1.1045333333333332e+02;
  a12=8.;
  a13=(a12*a06);
  a14=casadi_sq(a13);
  a11=(a11-a14);
  a10=(a10/a11);
  a14=arg[1]? arg[1][6] : 0;
  a15=(a10*a14);
  a16=(a13/a11);
  a17=arg[1]? arg[1][4] : 0;
  a18=(a16*a17);
  a15=(a15-a18);
  a18=(a06*a15);
  a19=(a09*a18);
  a04=sin(a04);
  a20=(a04+a04);
  a21=4.;
  a22=2.;
  a23=arg[2]? arg[2][1] : 0;
  a24=arg[2]? arg[2][0] : 0;
  a25=(a23-a24);
  a25=(a22*a25);
  a26=(a12*a04);
  a27=(a26*a06);
  a28=arg[0]? arg[0][6] : 0;
  a29=(a27*a28);
  a30=(a29*a08);
  a25=(a25-a30);
  a30=4.0000000000000008e-02;
  a31=(a30*a08);
  a32=(a31*a02);
  a33=(a32*a04);
  a34=2.0000000000000001e-01;
  a33=(a33/a34);
  a25=(a25-a33);
  a33=1.6733333333333333e+00;
  a35=casadi_sq(a04);
  a35=(a21*a35);
  a33=(a33+a35);
  a25=(a25/a33);
  a25=(a25/a33);
  a35=arg[1]? arg[1][5] : 0;
  a25=(a25*a35);
  a21=(a21*a25);
  a20=(a20*a21);
  a21=5.;
  a33=(a35/a33);
  a25=(a21*a33);
  a32=(a32*a25);
  a20=(a20+a32);
  a32=(a08*a33);
  a36=(a28*a32);
  a37=(a06*a36);
  a37=(a12*a37);
  a20=(a20+a37);
  a19=(a19-a20);
  a20=-8.;
  a37=(a28*a15);
  a38=(a02*a37);
  a38=(a20*a38);
  a19=(a19+a38);
  a38=7.8480000000000004e+01;
  a39=(a38*a15);
  a19=(a19+a39);
  a39=casadi_sq(a28);
  a40=5.8133333333333326e+00;
  a40=(a40/a11);
  a41=(a40*a17);
  a42=(a16*a14);
  a41=(a41-a42);
  a42=(a39*a41);
  a42=(a12*a42);
  a19=(a19+a42);
  a19=(a06*a19);
  a42=(a12*a02);
  a43=(a42*a08);
  a44=(a43*a15);
  a39=(a26*a39);
  a24=(a24+a23);
  a24=(a24/a34);
  a39=(a39+a24);
  a24=(a39*a14);
  a34=(a24/a11);
  a34=(a12*a34);
  a36=(a26*a36);
  a34=(a34+a36);
  a44=(a44-a34);
  a09=(a09*a04);
  a34=(a09*a15);
  a44=(a44+a34);
  a38=(a38*a04);
  a20=(a20*a04);
  a34=(a20*a02);
  a36=(a34*a28);
  a38=(a38+a36);
  a09=(a09*a06);
  a38=(a38+a09);
  a43=(a43*a06);
  a38=(a38+a43);
  a43=(a38*a17);
  a06=(a43/a11);
  a13=(a13+a13);
  a16=(a16/a11);
  a24=(a16*a24);
  a10=(a10/a11);
  a38=(a38*a14);
  a10=(a10*a38);
  a24=(a24-a10);
  a16=(a16*a43);
  a24=(a24+a16);
  a40=(a40/a11);
  a39=(a39*a17);
  a40=(a40*a39);
  a24=(a24-a40);
  a13=(a13*a24);
  a06=(a06+a13);
  a06=(a12*a06);
  a44=(a44-a06);
  a44=(a04*a44);
  a19=(a19-a44);
  if (res[0]!=0) res[0][3]=a19;
  a19=(a08*a18);
  a19=(a12*a19);
  a25=(a04*a25);
  a31=(a31*a25);
  a19=(a19-a31);
  a20=(a20*a37);
  a19=(a19+a20);
  a00=(a00*a03);
  a19=(a19+a00);
  a01=(a01*a05);
  a19=(a19+a01);
  if (res[0]!=0) res[0][4]=a19;
  a42=(a42*a18);
  a12=(a12*a35);
  a02=(a02*a25);
  a30=(a30*a02);
  a12=(a12+a30);
  a29=(a29*a33);
  a12=(a12+a29);
  a42=(a42-a12);
  a08=(a08+a08);
  a04=(a04*a18);
  a07=(a07*a04);
  a08=(a08*a07);
  a42=(a42+a08);
  a08=arg[1]? arg[1][2] : 0;
  a42=(a42+a08);
  if (res[0]!=0) res[0][5]=a42;
  a34=(a34*a15);
  a27=(a27*a32);
  a34=(a34-a27);
  a28=(a28+a28);
  a26=(a26*a41);
  a28=(a28*a26);
  a34=(a34+a28);
  a28=arg[1]? arg[1][3] : 0;
  a34=(a34+a28);
  if (res[0]!=0) res[0][6]=a34;
  a21=(a21*a41);
  a22=(a22*a33);
  a33=(a21-a22);
  if (res[0]!=0) res[0][7]=a33;
  a22=(a22+a21);
  if (res[0]!=0) res[0][8]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheeled_brick_2D_full_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_2D_full_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int wheeled_brick_2D_full_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wheeled_brick_2D_full_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_2D_full_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_brick_2D_full_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_2D_full_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_brick_2D_full_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_brick_2D_full_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
