/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* pendulum_expl_vde_forw:(i0[4],i1[4x4],i2[4],i3,i4)->(o0[4],o1[4x4],o2[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a01=-8.0000000000000016e-02;
  a02=arg[0]? arg[0][1] : 0;
  a03=sin(a02);
  a04=(a01*a03);
  a05=casadi_sq(a00);
  a06=(a04*a05);
  a07=arg[3]? arg[3][0] : 0;
  a06=(a06+a07);
  a08=9.8100000000000009e-01;
  a02=cos(a02);
  a09=(a08*a02);
  a10=(a09*a03);
  a06=(a06+a10);
  a10=arg[4]? arg[4][0] : 0;
  a11=1.0000000000000001e-01;
  a12=(a10+a11);
  a13=casadi_sq(a02);
  a13=(a11*a13);
  a12=(a12-a13);
  a06=(a06/a12);
  if (res[0]!=0) res[0][2]=a06;
  a13=(a01*a02);
  a14=(a13*a03);
  a15=(a14*a05);
  a16=(a07*a02);
  a15=(a15+a16);
  a16=(a08*a03);
  a15=(a15+a16);
  a16=9.8100000000000005e+00;
  a16=(a16*a10);
  a10=(a16*a03);
  a15=(a15+a10);
  a10=8.0000000000000004e-01;
  a17=(a10*a12);
  a15=(a15/a17);
  if (res[0]!=0) res[0][3]=a15;
  a18=arg[1]? arg[1][2] : 0;
  if (res[1]!=0) res[1][0]=a18;
  a18=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][1]=a18;
  a19=arg[1]? arg[1][1] : 0;
  a20=(a02*a19);
  a21=(a01*a20);
  a21=(a05*a21);
  a00=(a00+a00);
  a18=(a00*a18);
  a22=(a04*a18);
  a21=(a21+a22);
  a22=(a09*a20);
  a19=(a03*a19);
  a23=(a08*a19);
  a23=(a03*a23);
  a22=(a22-a23);
  a21=(a21+a22);
  a21=(a21/a12);
  a06=(a06/a12);
  a22=(a02+a02);
  a23=(a22*a19);
  a23=(a11*a23);
  a24=(a06*a23);
  a21=(a21-a24);
  if (res[1]!=0) res[1][2]=a21;
  a21=(a13*a20);
  a24=(a01*a19);
  a24=(a03*a24);
  a21=(a21-a24);
  a21=(a05*a21);
  a18=(a14*a18);
  a21=(a21+a18);
  a19=(a07*a19);
  a21=(a21-a19);
  a19=(a08*a20);
  a21=(a21+a19);
  a20=(a16*a20);
  a21=(a21+a20);
  a21=(a21/a17);
  a15=(a15/a17);
  a23=(a10*a23);
  a23=(a15*a23);
  a21=(a21-a23);
  if (res[1]!=0) res[1][3]=a21;
  a21=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][4]=a21;
  a21=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][5]=a21;
  a23=arg[1]? arg[1][5] : 0;
  a20=(a02*a23);
  a19=(a01*a20);
  a19=(a05*a19);
  a21=(a00*a21);
  a18=(a04*a21);
  a19=(a19+a18);
  a18=(a09*a20);
  a23=(a03*a23);
  a24=(a08*a23);
  a24=(a03*a24);
  a18=(a18-a24);
  a19=(a19+a18);
  a19=(a19/a12);
  a18=(a22*a23);
  a18=(a11*a18);
  a24=(a06*a18);
  a19=(a19-a24);
  if (res[1]!=0) res[1][6]=a19;
  a19=(a13*a20);
  a24=(a01*a23);
  a24=(a03*a24);
  a19=(a19-a24);
  a19=(a05*a19);
  a21=(a14*a21);
  a19=(a19+a21);
  a23=(a07*a23);
  a19=(a19-a23);
  a23=(a08*a20);
  a19=(a19+a23);
  a20=(a16*a20);
  a19=(a19+a20);
  a19=(a19/a17);
  a18=(a10*a18);
  a18=(a15*a18);
  a19=(a19-a18);
  if (res[1]!=0) res[1][7]=a19;
  a19=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][8]=a19;
  a19=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][9]=a19;
  a18=arg[1]? arg[1][9] : 0;
  a20=(a02*a18);
  a23=(a01*a20);
  a23=(a05*a23);
  a19=(a00*a19);
  a21=(a04*a19);
  a23=(a23+a21);
  a21=(a09*a20);
  a18=(a03*a18);
  a24=(a08*a18);
  a24=(a03*a24);
  a21=(a21-a24);
  a23=(a23+a21);
  a23=(a23/a12);
  a21=(a22*a18);
  a21=(a11*a21);
  a24=(a06*a21);
  a23=(a23-a24);
  if (res[1]!=0) res[1][10]=a23;
  a23=(a13*a20);
  a24=(a01*a18);
  a24=(a03*a24);
  a23=(a23-a24);
  a23=(a05*a23);
  a19=(a14*a19);
  a23=(a23+a19);
  a18=(a07*a18);
  a23=(a23-a18);
  a18=(a08*a20);
  a23=(a23+a18);
  a20=(a16*a20);
  a23=(a23+a20);
  a23=(a23/a17);
  a21=(a10*a21);
  a21=(a15*a21);
  a23=(a23-a21);
  if (res[1]!=0) res[1][11]=a23;
  a23=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][12]=a23;
  a23=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][13]=a23;
  a21=arg[1]? arg[1][13] : 0;
  a20=(a02*a21);
  a18=(a01*a20);
  a18=(a05*a18);
  a23=(a00*a23);
  a19=(a04*a23);
  a18=(a18+a19);
  a19=(a09*a20);
  a21=(a03*a21);
  a24=(a08*a21);
  a24=(a03*a24);
  a19=(a19-a24);
  a18=(a18+a19);
  a18=(a18/a12);
  a19=(a22*a21);
  a19=(a11*a19);
  a24=(a06*a19);
  a18=(a18-a24);
  if (res[1]!=0) res[1][14]=a18;
  a18=(a13*a20);
  a24=(a01*a21);
  a24=(a03*a24);
  a18=(a18-a24);
  a18=(a05*a18);
  a23=(a14*a23);
  a18=(a18+a23);
  a21=(a07*a21);
  a18=(a18-a21);
  a21=(a08*a20);
  a18=(a18+a21);
  a20=(a16*a20);
  a18=(a18+a20);
  a18=(a18/a17);
  a19=(a10*a19);
  a19=(a15*a19);
  a18=(a18-a19);
  if (res[1]!=0) res[1][15]=a18;
  a18=arg[2]? arg[2][2] : 0;
  if (res[2]!=0) res[2][0]=a18;
  a18=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][1]=a18;
  a19=(1./a12);
  a20=arg[2]? arg[2][1] : 0;
  a21=(a02*a20);
  a23=(a01*a21);
  a23=(a05*a23);
  a00=(a00*a18);
  a04=(a04*a00);
  a23=(a23+a04);
  a09=(a09*a21);
  a20=(a03*a20);
  a04=(a08*a20);
  a04=(a03*a04);
  a09=(a09-a04);
  a23=(a23+a09);
  a23=(a23/a12);
  a22=(a22*a20);
  a11=(a11*a22);
  a06=(a06*a11);
  a23=(a23-a06);
  a19=(a19+a23);
  if (res[2]!=0) res[2][2]=a19;
  a02=(a02/a17);
  a13=(a13*a21);
  a01=(a01*a20);
  a03=(a03*a01);
  a13=(a13-a03);
  a05=(a05*a13);
  a14=(a14*a00);
  a05=(a05+a14);
  a07=(a07*a20);
  a05=(a05-a07);
  a08=(a08*a21);
  a05=(a05+a08);
  a16=(a16*a21);
  a05=(a05+a16);
  a05=(a05/a17);
  a10=(a10*a11);
  a15=(a15*a10);
  a05=(a05-a15);
  a02=(a02+a05);
  if (res[2]!=0) res[2][3]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pendulum_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pendulum_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pendulum_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real pendulum_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
