function C = coriolis_matrix(theta_w,theta_p,d_m,theta_a,dtheta_w,dtheta_p,dd_m,dtheta_a,m_w,m_b,m_m,m_a,m_f,I_w,I_b,I_m,I_a,I_f,r_w,l_bx,l_bz,l_mx,l_mz,l_ax,l_az,l_fx)
%CORIOLIS_MATRIX
%    C = CORIOLIS_MATRIX(THETA_W,THETA_P,D_M,THETA_A,DTHETA_W,DTHETA_P,DD_M,DTHETA_A,M_W,M_B,M_M,M_A,M_F,I_w,I_b,I_m,I_a,I_f,R_W,L_BX,L_BZ,L_MX,L_MZ,L_AX,L_AZ,L_FX)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-Dec-2025 17:24:07

mt1 = [0.0,0.0,0.0,0.0,dd_m.*(m_a.*r_w.*cos(theta_p)+m_f.*r_w.*cos(theta_p))-dtheta_p.*(m_f.*r_w.*(sin(theta_p).*(d_m+l_az)+l_fx.*cos(theta_a+theta_p)+l_ax.*cos(theta_p))+m_a.*r_w.*(sin(theta_p).*(d_m+l_az)+l_ax.*cos(theta_p))+m_b.*r_w.*(l_bx.*cos(theta_p)+l_bz.*sin(theta_p))+m_m.*r_w.*(l_mx.*cos(theta_p)+l_mz.*sin(theta_p)))-dtheta_a.*l_fx.*m_f.*r_w.*cos(theta_a+theta_p),d_m.*dd_m.*m_a+d_m.*dd_m.*m_f+dd_m.*l_az.*m_a+dd_m.*l_az.*m_f-dd_m.*l_fx.*m_f.*sin(theta_a)-d_m.*dtheta_a.*l_fx.*m_f.*cos(theta_a)-dtheta_a.*l_az.*l_fx.*m_f.*cos(theta_a)-dtheta_a.*l_ax.*l_fx.*m_f.*sin(theta_a),-d_m.*dtheta_p.*m_a-d_m.*dtheta_p.*m_f-dtheta_p.*l_az.*m_a-dtheta_p.*l_az.*m_f+dtheta_a.*l_fx.*m_f.*sin(theta_a)+dtheta_p.*l_fx.*m_f.*sin(theta_a)];
mt2 = [l_fx.*m_f.*(-dd_m.*sin(theta_a)+d_m.*dtheta_p.*cos(theta_a)+dtheta_p.*l_az.*cos(theta_a)+dtheta_p.*l_ax.*sin(theta_a)),dtheta_p.*r_w.*cos(theta_p).*(m_a+m_f),dtheta_p.*(d_m.*m_a+d_m.*m_f+l_az.*m_a+l_az.*m_f-l_fx.*m_f.*sin(theta_a)),0.0,-dtheta_p.*l_fx.*m_f.*sin(theta_a),-l_fx.*m_f.*r_w.*cos(theta_a+theta_p).*(dtheta_a+dtheta_p),-l_fx.*m_f.*(dtheta_a+dtheta_p).*(d_m.*cos(theta_a)+l_az.*cos(theta_a)+l_ax.*sin(theta_a)),l_fx.*m_f.*sin(theta_a).*(dtheta_a+dtheta_p),0.0];
C = reshape([mt1,mt2],4,4);
end
