function M = mass_matrix(theta_w,theta_p,d_m,theta_a,m_w,m_b,m_m,m_a,m_f,I_w,I_b,I_m,I_a,I_f,r_w,l_bx,l_bz,l_mx,l_mz,l_ax,l_az,l_fx)
%MASS_MATRIX
%    M = MASS_MATRIX(THETA_W,THETA_P,D_M,THETA_A,M_W,M_B,M_M,M_A,M_F,I_w,I_b,I_m,I_a,I_f,R_W,L_BX,L_BZ,L_MX,L_MZ,L_AX,L_AZ,L_FX)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-Dec-2025 17:24:07

mt1 = [I_w.*2.0+m_a.*r_w.^2+m_b.*r_w.^2+m_f.*r_w.^2+m_m.*r_w.^2+m_w.*r_w.^2.*2.0,-m_f.*r_w.*(-cos(theta_p).*(d_m+l_az)+l_fx.*sin(theta_a+theta_p)+l_ax.*sin(theta_p))+m_a.*r_w.*(cos(theta_p).*(d_m+l_az)-l_ax.*sin(theta_p))+m_b.*r_w.*(l_bz.*cos(theta_p)-l_bx.*sin(theta_p))+m_m.*r_w.*(l_mz.*cos(theta_p)-l_mx.*sin(theta_p)),r_w.*sin(theta_p).*(m_a+m_f),-l_fx.*m_f.*r_w.*sin(theta_a+theta_p),-m_f.*r_w.*(-cos(theta_p).*(d_m+l_az)+l_fx.*sin(theta_a+theta_p)+l_ax.*sin(theta_p))+m_a.*r_w.*(cos(theta_p).*(d_m+l_az)-l_ax.*sin(theta_p))+m_b.*r_w.*(l_bz.*cos(theta_p)-l_bx.*sin(theta_p))+m_m.*r_w.*(l_mz.*cos(theta_p)-l_mx.*sin(theta_p))];
mt2 = [I_a+I_b+I_f+I_m+d_m.^2.*m_a+d_m.^2.*m_f+l_ax.^2.*m_a+l_az.^2.*m_a+l_bx.^2.*m_b+l_bz.^2.*m_b+l_ax.^2.*m_f+l_az.^2.*m_f+l_fx.^2.*m_f+l_mx.^2.*m_m+l_mz.^2.*m_m+d_m.*l_az.*m_a.*2.0+d_m.*l_az.*m_f.*2.0+l_ax.*l_fx.*m_f.*cos(theta_a).*2.0-d_m.*l_fx.*m_f.*sin(theta_a).*2.0-l_az.*l_fx.*m_f.*sin(theta_a).*2.0,-l_ax.*m_a-l_ax.*m_f-l_fx.*m_f.*cos(theta_a),I_f+l_fx.^2.*m_f+l_ax.*l_fx.*m_f.*cos(theta_a)-d_m.*l_fx.*m_f.*sin(theta_a)-l_az.*l_fx.*m_f.*sin(theta_a),r_w.*sin(theta_p).*(m_a+m_f),-l_ax.*m_a-l_ax.*m_f-l_fx.*m_f.*cos(theta_a),m_a+m_f,-l_fx.*m_f.*cos(theta_a),-l_fx.*m_f.*r_w.*sin(theta_a+theta_p)];
mt3 = [I_f+l_fx.^2.*m_f+l_ax.*l_fx.*m_f.*cos(theta_a)-d_m.*l_fx.*m_f.*sin(theta_a)-l_az.*l_fx.*m_f.*sin(theta_a),-l_fx.*m_f.*cos(theta_a),I_f+l_fx.^2.*m_f];
M = reshape([mt1,mt2,mt3],4,4);
end
