/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheeled_robot_lift_fork_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};

/* wheeled_robot_lift_fork_expl_ode_fun:(i0[8],i1[3],i2[])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a03=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a04=31.;
  a05=961.;
  a06=1.0500000000000000e+00;
  a07=arg[0]? arg[0][2] : 0;
  a06=(a06+a07);
  a07=2.;
  a08=arg[0]? arg[0][1] : 0;
  a09=cos(a08);
  a10=(a07*a09);
  a10=(a06*a10);
  a11=2.9999999999999999e-01;
  a12=arg[0]? arg[0][3] : 0;
  a12=(a08+a12);
  a13=sin(a12);
  a14=(a11*a13);
  a15=(a07*a14);
  a10=(a10-a15);
  a16=-1.0000000000000001e-01;
  a08=sin(a08);
  a07=(a07*a08);
  a17=(a16*a07);
  a10=(a10-a17);
  a17=5.;
  a18=(a17*a09);
  a19=(a06*a18);
  a10=(a10+a19);
  a17=(a17*a08);
  a19=(a16*a17);
  a10=(a10-a19);
  a19=1.2000000000000000e+00;
  a18=(a19*a18);
  a10=(a10+a18);
  a18=-1.4999999999999999e-01;
  a20=(a18*a17);
  a10=(a10-a20);
  a20=5.0000000000000000e-01;
  a21=16.;
  a21=(a21*a09);
  a21=(a20*a21);
  a10=(a10+a21);
  a21=casadi_sq(a10);
  a05=(a05+a21);
  a07=(a07+a17);
  a17=casadi_sq(a07);
  a05=(a05+a17);
  a17=casadi_sq(a15);
  a05=(a05+a17);
  a05=sqrt(a05);
  a04=(a04/a05);
  a17=arg[1]? arg[1][0] : 0;
  a21=2.0000000000000001e-01;
  a17=(a17/a21);
  a21=(a02*a09);
  a22=(a16*a01);
  a23=(a22*a09);
  a24=(a06*a01);
  a25=(a24*a08);
  a23=(a23+a25);
  a23=(a21-a23);
  a26=(a01+a03);
  a12=cos(a12);
  a27=(a11*a12);
  a28=(a26*a27);
  a29=(a23-a28);
  a29=(a29+a29);
  a30=2.5000000000000000e+00;
  a23=(a23+a23);
  a23=(a30*a23);
  a31=(a29+a23);
  a32=(a18*a01);
  a33=(a32*a09);
  a34=(a19*a01);
  a35=(a34*a08);
  a33=(a33+a35);
  a33=(a33+a33);
  a33=(a30*a33);
  a31=(a31-a33);
  a36=8.;
  a37=(a20*a01);
  a38=(a37*a08);
  a38=(a38+a38);
  a38=(a36*a38);
  a31=(a31-a38);
  a31=(a31*a01);
  a39=(a09*a01);
  a39=(a39+a39);
  a40=(a30*a39);
  a41=(a39+a40);
  a41=(a41*a02);
  a31=(a31+a41);
  a28=(a28+a28);
  a41=(a28*a03);
  a31=(a31-a41);
  a17=(a17-a31);
  a31=(a04*a17);
  a10=(a10/a05);
  a41=1.0000000000000001e-01;
  a42=(a26*a14);
  a43=(a41*a01);
  a44=(a43*a08);
  a45=(a24*a09);
  a44=(a44+a45);
  a46=(a02*a08);
  a44=(a44+a46);
  a47=(a42-a44);
  a47=(a47+a47);
  a48=(a09*a47);
  a49=(a43*a09);
  a49=(a49-a25);
  a49=(a49+a21);
  a21=(a27*a26);
  a21=(a49-a21);
  a21=(a21+a21);
  a25=(a21*a08);
  a48=(a48-a25);
  a25=(a41*a48);
  a50=(a27*a47);
  a51=(a21*a14);
  a50=(a50-a51);
  a52=(a21*a09);
  a47=(a08*a47);
  a52=(a52+a47);
  a52=(a06*a52);
  a52=(a50+a52);
  a25=(a25-a52);
  a52=(a22*a08);
  a52=(a00-a52);
  a52=(a52+a45);
  a52=(a52+a46);
  a46=(a14*a26);
  a46=(a52-a46);
  a46=(a46+a46);
  a45=(a46*a27);
  a47=(a14*a29);
  a47=(a45+a47);
  a25=(a25-a47);
  a53=(a09*a29);
  a54=(a46*a08);
  a53=(a53-a54);
  a53=(a06*a53);
  a25=(a25+a53);
  a53=(a46*a09);
  a29=(a08*a29);
  a53=(a53+a29);
  a29=(a16*a53);
  a25=(a25-a29);
  a49=(a49+a49);
  a49=(a30*a49);
  a29=(a49*a09);
  a44=(a44+a44);
  a44=(a30*a44);
  a54=(a08*a44);
  a29=(a29-a54);
  a29=(a06*a29);
  a25=(a25-a29);
  a29=(a49*a08);
  a44=(a09*a44);
  a29=(a29+a44);
  a44=(a41*a29);
  a25=(a25-a44);
  a44=(a09*a23);
  a52=(a52+a52);
  a52=(a30*a52);
  a54=(a52*a08);
  a44=(a44-a54);
  a44=(a06*a44);
  a25=(a25+a44);
  a44=(a52*a09);
  a23=(a08*a23);
  a44=(a44+a23);
  a23=(a16*a44);
  a25=(a25-a23);
  a23=1.4999999999999999e-01;
  a54=(a23*a01);
  a55=(a54*a09);
  a55=(a55-a35);
  a55=(a55+a55);
  a55=(a30*a55);
  a35=(a55*a09);
  a56=(a54*a08);
  a57=(a34*a09);
  a56=(a56+a57);
  a56=(a56+a56);
  a56=(a30*a56);
  a58=(a08*a56);
  a35=(a35-a58);
  a35=(a19*a35);
  a25=(a25-a35);
  a35=(a55*a08);
  a56=(a09*a56);
  a35=(a35+a56);
  a35=(a23*a35);
  a25=(a25-a35);
  a35=(a32*a08);
  a35=(a00-a35);
  a35=(a35+a57);
  a35=(a35+a35);
  a35=(a30*a35);
  a57=(a35*a08);
  a56=(a09*a33);
  a57=(a57+a56);
  a57=(a19*a57);
  a25=(a25-a57);
  a57=(a35*a09);
  a33=(a08*a33);
  a57=(a57-a33);
  a57=(a18*a57);
  a25=(a25-a57);
  a57=(a38*a09);
  a33=(a37*a09);
  a56=(a33+a33);
  a56=(a36*a56);
  a56=(a08*a56);
  a57=(a57+a56);
  a57=(a20*a57);
  a25=(a25+a57);
  a00=(a00+a33);
  a00=(a00+a00);
  a00=(a36*a00);
  a33=(a00*a08);
  a57=(a09*a38);
  a33=(a33+a57);
  a33=(a20*a33);
  a25=(a25-a33);
  a25=(a25*a01);
  a33=(a08*a01);
  a33=(a33+a33);
  a57=(a27*a33);
  a56=(a08*a21);
  a58=(a08*a33);
  a58=(a06*a58);
  a58=(a56-a58);
  a58=(a57-a58);
  a59=(a09*a33);
  a60=(a41*a59);
  a58=(a58-a60);
  a60=(a14*a39);
  a58=(a58-a60);
  a61=(a09*a46);
  a62=(a09*a39);
  a62=(a06*a62);
  a62=(a61+a62);
  a58=(a58+a62);
  a39=(a08*a39);
  a62=(a16*a39);
  a58=(a58-a62);
  a62=(a08*a49);
  a33=(a30*a33);
  a63=(a08*a33);
  a63=(a06*a63);
  a63=(a62-a63);
  a58=(a58-a63);
  a33=(a09*a33);
  a63=(a41*a33);
  a58=(a58-a63);
  a63=(a09*a52);
  a64=(a09*a40);
  a64=(a06*a64);
  a64=(a63+a64);
  a58=(a58+a64);
  a40=(a08*a40);
  a64=(a16*a40);
  a58=(a58-a64);
  a58=(a58*a02);
  a25=(a25+a58);
  a42=(a42+a42);
  a58=(a09*a42);
  a64=(a41*a58);
  a65=(a27*a42);
  a65=(a65-a51);
  a42=(a08*a42);
  a42=(a06*a42);
  a42=(a65+a42);
  a64=(a64-a42);
  a42=(a14*a28);
  a45=(a45-a42);
  a64=(a64-a45);
  a42=(a09*a28);
  a42=(a06*a42);
  a64=(a64-a42);
  a28=(a08*a28);
  a42=(a16*a28);
  a64=(a64+a42);
  a64=(a64*a03);
  a25=(a25+a64);
  a64=5.8860000000000001e+00;
  a64=(a64*a12);
  a42=-1.9620000000000001e+01;
  a51=(a42*a06);
  a51=(a08*a51);
  a51=(a64-a51);
  a66=-1.9620000000000002e+00;
  a66=(a66*a09);
  a51=(a51+a66);
  a66=-4.9050000000000004e+01;
  a67=(a66*a06);
  a67=(a08*a67);
  a51=(a51-a67);
  a67=-4.9050000000000011e+00;
  a67=(a67*a09);
  a51=(a51+a67);
  a67=-5.8859999999999999e+01;
  a67=(a67*a08);
  a51=(a51-a67);
  a67=-7.3574999999999999e+00;
  a67=(a67*a09);
  a51=(a51+a67);
  a67=-7.8480000000000004e+01;
  a67=(a67*a08);
  a51=(a51-a67);
  a67=(a26*a21);
  a67=(a11*a67);
  a13=(a13*a67);
  a51=(a51+a13);
  a67=(a02*a21);
  a67=(a08*a67);
  a51=(a51-a67);
  a67=(a24*a21);
  a67=(a09*a67);
  a51=(a51-a67);
  a21=(a43*a21);
  a21=(a08*a21);
  a51=(a51-a21);
  a26=(a26*a46);
  a11=(a11*a26);
  a12=(a12*a11);
  a51=(a51-a12);
  a11=(a02*a46);
  a11=(a09*a11);
  a51=(a51+a11);
  a11=(a24*a46);
  a11=(a08*a11);
  a51=(a51-a11);
  a46=(a22*a46);
  a46=(a09*a46);
  a51=(a51-a46);
  a46=(a02*a49);
  a46=(a08*a46);
  a51=(a51-a46);
  a46=(a24*a49);
  a46=(a09*a46);
  a51=(a51-a46);
  a43=(a43*a49);
  a43=(a08*a43);
  a51=(a51-a43);
  a43=(a02*a52);
  a43=(a09*a43);
  a51=(a51+a43);
  a24=(a24*a52);
  a24=(a08*a24);
  a51=(a51-a24);
  a22=(a22*a52);
  a22=(a09*a22);
  a51=(a51-a22);
  a22=(a34*a55);
  a22=(a09*a22);
  a51=(a51-a22);
  a54=(a54*a55);
  a54=(a08*a54);
  a51=(a51-a54);
  a34=(a34*a35);
  a34=(a08*a34);
  a51=(a51-a34);
  a32=(a32*a35);
  a32=(a09*a32);
  a51=(a51-a32);
  a38=(a37*a38);
  a38=(a09*a38);
  a51=(a51+a38);
  a37=(a37*a00);
  a37=(a08*a37);
  a51=(a51-a37);
  a25=(a25-a51);
  a51=(a10*a25);
  a31=(a31-a51);
  a07=(a07/a05);
  a51=arg[1]? arg[1][1] : 0;
  a48=(a48+a53);
  a48=(a48-a29);
  a48=(a48+a44);
  a48=(a48*a01);
  a39=(a39-a59);
  a39=(a39-a33);
  a39=(a39+a40);
  a39=(a39*a02);
  a48=(a48+a39);
  a58=(a58-a28);
  a58=(a58*a03);
  a48=(a48+a58);
  a42=(a42*a09);
  a66=(a66*a09);
  a42=(a42+a66);
  a56=(a01*a56);
  a42=(a42-a56);
  a61=(a01*a61);
  a42=(a42+a61);
  a62=(a01*a62);
  a42=(a42-a62);
  a63=(a01*a63);
  a42=(a42+a63);
  a48=(a48-a42);
  a51=(a51-a48);
  a48=(a07*a51);
  a31=(a31+a48);
  a15=(a15/a05);
  a48=arg[1]? arg[1][2] : 0;
  a57=(a57-a60);
  a57=(a57*a02);
  a50=(a50+a47);
  a50=(a50*a01);
  a57=(a57-a50);
  a65=(a65+a45);
  a65=(a65*a03);
  a57=(a57-a65);
  a64=(a64+a13);
  a64=(a64-a12);
  a57=(a57-a64);
  a48=(a48-a57);
  a57=(a15*a48);
  a31=(a31-a57);
  a57=2.9999999999999999e-02;
  a64=(a27+a27);
  a12=(a27*a64);
  a12=(a57+a12);
  a13=(a08*a64);
  a13=(a06*a13);
  a13=(a12+a13);
  a64=(a09*a64);
  a65=(a41*a64);
  a13=(a13-a65);
  a65=(a14+a14);
  a03=(a14*a65);
  a13=(a13+a03);
  a45=(a09*a65);
  a45=(a06*a45);
  a13=(a13-a45);
  a45=(a08*a65);
  a50=(a16*a45);
  a13=(a13+a50);
  a50=(a13*a10);
  a01=(a65*a04);
  a50=(a50-a01);
  a64=(a64+a45);
  a45=(a64*a07);
  a50=(a50-a45);
  a12=(a12+a03);
  a03=(a12*a15);
  a50=(a50-a03);
  a03=(a50*a15);
  a12=(a12+a03);
  a03=(a50*a10);
  a13=(a13-a03);
  a03=(a41*a09);
  a45=(a08*a06);
  a03=(a03-a45);
  a45=(a03-a27);
  a45=(a45+a45);
  a01=(a27*a45);
  a57=(a57-a01);
  a01=(a08*a45);
  a01=(a06*a01);
  a01=(a57-a01);
  a45=(a09*a45);
  a47=(a41*a45);
  a01=(a01+a47);
  a47=(a09*a06);
  a02=(a16*a08);
  a47=(a47-a02);
  a02=(a47-a14);
  a02=(a02+a02);
  a60=(a14*a02);
  a01=(a01-a60);
  a42=(a09*a02);
  a42=(a06*a42);
  a01=(a01+a42);
  a42=(a08*a02);
  a63=(a16*a42);
  a01=(a01-a63);
  a63=1.5310000000000001e-01;
  a01=(a01+a63);
  a03=(a03+a03);
  a03=(a30*a03);
  a63=(a08*a03);
  a63=(a06*a63);
  a01=(a01-a63);
  a03=(a09*a03);
  a63=(a41*a03);
  a01=(a01+a63);
  a47=(a47+a47);
  a47=(a30*a47);
  a63=(a09*a47);
  a63=(a06*a63);
  a01=(a01+a63);
  a63=(a08*a47);
  a62=(a16*a63);
  a01=(a01-a62);
  a62=9.4169999999999998e-01;
  a01=(a01+a62);
  a62=(a23*a09);
  a61=(a19*a08);
  a62=(a62-a61);
  a62=(a62+a62);
  a62=(a30*a62);
  a61=(a08*a62);
  a61=(a19*a61);
  a01=(a01-a61);
  a62=(a09*a62);
  a23=(a23*a62);
  a01=(a01+a23);
  a23=(a19*a09);
  a62=(a18*a08);
  a23=(a23-a62);
  a23=(a23+a23);
  a23=(a30*a23);
  a62=(a09*a23);
  a19=(a19*a62);
  a01=(a01+a19);
  a19=(a08*a23);
  a18=(a18*a19);
  a01=(a01-a18);
  a18=1.4533000000000000e+00;
  a01=(a01+a18);
  a18=(a36*a08);
  a18=(a08*a18);
  a18=(a20*a18);
  a01=(a01+a18);
  a36=(a36*a09);
  a18=(a09*a36);
  a20=(a20*a18);
  a01=(a01+a20);
  a02=(a02+a47);
  a02=(a02+a23);
  a02=(a02+a36);
  a36=(a02*a04);
  a23=(a01*a10);
  a36=(a36+a23);
  a45=(a45+a42);
  a45=(a45+a03);
  a45=(a45+a63);
  a63=(a45*a07);
  a36=(a36+a63);
  a57=(a57-a60);
  a60=(a57*a15);
  a36=(a36-a60);
  a60=(a36*a10);
  a01=(a01-a60);
  a60=(a36*a04);
  a02=(a02-a60);
  a60=casadi_sq(a02);
  a63=casadi_sq(a01);
  a60=(a60+a63);
  a63=(a36*a07);
  a45=(a45-a63);
  a63=casadi_sq(a45);
  a60=(a60+a63);
  a63=(a36*a15);
  a57=(a57+a63);
  a63=casadi_sq(a57);
  a60=(a60+a63);
  a60=sqrt(a60);
  a01=(a01/a60);
  a63=(a13*a01);
  a03=(a50*a04);
  a65=(a65+a03);
  a02=(a02/a60);
  a03=(a65*a02);
  a63=(a63-a03);
  a03=(a50*a07);
  a64=(a64+a03);
  a45=(a45/a60);
  a03=(a64*a45);
  a63=(a63-a03);
  a57=(a57/a60);
  a03=(a12*a57);
  a63=(a63+a03);
  a03=(a63*a57);
  a12=(a12-a03);
  a03=(a63*a01);
  a13=(a13-a03);
  a03=(a09+a09);
  a42=(a09*a03);
  a23=(a41*a42);
  a27=(a27*a03);
  a47=(a08*a03);
  a47=(a06*a47);
  a47=(a27+a47);
  a23=(a23-a47);
  a47=(a08+a08);
  a14=(a14*a47);
  a23=(a23-a14);
  a20=(a09*a47);
  a20=(a06*a20);
  a23=(a23+a20);
  a20=(a08*a47);
  a18=(a16*a20);
  a23=(a23-a18);
  a03=(a30*a03);
  a18=(a08*a03);
  a18=(a06*a18);
  a23=(a23-a18);
  a03=(a09*a03);
  a41=(a41*a03);
  a23=(a23+a41);
  a30=(a30*a47);
  a09=(a09*a30);
  a06=(a06*a09);
  a23=(a23+a06);
  a08=(a08*a30);
  a16=(a16*a08);
  a23=(a23-a16);
  a47=(a47+a30);
  a30=(a47*a04);
  a16=(a23*a10);
  a30=(a30+a16);
  a42=(a42+a20);
  a42=(a42+a03);
  a42=(a42+a08);
  a08=(a42*a07);
  a30=(a30+a08);
  a27=(a27+a14);
  a14=(a27*a15);
  a30=(a30+a14);
  a10=(a30*a10);
  a23=(a23-a10);
  a04=(a30*a04);
  a47=(a47-a04);
  a04=(a47*a02);
  a10=(a23*a01);
  a04=(a04+a10);
  a07=(a30*a07);
  a42=(a42-a07);
  a07=(a42*a45);
  a04=(a04+a07);
  a15=(a30*a15);
  a15=(a15-a27);
  a27=(a15*a57);
  a04=(a04+a27);
  a27=(a04*a01);
  a23=(a23-a27);
  a27=(a04*a02);
  a47=(a47-a27);
  a27=casadi_sq(a47);
  a07=casadi_sq(a23);
  a27=(a27+a07);
  a07=(a04*a45);
  a42=(a42-a07);
  a07=casadi_sq(a42);
  a27=(a27+a07);
  a07=(a04*a57);
  a15=(a15-a07);
  a07=casadi_sq(a15);
  a27=(a27+a07);
  a27=sqrt(a27);
  a23=(a23/a27);
  a07=(a13*a23);
  a10=(a63*a02);
  a65=(a65+a10);
  a47=(a47/a27);
  a10=(a65*a47);
  a07=(a07-a10);
  a10=(a63*a45);
  a64=(a64+a10);
  a42=(a42/a27);
  a10=(a64*a42);
  a07=(a07-a10);
  a15=(a15/a27);
  a10=(a12*a15);
  a07=(a07+a10);
  a10=(a07*a15);
  a12=(a12-a10);
  a10=(a07*a47);
  a65=(a65+a10);
  a10=casadi_sq(a65);
  a14=(a07*a23);
  a13=(a13-a14);
  a14=casadi_sq(a13);
  a10=(a10+a14);
  a14=(a07*a42);
  a64=(a64+a14);
  a14=casadi_sq(a64);
  a10=(a10+a14);
  a14=casadi_sq(a12);
  a10=(a10+a14);
  a10=sqrt(a10);
  a12=(a12/a10);
  a12=(a12*a48);
  a65=(a65/a10);
  a65=(a65*a17);
  a13=(a13/a10);
  a13=(a13*a25);
  a65=(a65+a13);
  a64=(a64/a10);
  a64=(a64*a51);
  a65=(a65+a64);
  a12=(a12-a65);
  a12=(a12/a10);
  a50=(a50*a12);
  a31=(a31-a50);
  a47=(a47*a17);
  a23=(a23*a25);
  a47=(a47-a23);
  a42=(a42*a51);
  a47=(a47+a42);
  a15=(a15*a48);
  a47=(a47+a15);
  a07=(a07*a12);
  a47=(a47-a07);
  a47=(a47/a27);
  a30=(a30*a47);
  a31=(a31-a30);
  a02=(a02*a17);
  a01=(a01*a25);
  a02=(a02-a01);
  a45=(a45*a51);
  a02=(a02+a45);
  a57=(a57*a48);
  a02=(a02+a57);
  a63=(a63*a12);
  a02=(a02-a63);
  a04=(a04*a47);
  a02=(a02-a04);
  a02=(a02/a60);
  a36=(a36*a02);
  a31=(a31-a36);
  a31=(a31/a05);
  if (res[0]!=0) res[0][4]=a31;
  if (res[0]!=0) res[0][5]=a02;
  if (res[0]!=0) res[0][6]=a47;
  if (res[0]!=0) res[0][7]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_lift_fork_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheeled_robot_lift_fork_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_lift_fork_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_robot_lift_fork_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheeled_robot_lift_fork_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheeled_robot_lift_fork_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheeled_robot_lift_fork_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheeled_robot_lift_fork_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheeled_robot_lift_fork_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int wheeled_robot_lift_fork_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wheeled_robot_lift_fork_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_robot_lift_fork_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheeled_robot_lift_fork_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_robot_lift_fork_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheeled_robot_lift_fork_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheeled_robot_lift_fork_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheeled_robot_lift_fork_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
