function M = mass_matrix(x,theta_p,d_m,theta_a,m_w,m_b,m_m,m_a,m_f,I_w,I_b,I_m,I_a,I_f,r_w,l_bx,l_bz,l_mx,l_mz,l_ax,l_az,l_fx)
%MASS_MATRIX
%    M = MASS_MATRIX(X,THETA_P,D_M,THETA_A,M_W,M_B,M_M,M_A,M_F,I_w,I_b,I_m,I_a,I_f,R_W,L_BX,L_BZ,L_MX,L_MZ,L_AX,L_AZ,L_FX)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    30-Dec-2025 18:07:37

mt1 = [m_a+m_b+m_f+m_m+m_w.*2.0+I_w.*1.0./r_w.^2.*2.0,(m_a.*(cos(theta_p).*(d_m+l_az).*2.0-l_ax.*sin(theta_p).*2.0))./2.0+(m_b.*(l_bz.*cos(theta_p).*2.0-l_bx.*sin(theta_p).*2.0))./2.0+(m_m.*(l_mz.*cos(theta_p).*2.0-l_mx.*sin(theta_p).*2.0))./2.0-(m_f.*(cos(theta_p).*(d_m+l_az).*-2.0+l_fx.*sin(theta_a+theta_p).*2.0+l_ax.*sin(theta_p).*2.0))./2.0,sin(theta_p).*(m_a+m_f),-l_fx.*m_f.*sin(theta_a+theta_p),(m_a.*(cos(theta_p).*(d_m+l_az).*2.0-l_ax.*sin(theta_p).*2.0))./2.0+(m_b.*(l_bz.*cos(theta_p).*2.0-l_bx.*sin(theta_p).*2.0))./2.0+(m_m.*(l_mz.*cos(theta_p).*2.0-l_mx.*sin(theta_p).*2.0))./2.0-(m_f.*(cos(theta_p).*(d_m+l_az).*-2.0+l_fx.*sin(theta_a+theta_p).*2.0+l_ax.*sin(theta_p).*2.0))./2.0];
mt2 = [I_a+I_b+I_f+I_m+d_m.^2.*m_a+d_m.^2.*m_f+l_ax.^2.*m_a+l_az.^2.*m_a+l_bx.^2.*m_b+l_bz.^2.*m_b+l_ax.^2.*m_f+l_az.^2.*m_f+l_fx.^2.*m_f+l_mx.^2.*m_m+l_mz.^2.*m_m+d_m.*l_az.*m_a.*2.0+d_m.*l_az.*m_f.*2.0+l_ax.*l_fx.*m_f.*cos(theta_a).*2.0-d_m.*l_fx.*m_f.*sin(theta_a).*2.0-l_az.*l_fx.*m_f.*sin(theta_a).*2.0,-l_ax.*m_a-l_ax.*m_f-l_fx.*m_f.*cos(theta_a),I_f+l_fx.^2.*m_f+l_ax.*l_fx.*m_f.*cos(theta_a)-d_m.*l_fx.*m_f.*sin(theta_a)-l_az.*l_fx.*m_f.*sin(theta_a),sin(theta_p).*(m_a+m_f),-l_ax.*m_a-l_ax.*m_f-l_fx.*m_f.*cos(theta_a),m_a+m_f,-l_fx.*m_f.*cos(theta_a),-l_fx.*m_f.*sin(theta_a+theta_p)];
mt3 = [I_f+l_fx.^2.*m_f+l_ax.*l_fx.*m_f.*cos(theta_a)-d_m.*l_fx.*m_f.*sin(theta_a)-l_az.*l_fx.*m_f.*sin(theta_a),-l_fx.*m_f.*cos(theta_a),I_f+l_fx.^2.*m_f];
M = reshape([mt1,mt2,mt3],4,4);
end
